// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.Entities.Models;

public partial class DbInstance
{
    public int Id { get; set; }

    public string ServerName { get; set; }

    public string ServerAddress { get; set; }

    public string AdminUser { get; set; }

    public string AdminPassword { get; set; }

    public string DbUser { get; set; }

    public string Password { get; set; }

    public string ReadOnlyUser { get; set; }

    public string ReadOnlyPassword { get; set; }

    public string DbName { get; set; }

    public bool? IsActive { get; set; }

    public DateTime AddNewTime { get; set; }

    public bool IsDefault { get; set; }

    public string EdmTempDirectory { get; set; }

    public virtual ICollection<ErpTenants> ErpTenants { get; set; } = new List<ErpTenants>();

    public virtual ICollection<MasterErpDatabaseRef> MasterErpDatabaseRefs { get; set; } = new List<MasterErpDatabaseRef>();
}
