// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.Entities.Models;

public partial class MasterErpDatabaseRef
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string UrlSourceMdf { get; set; }

    public string UrlSourceLdf { get; set; }

    public string UrlDestinationMdf { get; set; }

    public string UrlDestinationLdf { get; set; }

    public int? SqlServerInstanceId { get; set; }

    public DateTime AddNewTime { get; set; }

    public virtual DbInstance SqlServerInstance { get; set; }
}