// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.Entities.Models;

public partial class RefIdMap
{
    public Guid TenantGuid { get; set; }

    public string TableName { get; set; }

    public string SrcId { get; set; }

    public string TgtId { get; set; }

    public DateTime CreatedAt { get; set; }
}