// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.Entities.Models;

public partial class RefInitConfig
{
    public string TableName { get; set; }

    public string NeedDataInitialisation { get; set; }

    public bool? IsMapping { get; set; }
}