// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.Entities.Models;

public partial class TenantInitJob
{
    public long Id { get; set; }

    public int TenantId { get; set; }

    public string Status { get; set; }

    public int Attempts { get; set; }

    public int MaxAttempts { get; set; }

    public string LastError { get; set; }

    public string Payload { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}