// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class AAjustementConso
{
    public int Id { get; set; }

    public int AmortissementId { get; set; }

    public int? NumEcritureConsoFinal { get; set; }

    public string NumDocConsoFinal { get; set; }

    public double MontantConso { get; set; }

    public double MontantStatutaire { get; set; }

    public string Compte { get; set; }

    public string CompteContrePartie { get; set; }

    public int Annee { get; set; }

    public int DureeEnMois { get; set; }

    public DateTime DateCrea { get; set; }

    public string CreaPar { get; set; }

    public DateTime DateModif { get; set; }

    public string ModifPar { get; set; }

    public bool? Extourne { get; set; }

    public bool? Cession { get; set; }

    public bool GenerateFromCession { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual AAmortissement Amortissement { get; set; }
}

