// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class AAmortissementChange
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public string Utilisateur { get; set; }

    public int AmortissementId { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<AAmortissementChangeDetail> AAmortissementChangeDetails { get; set; } = new List<AAmortissementChangeDetail>();

[NotMapped]
    public virtual AAmortissement Amortissement { get; set; }
}

