// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ACessionAmortissement
{
    public int Id { get; set; }

    public int AmortissementId { get; set; }

    public int TypeCessionId { get; set; }

    public DateTime DateCession { get; set; }

    public double MontantAmorti { get; set; }

    public double MontantResiduel { get; set; }

    public string Libelle { get; set; }

    public DateTime DateCrea { get; set; }

    public string CreaPar { get; set; }

    public DateTime DateModif { get; set; }

    public string ModifPar { get; set; }

    public string NumDoc { get; set; }

    public double MontantAcquisition { get; set; }

    public double MontantVente { get; set; }

    public string CompteCessionCharge { get; set; }

    public string CompteCessionProfit { get; set; }

    public string NumDocTis { get; set; }

    public string CompteTransitoire { get; set; }

    public Guid TenantId { get; set; }

    public virtual AAmortissement Amortissement { get; set; }

    public virtual ATypeCession TypeCession { get; set; }
}