// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Action
{
    public int Id { get; set; }

    public string ActionName { get; set; }

    public virtual ICollection<GroupDocumentAction> GroupDocumentActions { get; set; } = new List<GroupDocumentAction>();

    public virtual ICollection<UserDocumentAction> UserDocumentActions { get; set; } = new List<UserDocumentAction>();
}
