// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class AEcritureAmortissementStatutaire
{
    public int Id { get; set; }

    public int AmortissementId { get; set; }

    public int NumEcritureProvisoire { get; set; }

    public string NumDocProvisoire { get; set; }

    public int? NumEcritureFinal { get; set; }

    public string NumDocFinal { get; set; }

    public int Pos { get; set; }

    public DateTime Date { get; set; }

    public short Annee { get; set; }

    public int Mois { get; set; }

    public short Sens { get; set; }

    public string Compte { get; set; }

    public string CompteContrePartie { get; set; }

    public double Montant { get; set; }

    public string Devise { get; set; }

    public double? MontantDevise { get; set; }

    public string CodeTva { get; set; }

    public double? MontantTva { get; set; }

    public string Text1 { get; set; }

    public string Text2 { get; set; }

    public double? MontantBrut { get; set; }

    public int Flag { get; set; }

    public double? TauxDevise { get; set; }

    public double? TauxTva { get; set; }

    public string TypePiece { get; set; }

    public bool IsMultiple { get; set; }

    public string CurrentUser { get; set; }

    public DateTime DateCrea { get; set; }

    public string CreaPar { get; set; }

    public DateTime DateModif { get; set; }

    public string ModifPar { get; set; }

    public bool? Cession { get; set; }

    public bool GenerateFromCession { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual AAmortissement Amortissement { get; set; }

    [NotMapped]
    public virtual PcCompteComptable PcCompteComptable { get; set; }

    [NotMapped]
    public virtual PcCompteComptable PcCompteComptableNavigation { get; set; }
}


