// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Agency
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string GroupAgency { get; set; }

    public bool? SiegeGroup { get; set; }

    public bool? SiegeGeneral { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<WfsAgency> WfsAgencies { get; set; } = new List<WfsAgency>();
}