// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class AidocEntity
{
    public int Id { get; set; }

    public string EntitiyName { get; set; }

    public string EntityAiinstruction { get; set; }

    public string EntityExtractorEngine { get; set; }

    public string EntityExtractorUrl { get; set; }

    public string EntityExtracotrKey { get; set; }

    public int EntityExtractorOcrDpiPrecision { get; set; }

    public virtual ICollection<AientityDocField> AientityDocFields { get; set; } = new List<AientityDocField>();
}
