// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class AientityDocField
{
    public int Id { get; set; }

    public int EntityDocId { get; set; }

    public string FieldName { get; set; }

    public string FieldType { get; set; }

    public string FieldAihelper { get; set; }

[NotMapped]
    public virtual AidocEntity EntityDoc { get; set; }
}

