// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class AiLog
{
    public int Id { get; set; }

    public string ModelLabel { get; set; }

    public string ModelGpt { get; set; }

    public string RequestData { get; set; }

    public long? RequestNbrTokens { get; set; }

    public string ReponseData { get; set; }

    public long? ResponseNbrTokens { get; set; }

    public bool? ResponseStatus { get; set; }

    public DateTime? CreateDate { get; set; }

    public string CreateBy { get; set; }

    public DateTime? EditDate { get; set; }

    public string EditBy { get; set; }

    public int? EntityId { get; set; }

    public Guid TenantId { get; set; }
}
