// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class AiModelSuggestion
{
    public int Id { get; set; }

    public string Suggestion { get; set; }

    public DateTime? CreateDate { get; set; }

    public string CreateBy { get; set; }

    public DateTime? EditDate { get; set; }

    public string EditBy { get; set; }

    public int? ModelId { get; set; }

    public int? EntityId { get; set; }

    public Guid TenantId { get; set; }

    public virtual AiModel Model { get; set; }
}