// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class AirlinesCompany
{
    public string CodeCompagnieAerienne { get; set; }

    public string NomCompagnieAerienne { get; set; }

    public string Session { get; set; }

    public string Available { get; set; }

    public string AddNewTime { get; set; }

    public string EditTime { get; set; }

    public string TransportType { get; set; }

    public string CodeIso { get; set; }

    public Guid TenantId { get; set; }
}