// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class APieceCorrectionAmortissement
{
    public int Id { get; set; }

    public int AmortissementId { get; set; }

    public string NumDoc { get; set; }

    public string Type { get; set; }

    public DateOnly? DateCrea { get; set; }

    public string CreateBy { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual AAmortissement Amortissement { get; set; }
}

