// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class AttendanceCorrectionValidationTemplate
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool MailToManager1 { get; set; }

    public int Manager1Id { get; set; }

    public bool MailToManager2 { get; set; }

    public int? Manager2Id { get; set; }

    public Guid TenantId { get; set; }
}
