// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ATypeAmortissement
{
    public int Id { get; set; }

    public string Libelle { get; set; }

    public DateTime DateCrea { get; set; }

    public string CreaPar { get; set; }

    public DateTime DateModif { get; set; }

    public string ModifPar { get; set; }

    public virtual ICollection<AAmortissement> AAmortissements { get; set; } = new List<AAmortissement>();
}
