// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ATypeCession
{
    public int Id { get; set; }

    public string Libelle { get; set; }

    public DateTime DateCrea { get; set; }

    public string CreaPar { get; set; }

    public DateTime DateModif { get; set; }

    public string ModifPar { get; set; }

    public string CompteCessionProfit { get; set; }

    public string CompteCessionCharge { get; set; }

    public bool MiseAuRebut { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<ACessionAmortissement> ACessionAmortissements { get; set; } = new List<ACessionAmortissement>();
}