// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class BankTransaction
{
    public long BankTransactionId { get; set; }

    public string ProviderName { get; set; }

    public string ProviderAccountId { get; set; }

    public string ProviderTransactionId { get; set; }

    public string SourceStatementId { get; set; }

    public string SourceEntryReference { get; set; }

    public string CamtMessageType { get; set; }

    public int? InternalAccountId { get; set; }

    public string InternalAccountCode { get; set; }

    public string AccountName { get; set; }

    public string AccountIban { get; set; }

    public string AccountBban { get; set; }

    public string AccountBic { get; set; }

    public string AccountCurrency { get; set; }

    public DateTime BookingDate { get; set; }

    public DateTime? ValueDate { get; set; }

    public DateTime? TransactionDateTime { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public string CreditDebitIndicator { get; set; }

    public decimal AmountSigned { get; set; }

    public decimal? FxRate { get; set; }

    public DateOnly? FxRateDate { get; set; }

    public string BaseCurrency { get; set; }

    public decimal? BaseAmount { get; set; }

    public string CounterpartyName { get; set; }

    public string CounterpartyAddress { get; set; }

    public string CounterpartyIban { get; set; }

    public string CounterpartyBban { get; set; }

    public string CounterpartyBic { get; set; }

    public string UltimateDebtorName { get; set; }

    public string UltimateCreditorName { get; set; }

    public string EndToEndId { get; set; }

    public string InstructionId { get; set; }

    public string MessageId { get; set; }

    public string PaymentInformationId { get; set; }

    public string MandateId { get; set; }

    public string CheckNumber { get; set; }

    public string SwissReferenceType { get; set; }

    public string SwissReferenceNumber { get; set; }

    public string SwissCreditorId { get; set; }

    public string BankTransactionCode { get; set; }

    public string ProprietaryCode { get; set; }

    public string ChargeBearer { get; set; }

    public string CategoryPurpose { get; set; }

    public string PurposeCode { get; set; }

    public string TransactionText { get; set; }

    public string RemittanceUnstructured { get; set; }

    public string RemittanceStructured { get; set; }

    public string AdditionalInfo { get; set; }

    public decimal? FeesAmount { get; set; }

    public string FeesCurrency { get; set; }

    public decimal? BalanceAfterAmount { get; set; }

    public string BalanceAfterCurrency { get; set; }

    public string MatchStatus { get; set; }

    public decimal? MatchConfidence { get; set; }

    public string MatchedEntityType { get; set; }

    public string MatchedEntityId { get; set; }

    public long? JournalEntryId { get; set; }

    public DateOnly? PostingDate { get; set; }

    public Guid FetchBatchId { get; set; }

    public DateTime FetchStartedUtc { get; set; }

    public DateTime? FetchFinishedUtc { get; set; }

    public string ProviderCursor { get; set; }

    public string ProviderConsentId { get; set; }

    public string ApiRequestId { get; set; }

    public string RawPayloadJson { get; set; }

    public byte[] RawHash { get; set; }

    public DateTime CreatedUtc { get; set; }

    public DateTime UpdatedUtc { get; set; }

    public bool IsDuplicate { get; set; }

    public bool IsReversal { get; set; }

    public string ReversedByProviderTxnId { get; set; }

    public byte[] Rowversion { get; set; }

    public string VoucherNumber { get; set; }

    public Guid TenantId { get; set; }
}