// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class BlinkPermission
{
    public int Id { get; set; }

    public string ProviderId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public Guid PermissionId { get; set; }

    public string AuthorizationUri { get; set; }

    public string Status { get; set; }

    public Guid ExternalReference { get; set; }

    public DateTime InsertDate { get; set; }

    public string UserGuid { get; set; }

    public string AgencyCode { get; set; }

    public DateTime? RevokeTime { get; set; }

    public string RevokedBy { get; set; }

    public Guid TenantId { get; set; }
}