// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class BlinkPaymentSubmission
{
    public long Id { get; set; }

    public int DebtorBankAccountId { get; set; }

    public string DebtorIban { get; set; }

    public string ProviderId { get; set; }

    public string ExternalReference { get; set; }

    public Guid? LocalPermissionId { get; set; }

    public string SubmissionId { get; set; }

    public string MessageId { get; set; }

    public string InstructionId { get; set; }

    public string EndToEndId { get; set; }

    public DateTime RequestedExecutionDate { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public string CreditorIban { get; set; }

    public string CreditorName { get; set; }

    public string CreditorCountry { get; set; }

    public string CreditorTownName { get; set; }

    public string CreditorStreetName { get; set; }

    public string CreditorBuildingNumber { get; set; }

    public string CreditorPostCode { get; set; }

    public string CreditorAddressLine1 { get; set; }

    public string CreditorAddressLine2 { get; set; }

    public string RemittanceInformation { get; set; }

    public string RemittanceReference { get; set; }

    public string RemittanceReferenceType { get; set; }

    public string ChargeBearer { get; set; }

    public string BookingInstruction { get; set; }

    public string StatusCode { get; set; }

    public string StatusReasonCode { get; set; }

    public string StatusReasonInformation { get; set; }

    public string RawRequestJson { get; set; }

    public string RawResponseJson { get; set; }

    public string RawStatusJson { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string SubmittedBy { get; set; }

    public DateTime? SubmittedOn { get; set; }

    public DateTime? LastStatusCheckDate { get; set; }

    public Guid TenantId { get; set; }
}