// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ConsoStepMapping
{
    public int Id { get; set; }

    public int? AgencyCode { get; set; }

    public string StepCode { get; set; }

    public int? ConsoCode { get; set; }

    public bool? TakeEndDate { get; set; }

    public string ConsoLabel { get; set; }

    public Guid TenantId { get; set; }

    public virtual StepsConsolidation ConsoCodeNavigation { get; set; }
}