// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class CoverLetterReportByAgencyTemp
{
    public string Piece { get; set; }

    public string NumProvisoire { get; set; }

    public string Agence { get; set; }

    public DateTime? DateEnregistrement { get; set; }

    public DateTime? Periode { get; set; }

    public string CategoriePiece { get; set; }

    public string Type { get; set; }

    public string TypeReglement { get; set; }

    public string ModeReglement { get; set; }

    public string Dossier { get; set; }

    public string CodeClient { get; set; }

    public string Client { get; set; }

    public string Division { get; set; }

    public string DossierSiege { get; set; }

    public bool? Facture { get; set; }

    public string StatutDossier { get; set; }

    public string RefPiece { get; set; }

    public DateTime? DateDocument { get; set; }

    public DateTime? DateEcheance { get; set; }

    public string Libelle { get; set; }

    public string Devise { get; set; }

    public double? Coef1 { get; set; }

    public double? Coef2 { get; set; }

    public double? MontantPiece { get; set; }

    public double? MontantOuvert { get; set; }

    public DateTime? DateValidation { get; set; }

    public DateTime? DateComptabilisation { get; set; }

    public string Observations { get; set; }

    public string NumeroTransmission { get; set; }

    public DateTime? DateTransmission { get; set; }

    public string UserName { get; set; }

    public int Id { get; set; }

    public Guid TenantId { get; set; }
}
