// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DashbordFilterCategory
{
    public string Code { get; set; }

    public string Label { get; set; }

    public string DbFieldsName { get; set; }

    public string DbQuery { get; set; }

    public virtual ICollection<DashbordFilterDetail> DashbordFilterDetails { get; set; } = new List<DashbordFilterDetail>();
}
