// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DashboardPermission
{
    public int Id { get; set; }

    public string PermissionLable { get; set; }

    public string PermissionCode { get; set; }

    public virtual ICollection<DashboardPermissionGroup> DashboardPermissionGroups { get; set; } = new List<DashboardPermissionGroup>();
}