// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DashboardStatusStep
{
    public int Id { get; set; }

    public int StatusId { get; set; }

    public string CodeEtape { get; set; }

    public bool IsMandatory { get; set; }

    public bool? SwimlaneMaster { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual WfsStatus Status { get; set; }
}

