// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DashbordFilter
{
    public int Id { get; set; }

    public string FilterName { get; set; }

    public string UserName { get; set; }

    public string DashbordId { get; set; }

    public bool? Isdefault { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<DashbordFilterDetail> DashbordFilterDetails { get; set; } = new List<DashbordFilterDetail>();
}