// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DashboardStatus
{
    public int Id { get; set; }

    public string StatusCode { get; set; }

    public string StatusLabel { get; set; }

    public int DashboadCategoryFamily { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual WfsCategoryFamily DashboadCategoryFamilyNavigation { get; set; }

    public virtual ICollection<DashboardCategoryStatus> DashboardCategoryStatuses { get; set; } = new List<DashboardCategoryStatus>();
}

