// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DashbordFilterDetail
{
    public int Id { get; set; }

    public string FilterCategoryCode { get; set; }

    public string FilterValue { get; set; }

    public int? DashbordFiltersId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual DashbordFilter DashbordFilters { get; set; }

[NotMapped]
    public virtual DashbordFilterCategory FilterCategoryCodeNavigation { get; set; }
}

