// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DashboardItemLabel
{
    public int Id { get; set; }

    public int ItemId { get; set; }

    public int LabelId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual DashBoardItem Item { get; set; }

[NotMapped]
    public virtual DashboardLabel Label { get; set; }
}

