// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DashboardItemComment
{
    public int Id { get; set; }

    public int ItemId { get; set; }

    public string Comment { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreateTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual DashBoardItem Item { get; set; }
}