// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DashboardLabel
{
    public int Id { get; set; }

    public string LabelText { get; set; }

    public string LabelColor { get; set; }

    public int? WfsCategoryId { get; set; }

    public int? TnColorsId { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<DashboardItemLabel> DashboardItemLabels { get; set; } = new List<DashboardItemLabel>();

[NotMapped]
    public virtual TnColor TnColors { get; set; }

[NotMapped]
    public virtual WfsCategory WfsCategory { get; set; }
}

