// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DashboardPriority
{
    public int Id { get; set; }

    public string PriorityName { get; set; }

    public string PriorityColor { get; set; }

    public string PriorityIcon { get; set; }

    public bool IsDefault { get; set; }

    public virtual ICollection<DashBoardItem> DashBoardItems { get; set; } = new List<DashBoardItem>();
}