// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DashboardItemTaskList
{
    public int Id { get; set; }

    public int ItemId { get; set; }

    public string TaskLabel { get; set; }

    public bool IsDone { get; set; }

    public DateTime? CloseDate { get; set; }

    public string ClosedBy { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreateTime { get; set; }

    public int ItemOrder { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual DashBoardItem Item { get; set; }
}

