// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DataRestriction
{
    public string Category { get; set; }

    public string ColumnName { get; set; }

    public string Type { get; set; }

    public int? MaxSize { get; set; }

    public bool? IsNullable { get; set; }

    public string DefaultValue { get; set; }

    public string SqlRequestValues { get; set; }
}