// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DispatchAnnexe
{
    public int Id { get; set; }

    public string Label { get; set; }

    public string DocumentCode { get; set; }

    public string AnnexeType { get; set; }

    public int? DispatchRequestId { get; set; }

    public string Observation { get; set; }

    public int? Gedid { get; set; }

    public int Order { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime EditedOn { get; set; }

    public string EditedBy { get; set; }

    public string EdmAgency { get; set; }

    public Guid TenantId { get; set; }
}