// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DispatchFileLogDetail
{
    public int Id { get; set; }

    public int? IdHeader { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public string PropertyName { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual DispatchFileLogDetail IdNavigation { get; set; }

[NotMapped]
    public virtual DispatchFileLogDetail InverseIdNavigation { get; set; }
}

