// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DispatchRequest
{
    public int Id { get; set; }

    public int? FileInvoicingWorkflowId { get; set; }

    public string Validator { get; set; }

    public string Responsable { get; set; }

    public DateTime CreateDate { get; set; }

    public string Observation { get; set; }

    public DateTime LastEditTime { get; set; }

    public string LastEditBy { get; set; }

    public string Status { get; set; }

    public string Sender { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<DispatchRequestInvoice> DispatchRequestInvoices { get; set; } = new List<DispatchRequestInvoice>();

    public virtual DispatchRequest IdNavigation { get; set; }

    public virtual DispatchRequest InverseIdNavigation { get; set; }
}