// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DispatchFileLogHeader
{
    public int Id { get; set; }

    public string SourceTableName { get; set; }

    public int? SourceId { get; set; }

    public DateTime EditTime { get; set; }

    public string Changer { get; set; }

    public string Description { get; set; }

    public Guid TenantId { get; set; }
}
