// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DispatchRequestInvoice
{
    public int Id { get; set; }

    public int DispatchRequestId { get; set; }

    public string InvoiceNumber { get; set; }

    public int? Order { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime EditedOn { get; set; }

    public string EditedBy { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual DispatchRequest DispatchRequest { get; set; }

[NotMapped]
    public virtual DispatchRequestInvoice IdNavigation { get; set; }

[NotMapped]
    public virtual DispatchRequestInvoice InverseIdNavigation { get; set; }

[NotMapped]
    public virtual TnPiece TnPiece { get; set; }
}

