// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DistanceDetail
{
    public string Vehicle { get; set; }

    public int Id { get; set; }

    public int? _202404 { get; set; }

    public int? _202405 { get; set; }

    public int? _202406 { get; set; }

    public int? _202407 { get; set; }

    public int? _202409 { get; set; }

    public Guid TenantId { get; set; }
}
