// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DocumentType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<DocumentSubType> DocumentSubTypes { get; set; } = new List<DocumentSubType>();
}
