// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DocumentSubType
{
    public int SubtypeId { get; set; }

    public int TypeId { get; set; }

    public string Name { get; set; }

    public Guid TenantId { get; set; }

    public virtual DocumentType Type { get; set; }
}