// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DsDetailsService
{
    public int Id { get; set; }

    public DateTime DateDebut { get; set; }

    public DateTime DateFin { get; set; }

    public double? NbreHeureNormal { get; set; }

    public double? NbreHeureOverTimeDay { get; set; }

    public double? NbreHeureOverTimeNight { get; set; }

    public double? NbreHeureWeekend { get; set; }

    public string DeviseId { get; set; }

    public double? TotalFrais { get; set; }

    public int FunctionId { get; set; }

    public double? TauxNormal { get; set; }

    public double? TauxOverTimeDay { get; set; }

    public double? TauxOverTimeNight { get; set; }

    public double? TauxWe { get; set; }

    public string Observation { get; set; }

    public DateTime? AddNewTime { get; set; }

    public DateTime? EditTime { get; set; }

    public string LastModifiedBy { get; set; }

    public string CreatedBy { get; set; }

    public string InvoicingType { get; set; }

    public Guid TenantId { get; set; }

    public string FileCode { get; set; }

    public int ServiceParametrageId { get; set; }

    public virtual TnDevise Devise { get; set; }

    public virtual ICollection<DsServiceDetailParticipant> DsServiceDetailParticipants { get; set; } = new List<DsServiceDetailParticipant>();

    public virtual TnDossier FileCodeNavigation { get; set; }

    public virtual DsDetailsService IdNavigation { get; set; }

    public virtual DsDetailsService InverseIdNavigation { get; set; }

    public virtual DsModeServiceTarif InvoicingTypeNavigation { get; set; }
}