// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DsReferenceDossier
{
    public int Id { get; set; }

    public int ServiceParametrageId { get; set; }

    public string Observation { get; set; }

    public DateTime? AddNewTime { get; set; }

    public DateTime? EditTime { get; set; }

    public string LastModifiedBy { get; set; }

    public string CreatedBy { get; set; }

    public int ServiceDossierId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual DsServiceDossier ServiceDossier { get; set; }

[NotMapped]
    public virtual DsServiceParametrage ServiceParametrage { get; set; }
}

