// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DsServiceParametrage
{
    public int Id { get; set; }

    public string Libelle { get; set; }

    public string Observation { get; set; }

    public string Categorie { get; set; }

    public int? Ordre { get; set; }

    public DateTime? AddNewTime { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<DsReferenceDossier> DsReferenceDossiers { get; set; } = new List<DsReferenceDossier>();

    public virtual ICollection<DsScopeDossier> DsScopeDossiers { get; set; } = new List<DsScopeDossier>();

    public virtual ICollection<DsServiceDossier> DsServiceDossierAutorites { get; set; } = new List<DsServiceDossier>();

    public virtual ICollection<DsServiceDossier> DsServiceDossierScopes { get; set; } = new List<DsServiceDossier>();

    public virtual ICollection<DsServiceDossier> DsServiceDossierServiceParametrages { get; set; } = new List<DsServiceDossier>();
}