// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DsServiceDetailParticipant
{
    public int Id { get; set; }

    public int TlcparticipantId { get; set; }

    public int ServiceDetailId { get; set; }

    public Guid TenantId { get; set; }

    public virtual DsDetailsService ServiceDetail { get; set; }
}