// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DsUserProfileDetail
{
    public int DmsuserId { get; set; }

    public string DmsuserName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? FonctionId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual DsUserFunction Fonction { get; set; }
}

