// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class DsZonesHoraire
{
    public int Id { get; set; }

    public int Day { get; set; }

    public DateTime OverTimeNightFrom1 { get; set; }

    public DateTime OverTimeNightTo1 { get; set; }

    public DateTime OverTimeDayFrom1 { get; set; }

    public DateTime OverTimeDayTo1 { get; set; }

    public DateTime NormalTimeFrom { get; set; }

    public DateTime NormalTimeTo { get; set; }

    public DateTime OverTimeDayFrom2 { get; set; }

    public DateTime OverTimeDayTo2 { get; set; }

    public DateTime OverTimeNightFrom2 { get; set; }

    public DateTime OverTimeNightTo2 { get; set; }

    public bool? IsWe { get; set; }

    public DateTime? AddNewTime { get; set; }

    public DateTime? EditTime { get; set; }

    public string LastModifiedBy { get; set; }

    public string CreatedBy { get; set; }

    public string CodeTypeTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual DsTypeTime CodeTypeTimeNavigation { get; set; }
}

