// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class EcritureOuvertureResultatTemp
{
    public int Id { get; set; }

    public int NumEcriture { get; set; }

    public int? Pos { get; set; }

    public DateTime? Date { get; set; }

    public short? Annee { get; set; }

    public short? Mois { get; set; }

    public string NumDoc { get; set; }

    public short? Sens { get; set; }

    public string Compte { get; set; }

    public string CompteContrePartie { get; set; }

    public double? Montant { get; set; }

    public string Devise { get; set; }

    public double? MontantDevise { get; set; }

    public string Text1 { get; set; }

    public int? Wwflag { get; set; }

    public double? Taux { get; set; }

    public string CreaPar { get; set; }

    public DateTime DateCrea { get; set; }

    public DateTime DateModif { get; set; }

    public string ModifPar { get; set; }

    public string TypePiece { get; set; }

    public bool? Ismultiple { get; set; }

    public string CurrentUser { get; set; }

    public double? MontantOuverturePrecedant { get; set; }

    public double? Difference { get; set; }

    public Guid TenantId { get; set; }
}
