// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class EcritureSupprimeeDetail
{
    public int Id { get; set; }

    public int NumEcriture { get; set; }

    public DateTime? Date { get; set; }

    public string NumDoc { get; set; }

    public short? Sens { get; set; }

    public string Compte { get; set; }

    public string CompteContrePartie { get; set; }

    public double? Montant { get; set; }

    public string Devise { get; set; }

    public double? MontantDevise { get; set; }

    public string Text1 { get; set; }

    public string Text2 { get; set; }

    public int? Wwflag { get; set; }

    public double? Taux { get; set; }

    public string CreaPar { get; set; }

    public DateTime? DateCrea { get; set; }

    public DateTime? DateModif { get; set; }

    public string ModifPar { get; set; }

    public string TypePiece { get; set; }

    public string CurrentUser { get; set; }

    public string CostCenter { get; set; }

    public string SupplierCode { get; set; }

    public string CustomerCode { get; set; }

    public string TreasuryCode { get; set; }

    public Guid TenantId { get; set; }
}
