// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class EcritureSupprimee
{
    public int Id { get; set; }

    public int NumEcriture { get; set; }

    public string Commentaire { get; set; }

    public string User { get; set; }

    public DateTime Date { get; set; }

    public DateTime? DateCrea { get; set; }

    public Guid TenantId { get; set; }
}