// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class EmergencyInvoiceToUpdateTemp
{
    public string NumPiece { get; set; }

    public int AuNomduClient { get; set; }

    public bool IsUpdated { get; set; }

    public Guid TenantId { get; set; }
}