// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Erpanomaly
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string AgencyCode { get; set; }

    public string Type { get; set; }

    public DateTime AddNewtime { get; set; }

    public Guid TenantId { get; set; }
}