// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Erpagency
{
    public int Id { get; set; }

    public string AgencyCode { get; set; }

    public string AgencyName { get; set; }

    public int AgencyGroupId { get; set; }

    public string AgencyDescription { get; set; }

    public bool IsAgencyGroup { get; set; }

    public bool IsHeadQuarter { get; set; }

    public string IconUrl { get; set; }

    public DateTime CreateDate { get; set; }

    public int? ParentAgency { get; set; }

    public int CountryId { get; set; }

    public string TaxId { get; set; }

    public string Street { get; set; }

    public string Building { get; set; }

    public string CodePostal { get; set; }

    public string City { get; set; }

    public string CountryAgency { get; set; }

    public string AgencyEmail { get; set; }

    public string Other { get; set; }

    public string PrintName { get; set; }

    public string NumTelephone { get; set; }

    public string Logo { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual ErpagencyGroup AgencyGroup { get; set; }

[NotMapped]
    public virtual ICollection<Erpagency> InverseParentAgencyNavigation { get; set; } = new List<Erpagency>();

[NotMapped]
    public virtual Erpagency ParentAgencyNavigation { get; set; }
}

