// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ErpcustomUserFilterHeader
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int GridIndentifierId { get; set; }

    public string ConfigName { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<ErpcustomUserFilterDetail> ErpcustomUserFilterDetails { get; set; } = new List<ErpcustomUserFilterDetail>();

    public virtual ErpgridIdentifier GridIndentifier { get; set; }

    public virtual User User { get; set; }
}