// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ErpcustomUserFilterDetail
{
    public int Id { get; set; }

    public int FilterId { get; set; }

    public string FilterDefaultValue { get; set; }

    public int CustomFilterHeaderId { get; set; }

    public Guid TenantId { get; set; }

    public virtual ErpcustomUserFilterHeader CustomFilterHeader { get; set; }
}