// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ErpcurrentDiskSpaceMonitoring
{
    public int Id { get; set; }

    public string ServerName { get; set; }

    public string ServerIpAdresse { get; set; }

    public string ServerType { get; set; }

    public string Agency { get; set; }

    public string Country { get; set; }

    public string Drive { get; set; }

    public DateTime ExecutionTime { get; set; }

    public double AvailableSpace { get; set; }

    public double TotalSpace { get; set; }

    public string Message { get; set; }

    public Guid TenantId { get; set; }
}
