// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ErpdiskSpaceMonitoring
{
    public int Id { get; set; }

    public int ServerId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Domain { get; set; }

    public string Drive { get; set; }

    public bool IsActive { get; set; }

    public int WarningLimitPercentage { get; set; }

    public int CriticalLimitPercentage { get; set; }

    public Guid TenantId { get; set; }

    public virtual Erpserver Server { get; set; }
}