// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ErpgridFilter
{
    public int Id { get; set; }

    public int GridIdentifierId { get; set; }

    public string ParamName { get; set; }

    public string ParamLabel { get; set; }

    public string ParamType { get; set; }

    public string FrontType { get; set; }

    public string DataBaseFieldName { get; set; }

    public string Operator { get; set; }

    public int OrderBy { get; set; }

    public string ListApiUrl { get; set; }

    public bool? ListIsMultiple { get; set; }

    public string DefaultValue { get; set; }

    public bool? ShowByDefault { get; set; }

    public string ListTextField { get; set; }

    public string ListValueField { get; set; }

    public bool IsRequired { get; set; }

    public int Width { get; set; }

[NotMapped]
    public virtual ErpgridIdentifier GridIdentifier { get; set; }
}

