// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ErpglobalConfig
{
    public int Id { get; set; }

    public string EnvironmentName { get; set; }

    public string TemporaryPhysicalPath { get; set; }

    public string VirtualDirectoryName { get; set; }

    public string ZipLibraryPath { get; set; }

    public string GlobalSmtpAccount { get; set; }

    public string GlobalSmtpUser { get; set; }

    public string GlobalSmtpPasswordHash { get; set; }

    public int GlobalSmtpPort { get; set; }

    public string GlobalDfsUserId { get; set; }

    public string GlobalDfsUserPassword { get; set; }

    public string GlobalDfsUserName { get; set; }

    public string ExecutionDnsDomain { get; set; }

    public string SignatureFile { get; set; }

    public string FrontDirectoryPath { get; set; }

    public string EntityEdmDirectory { get; set; }

    public virtual ICollection<Erpmodule> Erpmodules { get; set; } = new List<Erpmodule>();
}
