// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ErpgridStatus
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public int ModuleId { get; set; }

    public string GridName { get; set; }

    public string CurrentStatus { get; set; }

    public DateTime CreateDate { get; set; }

    public bool? DefaultValue { get; set; }

    public string Label { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual Erpmodule Module { get; set; }
}

