// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Erplanguage
{
    public int Id { get; set; }

    public string LanguageCode { get; set; }

    public string LanguageName { get; set; }

    public string CountryFlag { get; set; }

    public virtual ICollection<AgencyGroupTranslator> AgencyGroupTranslators { get; set; } = new List<AgencyGroupTranslator>();

    public virtual ICollection<ErpmoduleTranslator> ErpmoduleTranslators { get; set; } = new List<ErpmoduleTranslator>();

    public virtual ICollection<FavouriteTranslator> FavouriteTranslators { get; set; } = new List<FavouriteTranslator>();

    public virtual ICollection<GroupFamilyTranslator> GroupFamilyTranslators { get; set; } = new List<GroupFamilyTranslator>();

    public virtual ICollection<GroupTranslator> GroupTranslators { get; set; } = new List<GroupTranslator>();

    public virtual ICollection<RoleFamilyTranslator> RoleFamilyTranslators { get; set; } = new List<RoleFamilyTranslator>();

    public virtual ICollection<RoleTranslator> RoleTranslators { get; set; } = new List<RoleTranslator>();
}