// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Erpmodule
{
    public int Id { get; set; }

    public string Module { get; set; }

    public bool IsActive { get; set; }

    public int GlobalConfigId { get; set; }

    public string IconName { get; set; }

    public string IconStyle { get; set; }

    public bool? IsEdm { get; set; }

    public string DocumentationBaseUrl { get; set; }

    public string DocumentationSpace { get; set; }

    public string DocumentationFilterType { get; set; }

    public bool? IsRh { get; set; }

    public virtual ICollection<Erpfavourite> Erpfavourites { get; set; } = new List<Erpfavourite>();

    public virtual ICollection<ErpgridStatus> ErpgridStatuses { get; set; } = new List<ErpgridStatus>();

    public virtual ICollection<ErpmailTemplate> ErpmailTemplates { get; set; } = new List<ErpmailTemplate>();

    public virtual ICollection<ErpmoduleEntity> ErpmoduleEntities { get; set; } = new List<ErpmoduleEntity>();

    public virtual ICollection<ErpmoduleTranslator> ErpmoduleTranslators { get; set; } = new List<ErpmoduleTranslator>();

    public virtual ErpglobalConfig GlobalConfig { get; set; }

    public virtual ICollection<GroupFamily> GroupFamilies { get; set; } = new List<GroupFamily>();

    public virtual ICollection<RoleFamily> RoleFamilies { get; set; } = new List<RoleFamily>();
}