// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ErpmoduleEntity
{
    public int Id { get; set; }

    public int ModuleId { get; set; }

    public string EntityName { get; set; }

    public string EntitySqlServerName { get; set; }

    public string EntityDataBaseName { get; set; }

    public string EntityDataBaseUser { get; set; }

    public string EntityDataBasePassword { get; set; }

    public string EntitySsrsSqlServerName { get; set; }

    public string EntitySsrsSqlServerDataBase { get; set; }

    public string EntitySsrsSqlServerUser { get; set; }

    public string EntitySsrsSqlServerPassword { get; set; }

    public string EntitySsrsUrl { get; set; }

    public string EntitySmtpAccount { get; set; }

    public string EntitySmtpUser { get; set; }

    public string EntitySmtpPassword { get; set; }

    public int? EntitySmtpPort { get; set; }

    public string EntityEdmDirectory { get; set; }

    public bool? EntityEdmEnabled { get; set; }

    public string EntityEdmUserName { get; set; }

    public string EntityEdmPassword { get; set; }

    public string EntityEdmDomain { get; set; }

    public bool IsReadOnlyDataBase { get; set; }

    public bool IsActive { get; set; }

    public int? AgencyId { get; set; }

    public int? EdmModuleEntity { get; set; }

    public string SignaturePadAutomaticDirectoryPath { get; set; }

    public int? RhModuleEntity { get; set; }

[NotMapped]
    public virtual ErpmoduleEntity EdmModuleEntityNavigation { get; set; }

    public virtual ICollection<ErpuserModule> ErpuserModules { get; set; } = new List<ErpuserModule>();

[NotMapped]
    public virtual ICollection<ErpmoduleEntity> InverseEdmModuleEntityNavigation { get; set; } = new List<ErpmoduleEntity>();

[NotMapped]
    public virtual ICollection<ErpmoduleEntity> InverseRhModuleEntityNavigation { get; set; } = new List<ErpmoduleEntity>();

[NotMapped]
    public virtual Erpmodule Module { get; set; }

[NotMapped]
    public virtual ErpmoduleEntity RhModuleEntityNavigation { get; set; }
}

