// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ErpmailTemplate
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Label { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public int ModuleId { get; set; }

    public int? CategoryId { get; set; }

    public string MailFrom { get; set; }

    public string Signature { get; set; }

    public string ToEmail { get; set; }

    public Guid TenantId { get; set; }

    public virtual Erpmodule Module { get; set; }
}