// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ErpserverType
{
    public int Id { get; set; }

    public string ServerTypeLabel { get; set; }

    public string ServerTypeDescription { get; set; }

    public virtual ICollection<Erpserver> Erpservers { get; set; } = new List<Erpserver>();
}
