// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Erpserver
{
    public int Id { get; set; }

    public string ServerName { get; set; }

    public string ServerIpAddresse { get; set; }

    public string Description { get; set; }

    public int AgencyId { get; set; }

    public int ServerTypeId { get; set; }

    public virtual ICollection<ErpdiskSpaceMonitoring> ErpdiskSpaceMonitorings { get; set; } = new List<ErpdiskSpaceMonitoring>();

[NotMapped]
    public virtual ErpserverType ServerType { get; set; }
}

