// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ErpuserGridFilter
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int GridFilterId { get; set; }

    public int OrderBy { get; set; }

    public int? GridIdentifierId { get; set; }

    public Guid TenantId { get; set; }

    public virtual ErpgridIdentifier GridIdentifier { get; set; }

    public virtual User User { get; set; }
}