// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ExerciceComptable
{
    public int Id { get; set; }

    public string Libelle { get; set; }

    public DateTime DateDebut { get; set; }

    public DateTime DateFin { get; set; }

    public bool IsBloque { get; set; }

    public string CreaPar { get; set; }

    public DateTime DateCrea { get; set; }

    public string ModifPar { get; set; }

    public DateTime? DateModif { get; set; }

    public string CompteResultatCharge { get; set; }

    public string CompteResultatProfit { get; set; }

    public int? PlanComptableEntiteId { get; set; }

    public bool? IsCurrent { get; set; }

    public string CompteDta { get; set; }

    public string CompteDte { get; set; }

    public string CompteDtl { get; set; }

    public string CompteRe { get; set; }

    public string CompteBankOverDraft { get; set; }

    public string CompteCta { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<ExerciceComptableLog> ExerciceComptableLogs { get; set; } = new List<ExerciceComptableLog>();

    public virtual PcCompteComptable PcCompteComptable { get; set; }

    public virtual ICollection<PeriodeMensuelleLog> PeriodeMensuelleLogs { get; set; } = new List<PeriodeMensuelleLog>();

    public virtual ICollection<PeriodeMensuelle> PeriodeMensuelles { get; set; } = new List<PeriodeMensuelle>();

    public virtual PcPlanComptableEntite PlanComptableEntite { get; set; }
}