// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ExternalRateChangeDetail
{
    public int Id { get; set; }

    public int ExternalRataChangeId { get; set; }

    public string CurrencyFrom { get; set; }

    public double CurrencyFromRate { get; set; }

    public string CurrencyTo { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnDevise CurrencyFromNavigation { get; set; }

[NotMapped]
    public virtual TnDevise CurrencyToNavigation { get; set; }

[NotMapped]
    public virtual ExternalRateChange ExternalRataChange { get; set; }
}

