// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ExternalRateChange
{
    public int Id { get; set; }

    public string Label { get; set; }

    public DateTime RateDateFrom { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public bool DefaultRate { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<ExternalRateChangeDetail> ExternalRateChangeDetails { get; set; } = new List<ExternalRateChangeDetail>();
}