// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class FiClearingOperation
{
    public long Id { get; set; }

    public Guid ClearingGuid { get; set; }

    public string ClearingType { get; set; }

    public string OwnerCode { get; set; }

    public string BaseCurrency { get; set; }

    public DateOnly ClearingDate { get; set; }

    public string RatePolicy { get; set; }

    public string AllocationStrategy { get; set; }

    public string CloseMode { get; set; }

    public string PostMode { get; set; }

    public string CodeLettrage { get; set; }

    public bool Posted { get; set; }

    public DateTime? PostedAt { get; set; }

    public bool Canceled { get; set; }

    public Guid? CancelOfGuid { get; set; }

    public string CancelReason { get; set; }

    public decimal TotalAppliedBase { get; set; }

    public decimal TotalFxRealizedBase { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<FiClearingEntry> FiClearingEntries { get; set; } = new List<FiClearingEntry>();
}