// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class FiClearingEntry
{
    public long Id { get; set; }

    public Guid ClearingGuid { get; set; }

    public int LineSeq { get; set; }

    public string VoucherNumber { get; set; }

    public string PaymentNumber { get; set; }

    public string InvoicePieceType { get; set; }

    public string PaymentPieceType { get; set; }

    public string InvoiceCurrency { get; set; }

    public string PaymentCurrency { get; set; }

    public decimal RateAtClearingInvoice { get; set; }

    public decimal RateAtClearingPayment { get; set; }

    public decimal InvoiceCreateRate { get; set; }

    public decimal PaymentCreateRate { get; set; }

    public decimal AppliedOnInvoiceDoc { get; set; }

    public decimal AppliedOnPaymentDoc { get; set; }

    public decimal AppliedBase { get; set; }

    public decimal FxRealizedBase { get; set; }

    public decimal? ResultingInvoiceOpenDoc { get; set; }

    public decimal? ResultingInvoiceOpenBase { get; set; }

    public decimal? ResultingPaymentOpenDoc { get; set; }

    public decimal? ResultingPaymentOpenBase { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public virtual FiClearingOperation Clearing { get; set; }
}