// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class FileControlComment
{
    public string Code { get; set; }

    public string FileNumber { get; set; }

    public string Note { get; set; }

    public string CommentedBy { get; set; }

    public DateTime CommentTime { get; set; }

    public string ControlType { get; set; }

    public Guid TenantId { get; set; }
}