// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class FileTaskItem
{
    public int Id { get; set; }

    public string TaskItemName { get; set; }

    public int? FileTaskDefaultStatus { get; set; }

    public bool? DefaultIncludeInReporting { get; set; }

    public Guid TenantId { get; set; }

    public virtual FileTaskStatus FileTaskDefaultStatusNavigation { get; set; }

    public virtual ICollection<FileTaskTemplateItem> FileTaskTemplateItems { get; set; } = new List<FileTaskTemplateItem>();

    public virtual ICollection<FileTaskValue> FileTaskValues { get; set; } = new List<FileTaskValue>();
}