// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class FileTypeFileTaskTemplate
{
    public int Id { get; set; }

    public string FileType { get; set; }

    public int FileTaskTemplateId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual FileTaskTemplate FileTaskTemplate { get; set; }
}

