// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class FileTaskStatus
{
    public int Id { get; set; }

    public string StatusColor { get; set; }

    public int? StatusOrder { get; set; }

    public string TaskStatusName { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<FileTaskItem> FileTaskItems { get; set; } = new List<FileTaskItem>();

    public virtual ICollection<FileTaskValue> FileTaskValues { get; set; } = new List<FileTaskValue>();
}
