// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class FileTaskTemplateItem
{
    public int Id { get; set; }

    public int TemplateId { get; set; }

    public int TaskOrder { get; set; }

    public int FileTaskItemId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual FileTaskItem FileTaskItem { get; set; }

[NotMapped]
    public virtual FileTaskTemplate Template { get; set; }
}

