// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class FileTaskValue
{
    public int Id { get; set; }

    public string FileNumber { get; set; }

    public int FileTaskItemId { get; set; }

    public int FileTaskItemStatus { get; set; }

    public string FileTaskItemInternalObservation { get; set; }

    public string FileTaskItemObservation { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTime LastEditTime { get; set; }

    public int TaskOrder { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual FileTaskItem FileTaskItem { get; set; }

[NotMapped]
    public virtual FileTaskStatus FileTaskItemStatusNavigation { get; set; }

[NotMapped]
    public virtual TnDossier TnDossier { get; set; }
}

