// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class FrontTranslation
{
    public int Id { get; set; }

    public string LabelId { get; set; }

    public int HashCode { get; set; }

    public string Language { get; set; }

    public string LabelTranslation { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime EditedOn { get; set; }

    public string Notes { get; set; }

    public bool? IsValidated { get; set; }

    public string ValidatedBy { get; set; }

    public string LabelSource { get; set; }
}
