// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GcCaution
{
    public int Id { get; set; }

    public int? IdCompagnie { get; set; }

    public double? Montant { get; set; }

    public string Devise { get; set; }

    public string CodeTypeColisage { get; set; }

    public string Libelle { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnTypesColisage CodeTypeColisageNavigation { get; set; }

[NotMapped]
    public virtual GcCompagnieAgent IdCompagnieNavigation { get; set; }
}

