// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GcGestionConteneur
{
    public int Id { get; set; }

    public string NumDossier { get; set; }

    public string CodeDetailConnaissement { get; set; }

    public string CodeDevise { get; set; }

    public string PieceCaution { get; set; }

    public string PieceRemboursement { get; set; }

    public double? Montant { get; set; }

    public string Statut { get; set; }

    public DateTime? DateCreation { get; set; }

    public DateTime? DateSortie { get; set; }

    public DateTime? DateRetour { get; set; }

    public DateTime? DatePerdu { get; set; }

    public string Observation { get; set; }

    public int? Compagnie { get; set; }

    public int? NbJourEnlevement { get; set; }

    public int? NbJourDepotage { get; set; }

    public DateTime? AddNewTime { get; set; }

    public DateTime? EditTime { get; set; }

    public string LastModifiedBy { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? DateReceptionDocument { get; set; }

    public string RefDocument { get; set; }

    public DateTime? DateReelle { get; set; }

    public DateTime? EirpDate { get; set; }

    public string EirpObservation { get; set; }

    public DateTime? EirvDate { get; set; }

    public string EirvObservation { get; set; }

    public DateTime? ReclamationDate { get; set; }

    public string ReclamationObservation { get; set; }

    public DateTime? MailRecupDate { get; set; }

    public string MailRecupObservation { get; set; }

    public int? StatusId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnDetailsConnaissement CodeDetailConnaissementNavigation { get; set; }

[NotMapped]
    public virtual TnDevise CodeDeviseNavigation { get; set; }

    public virtual ICollection<GcHistoriqueGestionConteneur> GcHistoriqueGestionConteneurs { get; set; } = new List<GcHistoriqueGestionConteneur>();
}

