// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GcHistoriqueGestionConteneur
{
    public int Id { get; set; }

    public int GestionConteneurId { get; set; }

    public string ActionName { get; set; }

    public string Champ { get; set; }

    public string AncienneValeur { get; set; }

    public string NouvelleValeur { get; set; }

    public DateTime Date { get; set; }

    public string Utilisateur { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual GcGestionConteneur GestionConteneur { get; set; }
}

