// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GedCategorieGroupe
{
    public int Id { get; set; }

    public int CategorieId { get; set; }

    public int GroupId { get; set; }

    public bool CanUploadDocument { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual GedDocumentCategory Categorie { get; set; }

[NotMapped]
    public virtual GedGroupe Group { get; set; }
}

