// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GedCategorieType
{
    public int Id { get; set; }

    public int TypesId { get; set; }

    public int CategorieId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual GedDocumentCategory Categorie { get; set; }

    public virtual ICollection<GedCategorieTypeTypesDossier> GedCategorieTypeTypesDossiers { get; set; } = new List<GedCategorieTypeTypesDossier>();

[NotMapped]
    public virtual GedDocumentType Types { get; set; }
}

