// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GedDocumentDossier
{
    public int Id { get; set; }

    public int DocumentAttached { get; set; }

    public string NumDossier { get; set; }

    public string ColumnType { get; set; }

    public int? DocumentOrder { get; set; }

    public int? GroupId { get; set; }

    public Guid TenantId { get; set; }

    public virtual GedGroupe Group { get; set; }
}