// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GedDossier
{
    public string NumDossier { get; set; }

    public bool IsSpecial { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<GedDocumentType> GedDocumentTypes { get; set; } = new List<GedDocumentType>();
}
