// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GedDefaultType
{
    public int Id { get; set; }

    public int InterfaceId { get; set; }

    public string GroupType { get; set; }

    public int DocumentTypeId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual GedDocumentType DocumentType { get; set; }

[NotMapped]
    public virtual GedInterface Interface { get; set; }
}

