// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GedDocumentType
{
    public int Id { get; set; }

    public string TypeName { get; set; }

    public int TypeCategory { get; set; }

    public string UrlTemplate { get; set; }

    public string TypeNameFr { get; set; }

    public string TypeNameEn { get; set; }

    public string TypeNameEs { get; set; }

    public string TypeNamePt { get; set; }

    public string CodeTemplate { get; set; }

    public bool? RequiredValidation { get; set; }

    public string DefaultFolder { get; set; }

    public string TypeRole { get; set; }

    public bool Visible { get; set; }

    public bool? UseGrCodeRecogizing { get; set; }

    public bool? DownloadOnlyLastVersion { get; set; }

    public bool? NeedsEncryption { get; set; }

    public Guid TenantId { get; set; }

    public int? IndustryId { get; set; }

[NotMapped]
    public virtual GedDossier DefaultFolderNavigation { get; set; }

    public virtual ICollection<GedCategorieType> GedCategorieTypes { get; set; } = new List<GedCategorieType>();

    public virtual ICollection<GedDefaultType> GedDefaultTypes { get; set; } = new List<GedDefaultType>();

    public virtual ICollection<GedDocument> GedDocuments { get; set; } = new List<GedDocument>();

[NotMapped]
    public virtual GedDocumentCategory TypeCategoryNavigation { get; set; }
}

