// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GedInterface
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int GroupId { get; set; }

    public string Roles { get; set; }

    public virtual ICollection<GedDefaultType> GedDefaultTypes { get; set; } = new List<GedDefaultType>();

    public virtual ICollection<GedInterfaceAction> GedInterfaceActions { get; set; } = new List<GedInterfaceAction>();

    public virtual ICollection<GedInterfaceTab> GedInterfaceTabs { get; set; } = new List<GedInterfaceTab>();

    public virtual GedGroupe Group { get; set; }
}