// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GedInterfaceAction
{
    public int Id { get; set; }

    public int InterfaceId { get; set; }

    public int ActionId { get; set; }

    public virtual GedAction Action { get; set; }

    public virtual GedInterface Interface { get; set; }
}