// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GedInterfaceTab
{
    public int Id { get; set; }

    public int InterfaceId { get; set; }

    public int TabId { get; set; }

[NotMapped]
    public virtual GedInterface Interface { get; set; }

[NotMapped]
    public virtual GedTab Tab { get; set; }
}

