// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GedInsert
{
    public int Id { get; set; }

    public string FileName { get; set; }

    public bool? Result { get; set; }

    public string Message { get; set; }

    public string Agence { get; set; }

    public int GedBitId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual GedBulkInsert GedBit { get; set; }
}

