// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GlobalInvoicingKpi
{
    public string ClientCode { get; set; }

    public string ClientName { get; set; }

    public string InvoiceNumber { get; set; }

    public string FileNumber { get; set; }

    public string VoucherResponsable { get; set; }

    public string OperationValidator { get; set; }

    public string InvoicingRequestResponsable { get; set; }

    public DateTime FileOpenDate { get; set; }

    public DateTime FileSentForInvoicingDate { get; set; }

    public int? FileOpenToSentForInvoicing { get; set; }

    public DateTime? Draft { get; set; }

    public int? SentForInvoicingToDraft { get; set; }

    public DateTime? SentToOp { get; set; }

    public int? DraftToSentForOp { get; set; }

    public DateTime? ToRevise { get; set; }

    public int? OpToAskForRevision { get; set; }

    public DateTime? AcceptedByOp { get; set; }

    public int? OpToAccepted { get; set; }

    public DateTime? PendingClientOk { get; set; }

    public int? AcceptedToWaitingForClientOk { get; set; }

    public DateTime? ToSendToClient { get; set; }

    public int? WaitingForClientOkToSent { get; set; }

    public DateTime? Closed { get; set; }

    public int? InvoiceSentToClosed { get; set; }

    public int? DraftToClosed { get; set; }

    public int? FileSentToClosed { get; set; }

    public int? FileOpenToClosed { get; set; }

    public string MainFileAgency { get; set; }

    public string LocalFileAgency { get; set; }

    public string VoucherAgency { get; set; }

    public string FileType { get; set; }

    public string FileTypeName { get; set; }

    public string Activity { get; set; }

    public string Module { get; set; }

    public string VoucherType { get; set; }

    public string CurrentInvoicingRequestStatus { get; set; }

    public string VoucherTypeName { get; set; }

    public string VoucherNumber { get; set; }

    public double? TotalInVoucherCurrency { get; set; }

    public string VoucherCurrency { get; set; }

    public double? TotalInLocalCurrency { get; set; }

    public string LocalCurrency { get; set; }

    public double? ServicesInVoucherCurrency { get; set; }

    public double? ServicesInLocalCurrency { get; set; }

    public double? OutlaysInVoucherCurrency { get; set; }

    public double? OutlaysInLocalCurrency { get; set; }

    public DateTime? VoucherDate { get; set; }

    public string VoucherStatus { get; set; }

    public string FileStatus { get; set; }

    public DateTime FileDate { get; set; }

    public Guid TenantId { get; set; }
}