// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GroupDocumentAction
{
    public int Id { get; set; }

    public int GroupId { get; set; }

    public int ActionId { get; set; }

    public string TypePieceId { get; set; }

[NotMapped]
    public virtual Action Action { get; set; }

[NotMapped]
    public virtual Group Group { get; set; }
}

