// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Group
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? GroupFamilyId { get; set; }

    public virtual ICollection<GroupDocumentAction> GroupDocumentActions { get; set; } = new List<GroupDocumentAction>();

    public virtual GroupFamily GroupFamily { get; set; }

    public virtual ICollection<GroupRole> GroupRoles { get; set; } = new List<GroupRole>();

    public virtual ICollection<GroupTranslator> GroupTranslators { get; set; } = new List<GroupTranslator>();

    public virtual ICollection<GroupUser> GroupUsers { get; set; } = new List<GroupUser>();
}