// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class GroupUser
{
    public int Id { get; set; }

    public int GroupId { get; set; }

    public int UserId { get; set; }

    public Guid TenantId { get; set; }

    public virtual Group Group { get; set; }

    public virtual User User { get; set; }
}