// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class HolidayDetailTemplate
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime DayDate { get; set; }

    public int HolidayTemplateId { get; set; }

    public double Rate { get; set; }

    public DateTime? EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual HolidayTemplate HolidayTemplate { get; set; }
}