// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DMS.Entities.Models;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DMS.Entities.Models
{
    public partial interface IDmsReferenceContextFunctions
    {
        Task<List<fn_translations_by_menuResult>> fn_translations_by_menuAsync(string p_menu, CancellationToken cancellationToken = default);
    }
}
