// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ImportModel
{
    public string Make { get; set; }

    public string BaseModel { get; set; }

    public Guid TenantId { get; set; }
}
