// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class InstancePivot
{
    public int Id { get; set; }

    public string ColumnName { get; set; }

    public int? InstanceId { get; set; }

    public Guid TenantId { get; set; }
}