// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class InvInventoryLine
{
    public int Id { get; set; }

    public int ProductVariantId { get; set; }

    public int Gap { get; set; }

    public int RealQuantity { get; set; }

    public int? Quantity { get; set; }

    public DateTime? CreateDate { get; set; }

[NotMapped]
    public virtual InvProductVariant ProductVariant { get; set; }
}

