// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class InvLocation
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public int Position { get; set; }

    public int WarehouseId { get; set; }

    public int? ParentId { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public string Path { get; set; }

    public int? TypeId { get; set; }

    public virtual ICollection<InvLot> InvLots { get; set; } = new List<InvLot>();

    [NotMapped]
    public virtual ICollection<InvStockMovement> InvStockMovementDestinationLocations { get; set; } = new List<InvStockMovement>();

    [NotMapped]
    public virtual ICollection<InvStockMovement> InvStockMovementSourceLocations { get; set; } = new List<InvStockMovement>();

    public virtual ICollection<InvStockOperation> InvStockOperations { get; set; } = new List<InvStockOperation>();

[NotMapped]
    public virtual ICollection<InvLocation> InverseParent { get; set; } = new List<InvLocation>();

[NotMapped]
    public virtual InvLocation Parent { get; set; }

[NotMapped]
    public virtual InvLocationType TypeNavigation { get; set; }

[NotMapped]
    public virtual InvWarehouse Warehouse { get; set; }
}


