// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class InvLocationType
{
    public int Id { get; set; }

    public string Type { get; set; }

    public List<int> CompatibleParent { get; set; }

    public virtual ICollection<InvLocation> InvLocations { get; set; } = new List<InvLocation>();
}