// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class InvLot
{
    public int Id { get; set; }

    public string LotNumber { get; set; }

    public int? VariantProductId { get; set; }

    public int? InitialQuantity { get; set; }

    public int? Quantity { get; set; }

    public string Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public DateOnly? ExpirationDate { get; set; }

    public int? LocationId { get; set; }

    public int? OperationId { get; set; }

    [NotMapped]
    public virtual ICollection<InvStockMovement> InvStockMovements { get; set; } = new List<InvStockMovement>();

[NotMapped]
    public virtual InvLocation Location { get; set; }

[NotMapped]
    public virtual InvStockOperation Operation { get; set; }

[NotMapped]
    public virtual InvProductVariant VariantProduct { get; set; }
}


