// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class InvPackage
{
    public int Id { get; set; }

    public string PackageNumber { get; set; }

    public DateTime? PackagingDate { get; set; }

    public string Status { get; set; }
}
