// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class InvProduct
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Sku { get; set; }

    public double? Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public int? CategoryId { get; set; }

    public int? UnitCategoryId { get; set; }

[NotMapped]
    public virtual InvCategoryProduct Category { get; set; }

    public virtual ICollection<InvProductVariant> InvProductVariants { get; set; } = new List<InvProductVariant>();

[NotMapped]
    public virtual InvUnitCategory UnitCategory { get; set; }
}

