// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class InvStockMovement
{
    public int? LotId { get; set; }

    public int? SourceLocationId { get; set; }

    public int? DestinationLocationId { get; set; }

    public string Status { get; set; }

    public int? StockOperationId { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public int Id { get; set; }

    public virtual InvLocation DestinationLocation { get; set; }

    public virtual InvLot Lot { get; set; }

    public virtual InvLocation SourceLocation { get; set; }

    public virtual InvStockOperation StockOperation { get; set; }
}