// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class InvUnitCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime? CreateDate { get; set; }

    public virtual ICollection<InvProduct> InvProducts { get; set; } = new List<InvProduct>();

    public virtual ICollection<InvUnit> InvUnits { get; set; } = new List<InvUnit>();
}