// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class InvWarehouse
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Adress { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<InvLocation> InvLocations { get; set; } = new List<InvLocation>();
}