// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KanbanCardStep
{
    public int Id { get; set; }

    public string StepCode { get; set; }

    public int KanbanDashboardId { get; set; }

    public Guid TenantId { get; set; }
}