// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiacompteNonLieSurDesDossiersFacture
{
    public string VoucherNumber { get; set; }

    public string TypeReglement { get; set; }

    public string VoucherClientCode { get; set; }

    public string ClientCurrency { get; set; }

    public string VoucherClientName { get; set; }

    public string VoucherClientGroup { get; set; }

    public string MainFileAgency { get; set; }

    public string FileAgencyName { get; set; }

    public DateTime DatePiece { get; set; }

    public double? PaymentOpenAmountInVoucherCurrency { get; set; }

    public string File { get; set; }

    public string MainAgencyCode { get; set; }

    public string FileAgencyCode { get; set; }

    public double? PaymentOpenAmountInChf { get; set; }

    public Guid TenantId { get; set; }
}
