// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiConfig
{
    public int Id { get; set; }

    public string Label { get; set; }

    public string Activity { get; set; }

    public string FileType { get; set; }

    public string FromStep { get; set; }

    public bool? FromStepStart { get; set; }

    public string ToStep { get; set; }

    public bool? ToStepEnd { get; set; }

    public string GroupName { get; set; }

    public int? MinDays { get; set; }

    public int? MaxDays { get; set; }

    public Guid TenantId { get; set; }
}