// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpidashboardInstance
{
    public int Id { get; set; }

    public int? DashboardId { get; set; }

    public int? InstanceId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual KpiDashbord Dashboard { get; set; }

[NotMapped]
    public virtual KpiInstance Instance { get; set; }
}

