// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiExtraFieldTable
{
    public int Id { get; set; }

    public int? ResultExtraFieldId { get; set; }

    public int? TableId { get; set; }

[NotMapped]
    public virtual KpiResultExtraField ResultExtraField { get; set; }

[NotMapped]
    public virtual KpiTable Table { get; set; }
}

