// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiEntityBlocDetail
{
    public int Id { get; set; }

    public int? ConditionBlocId { get; set; }

    public int? ConditionDetailTemplateId { get; set; }

    public virtual KpiEntityBloc ConditionBloc { get; set; }

    public virtual KpiEntityDetail ConditionDetailTemplate { get; set; }
}