// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiEntityTable
{
    public int Id { get; set; }

    public int? EntityId { get; set; }

    public int? TableId { get; set; }

    public virtual KpiEntity Entity { get; set; }

    public virtual KpiTable Table { get; set; }
}