// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiEntityBloc
{
    public int Id { get; set; }

    public string Label { get; set; }

    public string Api { get; set; }

    public string Type { get; set; }

    public string Mode { get; set; }

    public string CodeValue { get; set; }

    public string ExtraInfoFields { get; set; }

    public string Views { get; set; }

    public string TextValue { get; set; }

    public int? ConditionId { get; set; }

    public int? BlocOrder { get; set; }

    public bool? IsMultiple { get; set; }

    public virtual KpiEntity Condition { get; set; }

    public virtual ICollection<KpiEntityBlocDetail> KpiEntityBlocDetails { get; set; } = new List<KpiEntityBlocDetail>();
}