// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiEntityDetail
{
    public int Id { get; set; }

    public string ConditionName { get; set; }

    public string Query { get; set; }

    public string Api { get; set; }

    public string CodeValue { get; set; }

    public string TextValue { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string EditBy { get; set; }

    public DateTime? EditDate { get; set; }

    public bool? HasValue { get; set; }

    public string AttributName { get; set; }

    public bool? Ispivot { get; set; }

    public virtual ICollection<KpiEntityBlocDetail> KpiEntityBlocDetails { get; set; } = new List<KpiEntityBlocDetail>();

    public virtual ICollection<KpiEntityDetailsTable> KpiEntityDetailsTables { get; set; } = new List<KpiEntityDetailsTable>();
}