// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiInstance
{
    public int Id { get; set; }

    public string InstanceName { get; set; }

    public string KpiStringQuery { get; set; }

    public string KpiJsonFlux { get; set; }

    public string KpiResult { get; set; }

    public DateTime? LastExecutionDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string EditBy { get; set; }

    public DateTime? EditDate { get; set; }

    public int? TemplateId { get; set; }

    public string KpiValueResult { get; set; }

    public bool? IsGrouped { get; set; }

    public bool? IsMultiWidget { get; set; }

    public string ChartType { get; set; }

    public string Mesure { get; set; }

    public int? RefreshAfterXminute { get; set; }

    public int? TableId { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<KpiInstanceResultValue> KpiInstanceResultValues { get; set; } = new List<KpiInstanceResultValue>();

    public virtual ICollection<KpidashboardInstance> KpidashboardInstances { get; set; } = new List<KpidashboardInstance>();

[NotMapped]
    public virtual KpiTable Table { get; set; }

[NotMapped]
    public virtual KpiTemplate Template { get; set; }
}

