// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiPermission
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public int? KpiDashboardId { get; set; }

    public int? KpiPermissionTypeId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public Guid TenantId { get; set; }

    public virtual KpiDashbord KpiDashboard { get; set; }

    public virtual KpiPermissionType KpiPermissionType { get; set; }
}