// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiPermissionType
{
    public int Id { get; set; }

    public string Label { get; set; }

    public string Code { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string EditBy { get; set; }

    public DateTime? EditDate { get; set; }

    public virtual ICollection<KpiPermission> KpiPermissions { get; set; } = new List<KpiPermission>();
}