// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiPivot
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Prefix { get; set; }

    public int? KpiTemplateId { get; set; }

    public virtual KpiTemplate KpiTemplate { get; set; }
}