// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpisyntheseVente
{
    public string VoucherNumber { get; set; }

    public string VoucherStatus { get; set; }

    public DateTime VoucherDate { get; set; }

    public string VoucherType { get; set; }

    public string VoucherClientCode { get; set; }

    public string VoucherClientName { get; set; }

    public string VoucherClientGroup { get; set; }

    public string VoucherReference { get; set; }

    public string VoucherResponsable { get; set; }

    public double Coef1 { get; set; }

    public double Coef2 { get; set; }

    public string EquivalentCurrency { get; set; }

    public double OpenAmountInEquivalentCurrency { get; set; }

    public double TotalAmountInEquivalentCurrency { get; set; }

    public string VoucherCurrency { get; set; }

    public double OpenAmountInVoucherCurrency { get; set; }

    public double TotalAmountInVoucherCurrency { get; set; }

    public string LocalCurrency { get; set; }

    public double OpenAmountInLocalCurrency { get; set; }

    public double TotalAmountInLocalCurrency { get; set; }

    public string GroupCurrency { get; set; }

    public int OpenAmountInChf { get; set; }

    public int TotalAmountInChf { get; set; }

    public string FileNumber { get; set; }

    public string FileClientCode { get; set; }

    public string FileClientName { get; set; }

    public DateTime? FilePeriod { get; set; }

    public string FileType { get; set; }

    public string Activity { get; set; }

    public string Module { get; set; }

    public string TransmissionNumber { get; set; }

    public DateTime? TransmissionDate { get; set; }

    public string TemporaryTransmissionNumber { get; set; }

    public DateTime? TemporaryTransmissionDate { get; set; }

    public string DossierAgent { get; set; }

    public double? LumInLocalCurrency { get; set; }

    public double? OutInLocalCurrency { get; set; }

    public double? SerInLocalCurrency { get; set; }

    public double? TvaInLocalCurrency { get; set; }

    public double? WhtInLocalCurrency { get; set; }

    public double? CssInLocalCurrency { get; set; }

    public DateTime? InsertDate { get; set; }

    public string MainAgencyCode { get; set; }

    public string VoucherAgency { get; set; }

    public double? ChfRate { get; set; }

    public double? LumChf { get; set; }

    public double? OutChf { get; set; }

    public double? SerChf { get; set; }

    public double? TvaChf { get; set; }

    public double? WhtChf { get; set; }

    public double? CssChf { get; set; }

    public double? PayableAmountInLocalCurrency { get; set; }

    public double? PayableAmountChf { get; set; }

    public double? ActualOpenAmountInVoucherCurrency { get; set; }

    public double? ActualOpenAmountInChf { get; set; }

    public double? OutAndServicesInChf { get; set; }

    public double? OutAndServicesInLocalCurrency { get; set; }

    public double? PayableAmountInClientCurrency { get; set; }

    public string FileAgencyCode { get; set; }

    public string FileAgencyName { get; set; }

    public string MainFileAgency { get; set; }

    public Guid TenantId { get; set; }
}