// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiTemplate
{
    public int Id { get; set; }

    public string Label { get; set; }

    public string MainQuery { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string EditBy { get; set; }

    public DateTime? EditDate { get; set; }

    public int? CategoryId { get; set; }

    public bool? IsMultiTable { get; set; }

    public virtual ICollection<KpiEntity> KpiEntities { get; set; } = new List<KpiEntity>();

    public virtual ICollection<KpiInstance> KpiInstances { get; set; } = new List<KpiInstance>();

    public virtual ICollection<KpiPivot> KpiPivots { get; set; } = new List<KpiPivot>();

    public virtual ICollection<KpiResultExtraField> KpiResultExtraFields { get; set; } = new List<KpiResultExtraField>();

    public virtual ICollection<KpiStaticFilter> KpiStaticFilters { get; set; } = new List<KpiStaticFilter>();

    public virtual ICollection<KpiTemplateTable> KpiTemplateTables { get; set; } = new List<KpiTemplateTable>();
}
