// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiTable
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Label { get; set; }

    public virtual ICollection<KpiEntityDetailsTable> KpiEntityDetailsTables { get; set; } = new List<KpiEntityDetailsTable>();

    public virtual ICollection<KpiEntityTable> KpiEntityTables { get; set; } = new List<KpiEntityTable>();

    public virtual ICollection<KpiExtraFieldTable> KpiExtraFieldTables { get; set; } = new List<KpiExtraFieldTable>();

    public virtual ICollection<KpiFixedFilterTable> KpiFixedFilterTables { get; set; } = new List<KpiFixedFilterTable>();

    public virtual ICollection<KpiInstance> KpiInstances { get; set; } = new List<KpiInstance>();

    public virtual ICollection<KpiTemplateTable> KpiTemplateTables { get; set; } = new List<KpiTemplateTable>();
}