// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class KpiTemplateTable
{
    public int Id { get; set; }

    public int? TemplateId { get; set; }

    public int? TableId { get; set; }

    public virtual KpiTable Table { get; set; }

    public virtual KpiTemplate Template { get; set; }
}