// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class LogWorkflow
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string ValdiationStatus { get; set; }

    public string CommentText { get; set; }

    public string EditedBy { get; set; }

    public string DestinatedUserOrGroup { get; set; }

    public DateOnly EditDate { get; set; }

    public string Type { get; set; }

    public Guid TenantId { get; set; }
}