// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class MailAutomationInstanceConfiguration
{
    public int Id { get; set; }

    public string ConfigurationName { get; set; }

    public int ConfigurationRuleConditionType { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string SupplierCode { get; set; }

    public string CostCenter { get; set; }

    public int? Account { get; set; }

    public string Currency { get; set; }

    public string DefaultTaxCode { get; set; }

    public Guid TenantId { get; set; }

    public virtual PcCompteComptable AccountNavigation { get; set; }

    public virtual TnCentresCout CostCenterNavigation { get; set; }

    public virtual TnDevise CurrencyNavigation { get; set; }

    public virtual ICollection<MailAutomationConfigurationRule> MailAutomationConfigurationRules { get; set; } = new List<MailAutomationConfigurationRule>();
}