// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class MaintenanceQuery
{
    public int Id { get; set; }

    public string QueryName { get; set; }

    public string CommandText { get; set; }

    public string Db { get; set; }

    public int Ordre { get; set; }

    public bool Ignore { get; set; }
}
