// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class MasterErpindustry
{
    public string CodeIndustry { get; set; }

    public string LabelIndustry { get; set; }

    public string DescriptionIndustry { get; set; }

    public int ProfilIndustry { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }
}
