// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ModelExport
{
    public string Constractor { get; set; }

    public string Model { get; set; }

    public Guid TenantId { get; set; }
}