// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class OutlaysLinkingRestriction
{
    public int Id { get; set; }

    public string DestinationVoucherType { get; set; }

    public string ForcePurchaseCotations { get; set; }

    public string Agence { get; set; }

    public string ForceOutlaysAccount { get; set; }

    public bool? ClientLocality { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnTypesPiece DestinationVoucherTypeNavigation { get; set; }
}