// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class PcAffectationGroup
{
    public int Id { get; set; }

    public string Pcaffectation { get; set; }

    public string GroupCompte { get; set; }
}