// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class PcCompteComptable
{
    public int Id { get; set; }

    public string Compte { get; set; }

    public string Designation { get; set; }

    public string Commentaire { get; set; }

    public string Type { get; set; }

    public string Function { get; set; }

    public string Affectation { get; set; }

    public string DeviseEtranger { get; set; }

    public string TextEcr { get; set; }

    public string CodeTva { get; set; }

    public bool? BloquerCodeTva { get; set; }

    public bool? ChangementAnnuelSansSolde { get; set; }

    public bool? ResumeExtraitCompte { get; set; }

    public bool? CompteImmobilise { get; set; }

    public bool? UniquementEcritureIndirects { get; set; }

    public DateTime? DateBlocageEcriture { get; set; }

    public string CalculCouts { get; set; }

    public string CompteTypeCout { get; set; }

    public string Schema { get; set; }

    public string CentreCout { get; set; }

    public string Section { get; set; }

    public string Complement1 { get; set; }

    public string Complement2 { get; set; }

    public string WwcompteComparatif { get; set; }

    public string CompteConsolidation { get; set; }

    public DateTime? DateCrea { get; set; }

    public string CreaPar { get; set; }

    public DateTime? DateModif { get; set; }

    public string ModifPar { get; set; }

    public bool Visible { get; set; }

    public bool? CentreCoutObligatoire { get; set; }

    public bool? SectionObligatoire { get; set; }

    public bool? IgnoreEquilibrage { get; set; }

    public bool? Bank { get; set; }

    public int? MappingFsId { get; set; }

    public bool Provision { get; set; }

    public string TypeCompte { get; set; }

    public string NoeudCompte { get; set; }

    public string Agence { get; set; }

    public bool? IgnoreFromFileAnalysis { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<AAmortissement> AAmortissementPcCompteComptableNavigations { get; set; } = new List<AAmortissement>();

    public virtual ICollection<AAmortissement> AAmortissementPcCompteComptables { get; set; } = new List<AAmortissement>();

    public virtual ICollection<AEcritureAmortissementStatutaire> AEcritureAmortissementStatutairePcCompteComptableNavigations { get; set; } = new List<AEcritureAmortissementStatutaire>();

    public virtual ICollection<AEcritureAmortissementStatutaire> AEcritureAmortissementStatutairePcCompteComptables { get; set; } = new List<AEcritureAmortissementStatutaire>();

    public virtual ICollection<AEcritureCoutAmortissementStatutaire> AEcritureCoutAmortissementStatutaires { get; set; } = new List<AEcritureCoutAmortissementStatutaire>();

[NotMapped]
    public virtual ICollection<ATypeImmobilisation> ATypeImmobilisationPcCompteComptable1s { get; set; } = new List<ATypeImmobilisation>();

    public virtual ICollection<ATypeImmobilisation> ATypeImmobilisationPcCompteComptableNavigations { get; set; } = new List<ATypeImmobilisation>();

    public virtual ICollection<ATypeImmobilisation> ATypeImmobilisationPcCompteComptables { get; set; } = new List<ATypeImmobilisation>();

    public virtual ICollection<ExerciceComptable> ExerciceComptables { get; set; } = new List<ExerciceComptable>();

    public virtual ICollection<MailAutomationInstanceConfiguration> MailAutomationInstanceConfigurations { get; set; } = new List<MailAutomationInstanceConfiguration>();

    public virtual ICollection<PcComptePlanComptableGroupe> PcComptePlanComptableGroupes { get; set; } = new List<PcComptePlanComptableGroupe>();

    public virtual ICollection<TnArticle> TnArticlePcCompteComptableNavigations { get; set; } = new List<TnArticle>();

    public virtual ICollection<TnArticle> TnArticlePcCompteComptables { get; set; } = new List<TnArticle>();

    public virtual ICollection<TnClient> TnClients { get; set; } = new List<TnClient>();

    public virtual ICollection<TnDetailsCompte> TnDetailsComptes { get; set; } = new List<TnDetailsCompte>();

    public virtual ICollection<TnProduitsStock> TnProduitsStocks { get; set; } = new List<TnProduitsStock>();
}

