// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class PcPlanComptableGroupe
{
    public int Id { get; set; }

    public string LibelleFr { get; set; }

    public string LibelleEn { get; set; }

    public string LibellePt { get; set; }

    public string LibelleEs { get; set; }

    public int? Parent { get; set; }

    public string Code { get; set; }

    public int OrderGroupe { get; set; }

    public string CreaPar { get; set; }

    public DateTime? DateCrea { get; set; }

    public DateTime? DateModif { get; set; }

    public string ModifPar { get; set; }

    public int? PlanComptableEntiteId { get; set; }

    public int? AncienId { get; set; }

    public bool Bloque { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<PcPlanComptableGroupe> InverseParentNavigation { get; set; } = new List<PcPlanComptableGroupe>();

    public virtual PcPlanComptableGroupe ParentNavigation { get; set; }

    public virtual ICollection<PcComptePlanComptableGroupe> PcComptePlanComptableGroupes { get; set; } = new List<PcComptePlanComptableGroupe>();

    public virtual PcPlanComptableEntite PlanComptableEntite { get; set; }
}