// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class PcPlanComptableEntite
{
    public int Id { get; set; }

    public string Libelle { get; set; }

    public int GroupeIdbilan { get; set; }

    public int GroupeIdresultat { get; set; }

    public bool Principal { get; set; }

    public Guid TenantId { get; set; }

    public int? CountryId { get; set; }

    public virtual ICollection<ExerciceComptable> ExerciceComptables { get; set; } = new List<ExerciceComptable>();

    public virtual ICollection<PcComptePlanComptableGroupe> PcComptePlanComptableGroupes { get; set; } = new List<PcComptePlanComptableGroupe>();

    public virtual ICollection<PcPlanComptableGroupe> PcPlanComptableGroupes { get; set; } = new List<PcPlanComptableGroupe>();
}
