// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class PeriodeMensuelleLog
{
    public int Id { get; set; }

    public int Annee { get; set; }

    public int Mois { get; set; }

    public bool IsBloque { get; set; }

    public string CreaPar { get; set; }

    public DateTime? DateCrea { get; set; }

    public DateTime? DateModif { get; set; }

    public string ModifPar { get; set; }

    public string Raison { get; set; }

    public int? Pcid { get; set; }

    public Guid TenantId { get; set; }

    public virtual ExerciceComptable Pc { get; set; }
}