// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Po
{
    public int Id { get; set; }

    public string NumPo { get; set; }

    public string DevisePo { get; set; }

    public string Observation { get; set; }

    public double TotalAmountPo { get; set; }

    public DateTime Podate { get; set; }

    public DateTime AddNewTime { get; set; }

    public string CreatedBy { get; set; }

    public DateTime EditTime { get; set; }

    public string ModifiedBy { get; set; }

    public bool? Closed { get; set; }

    public DateTime? PodateValid { get; set; }

    public string TypePo { get; set; }

    public bool? Running { get; set; }

    public decimal? Warning { get; set; }

    public string JobLocation { get; set; }

    public string JobLocationDescription { get; set; }

    public string SenderDuns { get; set; }

    public string ReceiverDuns { get; set; }

    public string SellerSupplierCode { get; set; }

    public string SellerName { get; set; }

    public string SellerAddressLine { get; set; }

    public string SellerAddressCity { get; set; }

    public string SellerAddressState { get; set; }

    public string SellerAddressPostalCode { get; set; }

    public string SellerAddressCountryCode { get; set; }

    public string SellerContactName { get; set; }

    public string SellerContactPhone { get; set; }

    public string SellerContractMail { get; set; }

    public string RemitToType { get; set; }

    public string RemitToValue { get; set; }

    public string SoldToType { get; set; }

    public string SoldToValue { get; set; }

    public string ShipToType { get; set; }

    public string ShipToValue { get; set; }

    public string ShipToName { get; set; }

    public string ShipToAddressLine { get; set; }

    public string ShipToAddressCity { get; set; }

    public string ShipToCountryCode { get; set; }

    public string Pofamily { get; set; }

    public string ShipToAddressPostalCode { get; set; }

    public string ShipToAddressState { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<Poclient> Poclients { get; set; } = new List<Poclient>();

    public virtual ICollection<Podetail> Podetails { get; set; } = new List<Podetail>();

    public virtual ICollection<Pofile> Pofiles { get; set; } = new List<Pofile>();
}