// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Poclient
{
    public int Id { get; set; }

    public int CodeClient { get; set; }

    public int Poid { get; set; }

    public DateTime AddNewTime { get; set; }

    public string CreatedBy { get; set; }

    public DateTime EditTime { get; set; }

    public string ModifiedBy { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnClient CodeClientNavigation { get; set; }

    public virtual Po Po { get; set; }
}