// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Podetail
{
    public int Id { get; set; }

    public string ObservationDetail { get; set; }

    public double DetailAmount { get; set; }

    public DateTime PodetailDate { get; set; }

    public DateTime AddNewTime { get; set; }

    public string CreatedBy { get; set; }

    public DateTime EditTime { get; set; }

    public string ModifiedBy { get; set; }

    public int Poid { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual Po Po { get; set; }
}

