// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class PoExtraInfo
{
    public int Id { get; set; }

    public DateTime? ExpectedDeliveryDate { get; set; }

    public string DeliveryAddress { get; set; }

    public DateTime? ExpectedRemovalDate { get; set; }

    public string Recipient { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public string VoucherNumber { get; set; }

    public string SupplierLabel { get; set; }

    public Guid TenantId { get; set; }
}