// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Pofile
{
    public int Id { get; set; }

    public int Poid { get; set; }

    public string NumDossier { get; set; }

    public DateTime CreateTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual Po Po { get; set; }

[NotMapped]
    public virtual TnDossier TnDossier { get; set; }
}

