// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class PolineItemMapping
{
    public int Id { get; set; }

    public string PolineItemNumber { get; set; }

    public string PointernalLinceItemCode { get; set; }

    public string PolineItemType { get; set; }

    public DateTime EditTime { get; set; }

    public DateTime AddNewTime { get; set; }

    public string LastEditedBy { get; set; }

    public bool IsDefault { get; set; }

    public int Poid { get; set; }

    public Guid TenantId { get; set; }
}