// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class PoPidxExecution
{
    public int Id { get; set; }

    public string ExecutionGuid { get; set; }

    public int Poid { get; set; }

    public DateTime RequestCreateTime { get; set; }

    public string RequestCreatedBy { get; set; }

    public string VoucherNumber { get; set; }

    public string ExecutionStatut { get; set; }

    public string Base64Pfd { get; set; }

    public string SentMessage { get; set; }

    public DateTime? SendMessageTime { get; set; }

    public string ReveivedResponse { get; set; }

    public DateTime? ReceivedResponseTime { get; set; }

    public Guid TenantId { get; set; }
}