// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DMS.Entities.Models;

public partial class postgresContext : DbContext
{
    public postgresContext(DbContextOptions<postgresContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TnActivite> TnActivites { get; set; }

    public virtual DbSet<TnArticle> TnArticles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("dms_5", "allocation_strategy", new[] { "FIFO", "BY_CURRENCY", "MANUAL" })
            .HasPostgresEnum("dms_5", "clearing_type", new[] { "CLIENT", "SUPPLIER" })
            .HasPostgresEnum("dms_5", "close_mode", new[] { "LEAVE_OPEN", "FORCE_CLOSE_WRITE_OFF" })
            .HasPostgresEnum("dms_5", "piece_type", new[] { "INVOICE", "CREDIT", "PAYMENT_IN", "PAYMENT_OUT" })
            .HasPostgresEnum("dms_5", "post_mode", new[] { "DRAFT", "POST_TO_GL" })
            .HasPostgresEnum("dms_5", "rate_policy", new[] { "ECB_SPOT", "BANK" })
            .HasPostgresEnum("dms_7", "allocation_strategy", new[] { "FIFO", "BY_CURRENCY", "MANUAL" })
            .HasPostgresEnum("dms_7", "clearing_type", new[] { "CLIENT", "SUPPLIER" })
            .HasPostgresEnum("dms_7", "close_mode", new[] { "LEAVE_OPEN", "FORCE_CLOSE_WRITE_OFF" })
            .HasPostgresEnum("dms_7", "piece_type", new[] { "INVOICE", "CREDIT", "PAYMENT_IN", "PAYMENT_OUT" })
            .HasPostgresEnum("dms_7", "post_mode", new[] { "DRAFT", "POST_TO_GL" })
            .HasPostgresEnum("dms_7", "rate_policy", new[] { "ECB_SPOT", "BANK" })
            .HasPostgresEnum("dms_new_ref", "allocation_strategy", new[] { "FIFO", "BY_CURRENCY", "MANUAL" })
            .HasPostgresEnum("dms_new_ref", "clearing_type", new[] { "CLIENT", "SUPPLIER" })
            .HasPostgresEnum("dms_new_ref", "close_mode", new[] { "LEAVE_OPEN", "FORCE_CLOSE_WRITE_OFF" })
            .HasPostgresEnum("dms_new_ref", "piece_type", new[] { "INVOICE", "CREDIT", "PAYMENT_IN", "PAYMENT_OUT" })
            .HasPostgresEnum("dms_new_ref", "post_mode", new[] { "DRAFT", "POST_TO_GL" })
            .HasPostgresEnum("dms_new_ref", "rate_policy", new[] { "ECB_SPOT", "BANK" })
            .HasPostgresEnum("dms_reference", "allocation_strategy", new[] { "FIFO", "BY_CURRENCY", "MANUAL" })
            .HasPostgresEnum("dms_reference", "clearing_type", new[] { "CLIENT", "SUPPLIER" })
            .HasPostgresEnum("dms_reference", "close_mode", new[] { "LEAVE_OPEN", "FORCE_CLOSE_WRITE_OFF" })
            .HasPostgresEnum("dms_reference", "piece_type", new[] { "INVOICE", "CREDIT", "PAYMENT_IN", "PAYMENT_OUT" })
            .HasPostgresEnum("dms_reference", "post_mode", new[] { "DRAFT", "POST_TO_GL" })
            .HasPostgresEnum("dms_reference", "rate_policy", new[] { "ECB_SPOT", "BANK" });

        modelBuilder.Entity<TnActivite>(entity =>
        {
            entity.HasKey(e => new { e.CodeActivite, e.TenantId }).HasName("tn_Activites_pk");

            entity.ToTable("tn_Activites", "dms_reference");

            entity.HasIndex(e => new { e.CodeActivite, e.TenantId }, "uq_tn_Activites_code_activite_tenant").IsUnique();

            entity.Property(e => e.CodeActivite)
                .HasMaxLength(10)
                .HasColumnName("Code Activite");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");
            entity.Property(e => e.AddNewTime).HasColumnType("timestamp without time zone");
            entity.Property(e => e.ConcernFacturation).HasColumnName("Concern Facturation");
            entity.Property(e => e.EditTime).HasColumnType("timestamp without time zone");
            entity.Property(e => e.IndustryId).HasColumnName("industryId");
            entity.Property(e => e.LibelleActivite)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("Libelle Activite");
            entity.Property(e => e.ModuleOperation)
                .IsRequired()
                .HasMaxLength(5)
                .HasColumnName("Module Operation");
        });

        modelBuilder.Entity<TnArticle>(entity =>
        {
            entity.HasKey(e => e.CodeArticle).HasName("tn_Articles_pk");

            entity.ToTable("tn_Articles", "dms_reference");

            entity.HasIndex(e => e.SalesCategory, "fki_tn_Articles$rubric_cotation$Code_Rubric_Cotation");

            entity.Property(e => e.CodeArticle).HasColumnName("Code Article");
            entity.Property(e => e.AccountPurchases)
                .HasMaxLength(15)
                .HasColumnName("Account Purchases");
            entity.Property(e => e.AccountSales)
                .HasMaxLength(15)
                .HasColumnName("Account Sales");
            entity.Property(e => e.CategorieArticle)
                .HasColumnType("character varying")
                .HasColumnName("Categorie Article");
            entity.Property(e => e.CategorieReference)
                .HasMaxLength(15)
                .HasColumnName("Categorie Reference");
            entity.Property(e => e.CentreCout)
                .HasMaxLength(10)
                .HasColumnName("Centre Cout");
            entity.Property(e => e.CompteReclassement).HasMaxLength(15);
            entity.Property(e => e.DescriptionArticle).HasColumnName("Description Article");
            entity.Property(e => e.GroupeArticle).HasColumnName("Groupe Article");
            entity.Property(e => e.IndustryId).HasColumnName("industryId");
            entity.Property(e => e.LibelleArticle)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("Libelle Article");
            entity.Property(e => e.LibelleAuto).HasColumnName("Libelle Auto");
            entity.Property(e => e.LibelleFr)
                .HasMaxLength(200)
                .HasColumnName("LibelleFR");
            entity.Property(e => e.LibelleUs)
                .HasMaxLength(200)
                .HasColumnName("LibelleUS");
            entity.Property(e => e.RowSource).HasMaxLength(15);
            entity.Property(e => e.SalesCategory).HasMaxLength(10);
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");
            entity.Property(e => e.TypeCompteArticle)
                .HasMaxLength(6)
                .HasColumnName("Type Compte Article");
        });
        modelBuilder.HasSequence("Ecriture_ID_seq", "dms_5");
        modelBuilder.HasSequence("Ecriture_ID_seq", "dms_7");
        modelBuilder.HasSequence("Ecriture_ID_seq", "dms_new_ref");
        modelBuilder.HasSequence("Ecriture_ID_seq", "dms_reference");
        modelBuilder.HasSequence("erp_countries_id_seq", "erpmaster");
        modelBuilder.HasSequence("erp_countries_id_seq", "erpmaster3");
        modelBuilder.HasSequence("ti_Relations_NÃ‚Â°_seq", "dms_5").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÃ‚Â°_seq", "dms_7").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÃ‚Â°_seq", "dms_new_ref").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÃ‚Â°_seq", "dms_reference").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÂ°_seq", "dms_5").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÂ°_seq", "dms_7").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÂ°_seq", "dms_reference").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÃƒâ€šÃ‚Â°_seq", "dms_new_ref").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÃƒâ€šÃ‚Â°_seq", "dms_reference").HasMax(2147483647L);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

}