// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class QrRequest
{
    public int RequestId { get; set; }

    public DateTime? AddNewTime { get; set; }

    public string CreatedBy { get; set; }

    public string GedDocumentId { get; set; }

    public string Dossier { get; set; }

    public string Type { get; set; }

    public Guid TenantId { get; set; }
}
