// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ReferenceSessionOption
{
    public int Id { get; set; }

    public string CategorieRefrence { get; set; }

    public int? CodeOption { get; set; }

    public string ValueOption { get; set; }
}
