// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class RegimesForStep
{
    public int Id { get; set; }

    public string StepCode { get; set; }

    public string RegimeCode { get; set; }

    public bool IsRequired { get; set; }

    public bool EndDateRequired { get; set; }

    public int Delay { get; set; }

    public Guid TenantId { get; set; }
}