// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ReplacersAndQuery
{
    public int Id { get; set; }

    public string Replacers { get; set; }

    public string Query { get; set; }

    public int EmailTemplateId { get; set; }
}
