// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class ReportTemplate
{
    public int Id { get; set; }

    public string TemplateName { get; set; }

    public string Body { get; set; }

    public string Engine { get; set; }

    public string Recipe { get; set; }

    public bool? DisplayHeaderFooter { get; set; }

    public string HeaderTemplate { get; set; }

    public string FooterTemplate { get; set; }

    public DateTime? AddNewTime { get; set; }

    public string ShortId { get; set; }

    public string Colors { get; set; }
}