// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class RlsApplyLog
{
    public DateTime AppliedAt { get; set; }

    public string TableName { get; set; }

    public string ResolvedRel { get; set; }

    public bool TenantAdded { get; set; }

    public long RowsUpdated { get; set; }

    public string PolicyName { get; set; }

    public string TriggerName { get; set; }

    public bool RlsEnabled { get; set; }
}