// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Role
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? FamilyId { get; set; }

    public virtual RoleFamily Family { get; set; }

    public virtual ICollection<GroupRole> GroupRoles { get; set; } = new List<GroupRole>();

    public virtual ICollection<RoleTranslator> RoleTranslators { get; set; } = new List<RoleTranslator>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}