// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class RoleFamily
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int ModuleId { get; set; }

[NotMapped]
    public virtual Erpmodule Module { get; set; }

    public virtual ICollection<RoleFamilyTranslator> RoleFamilyTranslators { get; set; } = new List<RoleFamilyTranslator>();

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}

