// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class SaftExportationHeader
{
    public int Id { get; set; }

    public string FileName { get; set; }

    public string FluxXml { get; set; }

    public DateTime DateExport { get; set; }

    public string Responsable { get; set; }

    public double TotalCredit { get; set; }

    public double TotalDebit { get; set; }

    public double NbrePiece { get; set; }

    public Guid TenantId { get; set; }

    public virtual SaftExportationHeader IdNavigation { get; set; }

    public virtual SaftExportationHeader InverseIdNavigation { get; set; }

    public virtual ICollection<SaftExportationDetail> SaftExportationDetails { get; set; } = new List<SaftExportationDetail>();
}