// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class SaftLetteringDetail
{
    public int Id { get; set; }

    public string CodeLettrageSaft { get; set; }

    public string StatutLettrage { get; set; }

    public DateTime DateLettrage { get; set; }

    public string SaftXml { get; set; }

    public double TotalCreditAmount { get; set; }

    public double TotalDebitAmount { get; set; }

    public bool Visible { get; set; }

    public string Raison { get; set; }

    public string Statut { get; set; }

    public string CreatedBy { get; set; }

    public string LetteringPieces { get; set; }

    public bool PrintedOnce { get; set; }

    public DateTime? AddNewTime { get; set; }

    public Guid TenantId { get; set; }
}
