// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class SaftExportationDetail
{
    public int Id { get; set; }

    public string NumPiece { get; set; }

    public double MontantPiece { get; set; }

    public string CurrentHashCode { get; set; }

    public string HashCode4Chiffre { get; set; }

    public string SaftXml { get; set; }

    public string Statut { get; set; }

    public string Raison { get; set; }

    public bool Visible { get; set; }

    public int? HeaderId { get; set; }

    public DateTime AddNewTime { get; set; }

    public string CreatedBy { get; set; }

    public string NumPieceSaft { get; set; }

    public string TaxCodes { get; set; }

    public double? WhTaxAmount { get; set; }

    public double? TaxAmount { get; set; }

    public string OwnerCode { get; set; }

    public Guid TenantId { get; set; }

    public virtual SaftExportationHeader Header { get; set; }
}