// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class SaftParameter
{
    public int Id { get; set; }

    public string Key { get; set; }

    public string Value { get; set; }

    public DateTime AddNewTime { get; set; }

    public string CreatedBy { get; set; }

    public DateTime EditTime { get; set; }

    public string LastModifiedBy { get; set; }

    public Guid TenantId { get; set; }
}