// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class SerieInstance
{
    public string Type { get; set; }

    public string FormatOptions { get; set; }

    public bool IsActive { get; set; }

    public int Id { get; set; }

    public bool IsVisible { get; set; }

    public string Category { get; set; }

    public Guid TenantId { get; set; }
}