// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class SofWorkLog
{
    public int Id { get; set; }

    public int Sof1 { get; set; }

    public int Sof2 { get; set; }

    public bool SplitByDay { get; set; }

    public DateTime AddNewTime { get; set; }

    public string AddedBy { get; set; }

    public string Observations { get; set; }

    public Guid TenantId { get; set; }
}
