// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class StColi
{
    public int Id { get; set; }

    public int DeclarationId { get; set; }

    public string NumColis { get; set; }

    public double? PoidsNet { get; set; }

    public double? PoidsBrut { get; set; }

    public string UnitePoids { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string LastModifiedBy { get; set; }

    public string CreatedBy { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual StDeclaration Declaration { get; set; }

    public virtual ICollection<StGroupProduct> StGroupProducts { get; set; } = new List<StGroupProduct>();

    public virtual ICollection<StProduct> StProducts { get; set; } = new List<StProduct>();
}

