// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class StDeclaration
{
    public int Id { get; set; }

    public string DeclarationNum { get; set; }

    public string SupplierName { get; set; }

    public string File { get; set; }

    public string CommercialInvoice { get; set; }

    public DateTime? CommercialInvoiceDate { get; set; }

    public string PoNum { get; set; }

    public DateTime? PoDate { get; set; }

    public DateTime DateDeclaration { get; set; }

    public string CodeRegime { get; set; }

    public string BlAwb { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string LastModifiedBy { get; set; }

    public string CreatedBy { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<StColi> StColis { get; set; } = new List<StColi>();

    public virtual ICollection<StProduct> StProducts { get; set; } = new List<StProduct>();
}
