// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class StepsConsolidation
{
    public int Id { get; set; }

    public string ConsoLabel { get; set; }

    public int? Ordre { get; set; }

    public string Group { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<ConsoStepMapping> ConsoStepMappings { get; set; } = new List<ConsoStepMapping>();
}
