// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class StGroupProduct
{
    public int Id { get; set; }

    public int ColisId { get; set; }

    public string Libelle { get; set; }

    public double Quantite { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string LastModifiedBy { get; set; }

    public string CreatedBy { get; set; }

    public double RemainingQuantity { get; set; }

    public Guid TenantId { get; set; }

    public virtual StColi Colis { get; set; }

    public virtual ICollection<StProduct> StProducts { get; set; } = new List<StProduct>();
}