// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class StLogHeader
{
    public int Id { get; set; }

    public int TableId { get; set; }

    public DateTime Date { get; set; }

    public string TableName { get; set; }

    public string UserName { get; set; }

    public string Action { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<StLogDetail> StLogDetails { get; set; } = new List<StLogDetail>();
}
