// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class StMovementUnit
{
    public int Id { get; set; }

    public int MovementProductId { get; set; }

    public int UnitId { get; set; }

    public double Quantity { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string LastModifiedBy { get; set; }

    public string CreatedBy { get; set; }

    public bool IsStockUnit { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual StMovementProduct MovementProduct { get; set; }

[NotMapped]
    public virtual StUnit Unit { get; set; }
}

