// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class StProduct
{
    public int Id { get; set; }

    public int DeclarationId { get; set; }

    public DateTime EntryDate { get; set; }

    public string ProductLabel { get; set; }

    public string Hscode { get; set; }

    public string Hsdetail { get; set; }

    public double RemainingQuantity { get; set; }

    public int UnitStock { get; set; }

    public double PriceUniteStock { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string LastModifiedBy { get; set; }

    public string CreatedBy { get; set; }

    public double QuantityStock { get; set; }

    public string Devise { get; set; }

    public int? GroupeProduitId { get; set; }

    public int ColisId { get; set; }

    public int QteParLot { get; set; }

    public string CodePays { get; set; }

    public Guid TenantId { get; set; }

    public virtual StColi Colis { get; set; }

    public virtual StDeclaration Declaration { get; set; }

    public virtual StGroupProduct GroupeProduit { get; set; }

    public virtual ICollection<StMovementProduct> StMovementProducts { get; set; } = new List<StMovementProduct>();

    public virtual StUnit UnitStockNavigation { get; set; }
}