// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class StUnit
{
    public int Id { get; set; }

    public string Label { get; set; }

    public double? Coefficient { get; set; }

    public int? Parent { get; set; }

    public int? GroupId { get; set; }

    public int? Order { get; set; }

    public bool IsStockUnit { get; set; }

    public Guid TenantId { get; set; }

    public virtual StGroupUnit Group { get; set; }

    public virtual ICollection<StUnit> InverseParentNavigation { get; set; } = new List<StUnit>();

    public virtual StUnit ParentNavigation { get; set; }

    public virtual ICollection<StMovementProduct> StMovementProducts { get; set; } = new List<StMovementProduct>();

    public virtual ICollection<StMovementUnit> StMovementUnits { get; set; } = new List<StMovementUnit>();

    public virtual ICollection<StProduct> StProducts { get; set; } = new List<StProduct>();
}