// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class SubCategory
{
    public int Id { get; set; }

    public string Label { get; set; }

    public string Description { get; set; }

    public DateTime? AddNewTime { get; set; }

    public DateTime? EditTime { get; set; }

    public int? CategoryId { get; set; }

    public Guid TenantId { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<VehicleOperationSubCategory> VehicleOperationSubCategories { get; set; } = new List<VehicleOperationSubCategory>();
}