// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TarifFunction
{
    public int Id { get; set; }

    public int FonctionId { get; set; }

    public double? NormalRatePerHour { get; set; }

    public double? OverTimeDayRatePerHour { get; set; }

    public double? OverTimeNightRatePerHour { get; set; }

    public double? WeekendRatePerHour { get; set; }

    public string CurrencyCode { get; set; }

    public DateTime? AddNewTime { get; set; }

    public DateTime? EditTime { get; set; }

    public string LastModifiedBy { get; set; }

    public string CreatedBy { get; set; }

    public bool? IsModel { get; set; }

    public int? ClientCode { get; set; }

    public string CalculationMethod { get; set; }

    public Guid TenantId { get; set; }

    public virtual DsTariffCalculationRounding CalculationMethodNavigation { get; set; }

    public virtual TnClient ClientCodeNavigation { get; set; }

    public virtual TnDevise CurrencyCodeNavigation { get; set; }

    public virtual Function Function { get; set; }
}