// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TblAddressPost
{
    public int Id { get; set; }

    public int ClientId { get; set; }

    public int TypeOperation { get; set; }

    public string Name { get; set; }

    public string CompanyName { get; set; }

    public string Street { get; set; }

    public string Region { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string ZipCode { get; set; }

    public string Country { get; set; }

    public string PhoneNumber1 { get; set; }

    public string PhoneNumber2 { get; set; }

    public string FaxNumber { get; set; }

    public string Details { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TblClient Client { get; set; }
}

