// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TbLangue
{
    public string Langue { get; set; }

    public string LibelleLangue { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }
}
