// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TblAgence
{
    public string CodeAgence { get; set; }

    public string NomAgence { get; set; }

    public string GroupeAgence { get; set; }

    public string DescriptionAgence { get; set; }

    public string DeviseReference { get; set; }

    public string DeviseEquivalence { get; set; }

    public bool SiegeGpe { get; set; }

    public bool SiegeGeneral { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual TblGroupesAgence GroupeAgenceNavigation { get; set; }

    public virtual ICollection<TblClient> TblClients { get; set; } = new List<TblClient>();
}