// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TblAddressScan
{
    public int Id { get; set; }

    public int ClientId { get; set; }

    public int ScanModeId { get; set; }

    public int TypeOperation { get; set; }

    public string ScanAddress { get; set; }

    public string Description { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TblClient Client { get; set; }

[NotMapped]
    public virtual TblScanMode ScanMode { get; set; }
}

