// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TblGroupesAgence
{
    public string CodeGpeAgence { get; set; }

    public string LibelleGpeAgence { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TblAgence> TblAgences { get; set; } = new List<TblAgence>();
}