// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TblReport
{
    public int Id { get; set; }

    public string ReportName { get; set; }

    public string ReportCode { get; set; }

    public string TemporarySerieCode { get; set; }

    public string FinalSerieCode { get; set; }

    public Guid TenantId { get; set; }
}