// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TbSeries
{
    public string CodeSerie { get; set; }

    public string LibelleSerie { get; set; }

    public string PtyPrefix { get; set; }

    public int PtyRadical { get; set; }

    public string PtySuffix { get; set; }

    public string PtyType { get; set; }

    public string PtyDataBase { get; set; }

    public DateTime ReportDat { get; set; }

    public Guid TenantId { get; set; }
}
