// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TbSeriesParameter
{
    public int Id { get; set; }

    public string Parameter { get; set; }

    public string Description { get; set; }

    public string Value { get; set; }

    public bool IsVisible { get; set; }

    public bool IsUpdatable { get; set; }

    public Guid TenantId { get; set; }
}