// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TbSerieCounter
{
    public int Id { get; set; }

    public string CodeAgence { get; set; }

    public int SerieStructId { get; set; }

    public int Counter { get; set; }

    public int? YearNumber { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TbSeriesStruct SerieStruct { get; set; }
}

