// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TbSeriesBooking
{
    public int Id { get; set; }

    public int SerieStructId { get; set; }

    public string CodeAgence { get; set; }

    public string Counter { get; set; }

    public string Status { get; set; }

    public DateTime BookingDate { get; set; }

    public int? YearNumber { get; set; }

    public Guid TenantId { get; set; }

    public virtual TbSeriesStruct SerieStruct { get; set; }
}