// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TiRelation
{
    public int NãƒÆÃÂÅÃƒâŠÃÂ { get; set; }

    public string Name { get; set; }

    public string Table { get; set; }

    public string FieldName { get; set; }

    public string ForeignTable { get; set; }

    public string ForeignFieldName { get; set; }

    public int Attributes { get; set; }

    public DateTime ReportDat { get; set; }

    public Guid TenantId { get; set; }

    public int NãƒâŠÃÂ { get; set; }

    public int NãÂ { get; set; }
}
