// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TisComptaAccountingDetail
{
    public int Id { get; set; }

    public string Piece { get; set; }

    public string Statut { get; set; }

    public string Raison { get; set; }

    public int HeaderId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TisComptaAccounting Header { get; set; }
}

