// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnActionsProjet
{
    public string CodeActionProjet { get; set; }

    public string Projet { get; set; }

    public DateTime DateAction { get; set; }

    public string AgenceEmission { get; set; }

    public string AgencesDestination { get; set; }

    public int TypeAction { get; set; }

    public string LibelleAction { get; set; }

    public DateTime DateEcheance { get; set; }

    public string ResponsableAction { get; set; }

    public string ObservationAction { get; set; }

    public string StatutAction { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnAgence AgenceEmissionNavigation { get; set; }

[NotMapped]
    public virtual TnProjet ProjetNavigation { get; set; }

    public virtual ICollection<TnRapportsProjet> TnRapportsProjets { get; set; } = new List<TnRapportsProjet>();
}

