// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnActivite
{
    public string CodeActivite { get; set; }

    public string LibelleActivite { get; set; }

    public string ModuleOperation { get; set; }

    public string ConcernFacturation { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public int? IndustryId { get; set; }

[NotMapped]
    public virtual TnModulesOperation ModuleOperationNavigation { get; set; }

    public virtual ICollection<TnEstimationsDossier> TnEstimationsDossiers { get; set; } = new List<TnEstimationsDossier>();

    public virtual ICollection<TnModelesCotation> TnModelesCotations { get; set; } = new List<TnModelesCotation>();

    public virtual ICollection<TnTypesDossier> TnTypesDossiers { get; set; } = new List<TnTypesDossier>();
}

