// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnBankTransfer
{
    public int CodeBankTransfer { get; set; }

    public DateTime CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public int NbrFactures { get; set; }

    public string Devise { get; set; }

    public double MontantTotal { get; set; }

    public string CompteTlc { get; set; }

    public DateTime? DateExecution { get; set; }

    public string Libelle { get; set; }

    public string EditedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string Type { get; set; }

    public string Statut { get; set; }

    public string Agence { get; set; }

    public string MessageIdentification { get; set; }

    public int? WaitingValidationFrom { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnBankTransferDetail> TnBankTransferDetails { get; set; } = new List<TnBankTransferDetail>();

[NotMapped]
    public virtual WorkflowGroup WaitingValidationFromNavigation { get; set; }
}

