// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnBankTransferComment
{
    public int CommentId { get; set; }

    public int BankTransferId { get; set; }

    public string Action { get; set; }

    public DateTime? ActionDate { get; set; }

    public string Responsable { get; set; }

    public Guid TenantId { get; set; }
}
