// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCategoriesReference
{
    public string CodeCategorieReference { get; set; }

    public string DescriptionCategorie { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string SessionOptions { get; set; }

    public bool? DisableMultiOptions { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnArticle> TnArticles { get; set; } = new List<TnArticle>();

    public virtual ICollection<TnCategoryReferencesOption> TnCategoryReferencesOptions { get; set; } = new List<TnCategoryReferencesOption>();

    public virtual ICollection<TnReference> TnReferences { get; set; } = new List<TnReference>();
}
