// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCashCountingDetail
{
    public int Id { get; set; }

    public int CashCountingHeaderId { get; set; }

    public int NotesAndCoinsId { get; set; }

    public int Qty { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnCashCountingHeader CashCountingHeader { get; set; }

    public virtual TnCurrencyNotesAndCoin NotesAndCoins { get; set; }
}