// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCategoryReferencesOption
{
    public int Id { get; set; }

    public string CaregoryCode { get; set; }

    public int OptionCode { get; set; }

    public string OptionLabel { get; set; }

    public bool? IsDefault { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnCategoriesReference CaregoryCodeNavigation { get; set; }
}

