// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCentresCout
{
    public string CodeCentreCout { get; set; }

    public string LibelleCentreCout { get; set; }

    public string GroupeCentreCout { get; set; }

    public string Agence { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<AEcritureCoutAmortissementStatutaire> AEcritureCoutAmortissementStatutaires { get; set; } = new List<AEcritureCoutAmortissementStatutaire>();

    public virtual ICollection<Ecriture> Ecritures { get; set; } = new List<Ecriture>();

    public virtual ICollection<MailAutomationInstanceConfiguration> MailAutomationInstanceConfigurations { get; set; } = new List<MailAutomationInstanceConfiguration>();

    public virtual ICollection<TnArticle> TnArticles { get; set; } = new List<TnArticle>();

    public virtual ICollection<TnDetailsCompte> TnDetailsComptes { get; set; } = new List<TnDetailsCompte>();

    public virtual ICollection<TnDetailsPiece> TnDetailsPieces { get; set; } = new List<TnDetailsPiece>();

    public virtual ICollection<TnDetailsStock> TnDetailsStocks { get; set; } = new List<TnDetailsStock>();
}
