// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCheckPaymentDocument
{
    public int IdDocument { get; set; }

    public string RefDetailDocument { get; set; }

    public string Libelle { get; set; }

    public double? Montant { get; set; }

    public string RefPiece { get; set; }

    public string Devise { get; set; }

    public Guid TenantId { get; set; }
}
