// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnChargeur
{
    public string CodeChargeur { get; set; }

    public string NomChargeur { get; set; }

    public string AdresseChargeur { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnConnaissement> TnConnaissements { get; set; } = new List<TnConnaissement>();
}
