// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnClientsLable
{
    public int Id { get; set; }

    public string ClientCode { get; set; }

    public string ClientLabel { get; set; }

    public Guid TenantId { get; set; }
}
