// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCodesRegime
{
    public string CodeRegime { get; set; }

    public string DescriptionRegime { get; set; }

    public string TypesDossiers { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string Operation { get; set; }

    public bool? IsAdouanaRegime { get; set; }

    public string TypesDocuments { get; set; }

    public string Etape { get; set; }

    public string Sens { get; set; }

    public bool? IsActive { get; set; }

    public string Label { get; set; }

    public string Acronym { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnCodesEtape> TnCodesEtapes { get; set; } = new List<TnCodesEtape>();

    public virtual ICollection<TnFileTypeRegime> TnFileTypeRegimes { get; set; } = new List<TnFileTypeRegime>();

    public virtual TnRubriquesOperation TnRubriquesOperation { get; set; }
}