// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCodesMvtsStock
{
    public string CodeMvtStock { get; set; }

    public string LibelleMvtStock { get; set; }

    public int SensMvt { get; set; }

    public bool PuAutomatique { get; set; }

    public int OrdreMvt { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnDetailsStock> TnDetailsStocks { get; set; } = new List<TnDetailsStock>();
}
