// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCodesTaxis
{
    public string CodeTaxe { get; set; }

    public string DescriptionTaxe { get; set; }

    public double PourcentageTaxe { get; set; }

    public string CompteTaxeAchat { get; set; }

    public string CompteTaxeVente { get; set; }

    public string Agence { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public bool? IgnoreAccounting { get; set; }

    public string TextPrefixOnNewLine { get; set; }

    public bool? SplitOnNewLine { get; set; }

    public string Rubrique { get; set; }

    public bool ApplyOnTaxes { get; set; }

    public int? Priorite { get; set; }

    public bool? ToGroup { get; set; }

    public bool? AvailableOnFile { get; set; }

    public string CodeTisCompta { get; set; }

    public bool? ToShowOnDetails { get; set; }

    public string Abbreviation { get; set; }

    public string TypeTax { get; set; }

    public string TvaTaxTopology { get; set; }

    public string WhTaxTopology { get; set; }

    public bool? ToBeDeclareOtherThanTax { get; set; }

    public bool? IsDefault { get; set; }

    public bool? IsActive { get; set; }

    public Guid TenantId { get; set; }

    public int? CountryId { get; set; }

[NotMapped]
    public virtual TnAgence AgenceNavigation { get; set; }

    [NotMapped]
    public virtual PcCompteComptable PcCompteComptable { get; set; }

    [NotMapped]
    public virtual PcCompteComptable PcCompteComptableNavigation { get; set; }
}


