// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCompagniesAerienne
{
    public string CodeCompagnieAerienne { get; set; }

    public string NomCompagnieAerienne { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string TransportType { get; set; }

    public bool Available { get; set; }

    public string CodeIso { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnVol> TnVols { get; set; } = new List<TnVol>();
}