// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCostType
{
    public int Id { get; set; }

    public string Label { get; set; }

    public string Code { get; set; }

    public int? SplitType { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnSplitType SplitTypeNavigation { get; set; }

    public virtual ICollection<TnDetailsTarifsClient> TnDetailsTarifsClients { get; set; } = new List<TnDetailsTarifsClient>();

    public virtual ICollection<TnFournisseur> TnFournisseurs { get; set; } = new List<TnFournisseur>();
}

