// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnConvertionsDevise
{
    public int RefDetailConversion { get; set; }

    public string CodeConvertionDevise { get; set; }

    public string Devise { get; set; }

    public double ValeurDevise { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnCodesConvertion CodeConvertionDeviseNavigation { get; set; }

    public virtual TnDevise DeviseNavigation { get; set; }
}