// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnColor
{
    public int Id { get; set; }

    public string Label { get; set; }

    public string Color { get; set; }

    public string BackgroundColor { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<DashboardLabel> DashboardLabels { get; set; } = new List<DashboardLabel>();
}