// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCodesConvertion
{
    public string CodeConvertion { get; set; }

    public string LibelleCodeConvertion { get; set; }

    public DateTime DateConvertion { get; set; }

    public string Agence { get; set; }

    public bool NonComptabilisable { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnConvertionsDevise> TnConvertionsDevises { get; set; } = new List<TnConvertionsDevise>();

    public virtual ICollection<TnFournisseur> TnFournisseurs { get; set; } = new List<TnFournisseur>();

    public virtual ICollection<TnPiece> TnPieces { get; set; } = new List<TnPiece>();
}
