// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnConnaissement
{
    public string CodeConnaissement { get; set; }

    public string NumConnaissement { get; set; }

    public string Manifeste { get; set; }

    public string Provenance { get; set; }

    public string Destination { get; set; }

    public string Chargeur { get; set; }

    public string Shipper { get; set; }

    public string Receptionnaire { get; set; }

    public string Consignee { get; set; }

    public string Notify { get; set; }

    public string Remarque { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string MasterAwb { get; set; }

    public string LastDestination { get; set; }

    public string ConsignePc { get; set; }

    public string TypesDocuments { get; set; }

    public string ProvenanceCode { get; set; }

    public string DestinationCode { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnChargeur ChargeurNavigation { get; set; }

[NotMapped]
    public virtual TnLieux DestinationNavigation { get; set; }

[NotMapped]
    public virtual TnManifeste ManifesteNavigation { get; set; }

[NotMapped]
    public virtual TnLieux ProvenanceNavigation { get; set; }

[NotMapped]
    public virtual TnReceptionnaire ReceptionnaireNavigation { get; set; }

    public virtual ICollection<TnColisagesDossier> TnColisagesDossiers { get; set; } = new List<TnColisagesDossier>();

    public virtual ICollection<TnDetailsConnaissement> TnDetailsConnaissements { get; set; } = new List<TnDetailsConnaissement>();
}

