// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCodesEtape
{
    public string CodeEtape { get; set; }

    public string LibelleEtape { get; set; }

    public string CategorieEtape { get; set; }

    public int? OrdreEtape { get; set; }

    public bool GestionDuree { get; set; }

    public int? DelaiEtape { get; set; }

    public string Agence { get; set; }

    public bool? EtapeDossier { get; set; }

    public string Regime { get; set; }

    public string PlanAchatEtape { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public int? AttachedDocumentType { get; set; }

    public string TypesDocuments { get; set; }

    public bool? IsActive { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnAgence AgenceNavigation { get; set; }

[NotMapped]
    public virtual TnCodesRegime TnCodesRegime { get; set; }

[NotMapped]
    public virtual TnPlansOperation TnPlansOperation { get; set; }
}

