// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCompteDestinationMapping
{
    public int CodeMapping { get; set; }

    public string CompteSource { get; set; }

    public string BaseDestination { get; set; }

    public string CompteDestination { get; set; }

    public bool? ShowOnFiles { get; set; }

    public Guid TenantId { get; set; }
}