// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnComptesBancaire
{
    public int CodeCompte { get; set; }

    public string NomCompte { get; set; }

    public string Lieu { get; set; }

    public string Devise { get; set; }

    public string Iban { get; set; }

    public string CodeClearing { get; set; }

    public string Bic { get; set; }

    public string TypeCompte { get; set; }

    public bool? IsActif { get; set; }

    public string OwnerCode { get; set; }

    public string OwnerName { get; set; }

    public string AddressLine { get; set; }

    public string Country { get; set; }

    public string TownName { get; set; }

    public string PostalCode { get; set; }

    public string StreetNumber { get; set; }

    public string BuildingNumber { get; set; }

    public string ChargeBearer { get; set; }

    public string TypecompteId { get; set; }

    public string ComptePostal { get; set; }

    public int? StatusId { get; set; }

    public DateOnly? CloseDate { get; set; }

    public string ClosedBy { get; set; }

    public string CreateBy { get; set; }

    public string EditedBy { get; set; }

    public DateTime? CreateOn { get; set; }

    public DateTime? EditOn { get; set; }

    public DateTime? GrantedOn { get; set; }

    public string GrantedBy { get; set; }

    public string RevokedBy { get; set; }

    public DateTime? RevokedOn { get; set; }

    public string ProviderCode { get; set; }

    public string AccountStatus { get; set; }

    public string ExternalReference { get; set; }

    public string AccountType { get; set; }

    public string AccountValue { get; set; }

    public string AccountBalanceLink { get; set; }

    public string AccountLink { get; set; }

    public string AccountTransactionsLink { get; set; }

    public string TreasuryCode { get; set; }

    public string AccountCategory { get; set; }

    public decimal? BalanceAmount { get; set; }

    public DateTime? BalanceUpdateDate { get; set; }

    public Guid TenantId { get; set; }
}