// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnCurrencyNotesAndCoin
{
    public int Id { get; set; }

    public string CurrencyCode { get; set; }

    public double CurrencyValue { get; set; }

    public string Type { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnDevise CurrencyCodeNavigation { get; set; }

    public virtual ICollection<TnCashCountingDetail> TnCashCountingDetails { get; set; } = new List<TnCashCountingDetail>();
}

