// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDailyRate
{
    public int Id { get; set; }

    public DateOnly DayDate { get; set; }

    public double Rate { get; set; }

    public string FromCurrency { get; set; }

    public string ToCurrency { get; set; }

    public Guid TenantId { get; set; }
}