// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDetailsOperation
{
    public string CodeDetailOperation { get; set; }

    public string SousDossier { get; set; }

    public string Operation { get; set; }

    public string RubriqueOperation { get; set; }

    public string CodeDetailReference { get; set; }

    public string LibelleDetailReference { get; set; }

    public int BaseOperation { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string RequestOfAdvance { get; set; }

    public string InvoiceNumber { get; set; }

    public bool? InvoiceReceived { get; set; }

    public string TemporaryInvoiceNumber { get; set; }

    public string SupplierOrderNumber { get; set; }

    public bool? NoShow { get; set; }

    public string Observation { get; set; }

    public int? PassagerVolId { get; set; }

    public string StatutOperation { get; set; }

    public DateTime? ApurementDate { get; set; }

    public DateTime? ValidFrom { get; set; }

    public DateTime? ValidTo { get; set; }

    public DateTime? DateTransmission { get; set; }

    public string ObervationsValidite { get; set; }

    public int? StatusId { get; set; }

    public DateTime? DateRealisation { get; set; }

    public DateOnly? CloseDate { get; set; }

    public string ClosedBy { get; set; }

    public DateTime? SynchroDate { get; set; }

    public int? FrontSourceId { get; set; }

    public DateTime? CancelDate { get; set; }

    public string CancelReason { get; set; }

    public bool? ToBeInvoiced { get; set; }

    public string SignatureBase64 { get; set; }

    public bool? IsPresent { get; set; }

    public string SignedBy { get; set; }

    public string MobileFrontSourceId { get; set; }

    public string Remark { get; set; }

    public string LastModifiedBy { get; set; }

    public bool? Requested { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnOperation OperationNavigation { get; set; }

    public virtual ICollection<TnEtapesOperationsDetail> TnEtapesOperationsDetails { get; set; } = new List<TnEtapesOperationsDetail>();

[NotMapped]
    public virtual TnSousDossier TnSousDossier { get; set; }
}

