// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDeclarationImportationDossier
{
    public int IdDeclaration { get; set; }

    public string NomSocieteImportateur { get; set; }

    public string AdresseSocieteImportateur { get; set; }

    public string Bpimportateur { get; set; }

    public string FaxImportateur { get; set; }

    public string TelImportateur { get; set; }

    public string EmailImportateur { get; set; }

    public string PaysImportateur { get; set; }

    public string NatureActiviteDeclareImportateur { get; set; }

    public string NumeroCodeActiviteImportateur { get; set; }

    public string NumeroIdentifiantUniqueImportateur { get; set; }

    public string NomSocieteFournisseur { get; set; }

    public string AdresseSocieteFournisseur { get; set; }

    public string Bpfournisseur { get; set; }

    public string FaxFournisseur { get; set; }

    public string TelFournisseur { get; set; }

    public string EmailFournisseur { get; set; }

    public string PaysFournisseur { get; set; }

    public string TransitaireAgreFournisseur { get; set; }

    public string DomicilationBanqueAgreFournisseur { get; set; }

    public string NatureProduitImporte { get; set; }

    public string NumeroFacture { get; set; }

    public string PaysOrigine { get; set; }

    public string PaysProvenance { get; set; }

    public string NumDossier { get; set; }

    public Guid TenantId { get; set; }
}
