// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDetailsPosition
{
    public int RefDetailPosition { get; set; }

    public string DetailConnaissement { get; set; }

    public string PositionTarifaire { get; set; }

    public double? ValeurImposable { get; set; }

    public string MarquesEtNumeros { get; set; }

    public string DescriptionMarchandises { get; set; }

    public int Qte { get; set; }

    public string UnitePoids { get; set; }

    public float PoidsNet { get; set; }

    public float PoidsBrut { get; set; }

    public string UniteVolume { get; set; }

    public float Volume { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnDetailsConnaissement DetailConnaissementNavigation { get; set; }

[NotMapped]
    public virtual TnPositionsTarifaire PositionTarifaireNavigation { get; set; }
}

