// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDevise
{
    public string CodeDevise { get; set; }

    public int CodeNumeriqueDevise { get; set; }

    public string LibelleDevise { get; set; }

    public int Decimales { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string DeviseIcon { get; set; }

    public bool? IsHomeDevise { get; set; }

    public double? CashCountingDiffLimit { get; set; }

    public virtual ICollection<DsDetailsService> DsDetailsServices { get; set; } = new List<DsDetailsService>();

    public virtual ICollection<DsTarifFonction> DsTarifFonctions { get; set; } = new List<DsTarifFonction>();

    public virtual ICollection<ExternalRateChangeDetail> ExternalRateChangeDetailCurrencyFromNavigations { get; set; } = new List<ExternalRateChangeDetail>();

    public virtual ICollection<ExternalRateChangeDetail> ExternalRateChangeDetailCurrencyToNavigations { get; set; } = new List<ExternalRateChangeDetail>();

    public virtual ICollection<GcGestionConteneur> GcGestionConteneurs { get; set; } = new List<GcGestionConteneur>();

    public virtual ICollection<MailAutomationInstanceConfiguration> MailAutomationInstanceConfigurations { get; set; } = new List<MailAutomationInstanceConfiguration>();

    public virtual ICollection<ServiceEstimation> ServiceEstimations { get; set; } = new List<ServiceEstimation>();

    public virtual ICollection<TarifFunction> TarifFunctions { get; set; } = new List<TarifFunction>();

    public virtual ICollection<TnAgence> TnAgenceDeviseEquivalenceNavigations { get; set; } = new List<TnAgence>();

    public virtual ICollection<TnAgence> TnAgenceDeviseReferenceNavigations { get; set; } = new List<TnAgence>();

    public virtual ICollection<TnClient> TnClients { get; set; } = new List<TnClient>();

    public virtual ICollection<TnComptesComptable> TnComptesComptables { get; set; } = new List<TnComptesComptable>();

    public virtual ICollection<TnConvertionsDevise> TnConvertionsDevises { get; set; } = new List<TnConvertionsDevise>();

    public virtual ICollection<TnCurrencyNotesAndCoin> TnCurrencyNotesAndCoins { get; set; } = new List<TnCurrencyNotesAndCoin>();

    public virtual ICollection<TnDetailsTarifsClient> TnDetailsTarifsClients { get; set; } = new List<TnDetailsTarifsClient>();

    public virtual ICollection<TnDevi> TnDevis { get; set; } = new List<TnDevi>();

    public virtual ICollection<TnDevisDetail> TnDevisDetails { get; set; } = new List<TnDevisDetail>();

    public virtual ICollection<TnDevisDevise> TnDevisDevises { get; set; } = new List<TnDevisDevise>();

    public virtual ICollection<TnEstimationsDossier> TnEstimationsDossiers { get; set; } = new List<TnEstimationsDossier>();

    public virtual ICollection<TnFournisseur> TnFournisseurs { get; set; } = new List<TnFournisseur>();

    public virtual ICollection<TnOffresClient> TnOffresClients { get; set; } = new List<TnOffresClient>();

    public virtual ICollection<TnPiece> TnPieceDeviseEquivalenceNavigations { get; set; } = new List<TnPiece>();

    public virtual ICollection<TnPiece> TnPieceDevisePieceNavigations { get; set; } = new List<TnPiece>();

    public virtual ICollection<TnPiece> TnPieceDeviseReferenceNavigations { get; set; } = new List<TnPiece>();

    public virtual ICollection<TnRubriquesAchat> TnRubriquesAchats { get; set; } = new List<TnRubriquesAchat>();

    public virtual ICollection<TnTresorery> TnTresoreries { get; set; } = new List<TnTresorery>();
}