// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDevisPackaging
{
    public int Id { get; set; }

    public string CodeDevis { get; set; }

    public double WidthOriginal { get; set; }

    public double LengthOriginal { get; set; }

    public double HeightOriginal { get; set; }

    public double WidthM { get; set; }

    public double LengthM { get; set; }

    public double HeightM { get; set; }

    public string Unit { get; set; }

    public string Label { get; set; }

    public string PackagingType { get; set; }

    public double CalculatedVolume { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnDevi CodeDevisNavigation { get; set; }
}

