// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDetailsCompte
{
    public string CodeDetailCompte { get; set; }

    public string Piece { get; set; }

    public string CompteCompta { get; set; }

    public string CodeConcern { get; set; }

    public string NomConcern { get; set; }

    public string LibelleArticle { get; set; }

    public string SousDossier { get; set; }

    public double MontantHt { get; set; }

    public string CodeTva { get; set; }

    public double MontantTva { get; set; }

    public bool ContrePartie { get; set; }

    public string Reference { get; set; }

    public string CentreCout { get; set; }

    public string CleControle { get; set; }

    public int Index { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnCentresCout CentreCoutNavigation { get; set; }

    [NotMapped]
    public virtual PcCompteComptable PcCompteComptable { get; set; }

[NotMapped]
    public virtual TnPiece TnPiece { get; set; }
}


