// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDetailsAction
{
    public int DetailPieceSource { get; set; }

    public int DetailPieceDestination { get; set; }

    public int TypeAction { get; set; }

    public string StatusAction { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string LastEditedBy { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnDetailsPiece DetailPieceDestinationNavigation { get; set; }

[NotMapped]
    public virtual TnDetailsPiece DetailPieceSourceNavigation { get; set; }
}



