// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDevisComment
{
    public int Id { get; set; }

    public string DevisId { get; set; }

    public string CommentText { get; set; }

    public DateTime CommentDate { get; set; }

    public string CommentedBy { get; set; }

    public Guid TenantId { get; set; }
}
