// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDetailGrouping
{
    public int Id { get; set; }

    public string Label { get; set; }

    public int Ordre { get; set; }

    public string TableName { get; set; }

    public string TableCode { get; set; }

    public string GroupCotation { get; set; }

    public bool? SautDePage { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnTaxeGroupe> TnTaxeGroupes { get; set; } = new List<TnTaxeGroupe>();
}