// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDevisExcelComplement
{
    public int Id { get; set; }

    public string Libelle { get; set; }

    public string Type { get; set; }

    public string CodeDevis { get; set; }

    public string Valeur { get; set; }

    public Guid TenantId { get; set; }
}