// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDevisExcelDetail
{
    public int CodeDetailDevis { get; set; }

    public string CodeDevis { get; set; }

    public string RubriqueCotation { get; set; }

    public double? Montant { get; set; }

    public double? Taxe { get; set; }

    public double? TotalLigne { get; set; }

    public string GroupLine { get; set; }

    public string GroupColumn { get; set; }

    public double? LineNumber { get; set; }

    public string GroupeCotation { get; set; }

    public string QuantiteEnLettres { get; set; }

    public Guid TenantId { get; set; }
}
