// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDetailsPiece
{
    public int CodeDetailPiece { get; set; }

    public string Piece { get; set; }

    public string SousDossier { get; set; }

    public int? ArticlePiece { get; set; }

    public string CompteArticle { get; set; }

    public string ReferencePiece { get; set; }

    public string LibelleArticlePiece { get; set; }

    public double MontantHtPiece { get; set; }

    public string CodeTva { get; set; }

    public double MontantTva { get; set; }

    public string CentreCout { get; set; }

    public string RubriqueCotation { get; set; }

    public float CommissionDebours { get; set; }

    public int OrdreDetail { get; set; }

    public double CoefV1 { get; set; }

    public double CoefV2 { get; set; }

    public bool Reclasse { get; set; }

    public bool IgnorerComptabilisation { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public double? MontantValeur { get; set; }

    public string DeviseValeur { get; set; }

    public string Comment { get; set; }

    public string RelatedTo { get; set; }

    public int? Tvatype { get; set; }

    public string TvadetailType { get; set; }

    public string CompteReclassement { get; set; }

    public bool? IsAutomaticlyGenerated { get; set; }

    public int? SousDossierIndex { get; set; }

    public string TaxeCodes { get; set; }

    public string TaxeRates { get; set; }

    public double? Quantity { get; set; }

    public double? UnitPrice { get; set; }

    public double? DiscountPercentage { get; set; }

    public double? DiscountValue { get; set; }

    public double? TaxeAmount { get; set; }

    public string InvoicingObservation { get; set; }

    public string InvoicingStatus { get; set; }

    public int? CostType { get; set; }

    public string Regroupement { get; set; }

    public string DiscountType { get; set; }

    public string ArticleDescription { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnArticle ArticlePieceNavigation { get; set; }

[NotMapped]
    public virtual TnCentresCout CentreCoutNavigation { get; set; }

[NotMapped]
    public virtual TnRubriquesCotation RubriqueCotationNavigation { get; set; }

    [NotMapped]
    public virtual ICollection<TnDetailsAction> TnDetailsActionDetailPieceDestinationNavigations { get; set; } = new List<TnDetailsAction>();

[NotMapped]
    public virtual TnDetailsAction TnDetailsActionDetailPieceSourceNavigation { get; set; }

    public virtual ICollection<TnDetailsPieceTaxe> TnDetailsPieceTaxes { get; set; } = new List<TnDetailsPieceTaxe>();

    public virtual ICollection<TnDetailsVente> TnDetailsVentes { get; set; } = new List<TnDetailsVente>();

[NotMapped]
    public virtual TnPiece TnPiece { get; set; }

[NotMapped]
    public virtual TnSousDossier TnSousDossier { get; set; }
}


