// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDetailsStock
{
    public string DetailOperationStock { get; set; }

    public string DetailPieceStock { get; set; }

    public string ProduitStock { get; set; }

    public string MvtStock { get; set; }

    public int Qte { get; set; }

    public double PrixUnitaire { get; set; }

    public int? ArticlePiece { get; set; }

    public string CentreCout { get; set; }

    public string Magasin { get; set; }

    public string Inventaire { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string LibelleDetailReference { get; set; }

    public string SousDossier { get; set; }

    public DateOnly? DateDemandeOperation { get; set; }

    public DateOnly? DateRealisation { get; set; }

    public string StatutOperation { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnArticle ArticlePieceNavigation { get; set; }

[NotMapped]
    public virtual TnCentresCout CentreCoutNavigation { get; set; }

[NotMapped]
    public virtual TnInventaire InventaireNavigation { get; set; }

[NotMapped]
    public virtual TnCodesMvtsStock MvtStockNavigation { get; set; }

[NotMapped]
    public virtual TnProduitsStock ProduitStockNavigation { get; set; }
}

