// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDevisDevise
{
    public int Id { get; set; }

    public string CodeDevis { get; set; }

    public string CurrencyCode { get; set; }

    public double Coef { get; set; }

    public DateTime EditTime { get; set; }

    public DateTime AddNewTime { get; set; }

    public string CreateBy { get; set; }

    public string ModifyBy { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnDevi CodeDevisNavigation { get; set; }

    public virtual TnDevise CurrencyCodeNavigation { get; set; }
}