// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDetailsConnaissement
{
    public string CodeDetailConnaissement { get; set; }

    public string Connaissement { get; set; }

    public string Produit { get; set; }

    public string TypeColisage { get; set; }

    public string Contenant { get; set; }

    public string MarquesEtNumeros { get; set; }

    public string DescriptionMarchandises { get; set; }

    public int Qte { get; set; }

    public string UnitePoids { get; set; }

    public float PoidsNet { get; set; }

    public float PoidsNet2 { get; set; }

    public float PoidsNet3 { get; set; }

    public float PoidsBrut { get; set; }

    public float PoidsBrut2 { get; set; }

    public float PoidsBrut3 { get; set; }

    public string UniteVolume { get; set; }

    public float Volume { get; set; }

    public string QtesRestantes { get; set; }

    public bool ArretDecompte { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string ManufacturingCountry { get; set; }

    public float? MarchandiseValeur { get; set; }

    public string MarchandiseDevise { get; set; }

    public string Htscode { get; set; }

    public string SousTypeColis { get; set; }

    public string Division { get; set; }

    public double? Amount { get; set; }

    public string AmountCurency { get; set; }

    public string Reference { get; set; }

    public int? CountryCode { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnConnaissement ConnaissementNavigation { get; set; }

    public virtual TnContenant ContenantNavigation { get; set; }

    public virtual CountryCode CountryCodeNavigation { get; set; }

    public virtual ICollection<GcGestionConteneur> GcGestionConteneurs { get; set; } = new List<GcGestionConteneur>();

    public virtual TnPay ManufacturingCountryNavigation { get; set; }

    public virtual TnProduitsColisage ProduitNavigation { get; set; }

    public virtual ICollection<TnApurementsEntrepot> TnApurementsEntrepots { get; set; } = new List<TnApurementsEntrepot>();

    public virtual ICollection<TnDetailsPosition> TnDetailsPositions { get; set; } = new List<TnDetailsPosition>();

    public virtual TnTypesColisage TypeColisageNavigation { get; set; }
}