// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDevi
{
    public string CodeDevis { get; set; }

    public string LibelleDevis { get; set; }

    public string StatusDevis { get; set; }

    public string Agence { get; set; }

    public int ClientCode { get; set; }

    public string Responsable { get; set; }

    public string ModeleDeCotation { get; set; }

    public string Module { get; set; }

    public string CustomerReference { get; set; }

    public string TlcReference { get; set; }

    public string Incoterm { get; set; }

    public DateTime DevisDate { get; set; }

    public double WeightKg { get; set; }

    public double VolumeCbm { get; set; }

    public int Nb40Feet { get; set; }

    public int Nb20Feet { get; set; }

    public int NbGeneralCargo { get; set; }

    public string Origin { get; set; }

    public double Exw { get; set; }

    public double Fob { get; set; }

    public double Cif { get; set; }

    public string Devise { get; set; }

    public double DevisTotal { get; set; }

    public string Remarks { get; set; }

    public string Creator { get; set; }

    public DateTime? ValidatedOn { get; set; }

    public DateTime? ValidFrom { get; set; }

    public DateTime? ValidUntil { get; set; }

    public string ValidatedBy { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastEditTime { get; set; }

    public DateTime CreateDate { get; set; }

    public string TypeDevis { get; set; }

    public DateTime? TransmissionDate { get; set; }

    public bool IsAirTransport { get; set; }

    public DateTime? OfferValidity { get; set; }

    public string LinkedTarif { get; set; }

    public double ChargeableWeightKg { get; set; }

    public string HeaderText { get; set; }

    public string Substatus { get; set; }

    public string RejectionReason { get; set; }

    public string RejectionDescription { get; set; }

    public bool IsFinalVersion { get; set; }

    public int RevIndex { get; set; }

    public string FromPlace { get; set; }

    public string ToPlace { get; set; }

    public string DeviseEquivalence { get; set; }

    public double? CurrencyRate { get; set; }

    public string ClientName { get; set; }

    public DateTime? ApprovalDate { get; set; }

    public int? HusbandryNbOnSigners { get; set; }

    public int? HusbandryNbOffSigners { get; set; }

    public string Division { get; set; }

    public double? ShippingLoa { get; set; }

    public double? ShippingBreadth { get; set; }

    public double? ShippingGrt { get; set; }

    public double? ShippingMaxSummerDraft { get; set; }

    public double? ShippingVolume { get; set; }

    public double? ShippingDeadWeight { get; set; }

    public string ShippingVesselType { get; set; }

    public string ShippingFlag { get; set; }

    public DateTime? ShippingEta { get; set; }

    public DateTime? ShippingEtd { get; set; }

    public int? ShippingCrewCount { get; set; }

    public double? ShippingCargoM3 { get; set; }

    public double? ShippingCargoMt { get; set; }

    public string ShippingTerminal { get; set; }

    public int? ShippingAnchorage { get; set; }

    public int? ShippingAtPort { get; set; }

    public double? ShippingNrt { get; set; }

    public string NumFactureCommerciale { get; set; }

    public double? MontantFactureCommerciale { get; set; }

    public string DeviseFactureCommerciale { get; set; }

    public string WeightCalculationMethod { get; set; }

    public bool? OutlaysSp { get; set; }

    public bool? ServicesSp { get; set; }

    public bool? RemarksSp { get; set; }

    public bool? TaxesSp { get; set; }

    public bool? LumpsumSp { get; set; }

    public bool? AdvancesSp { get; set; }

    public string InvoiceConcern { get; set; }

    public bool? ShowCurrencyEq { get; set; }

    public bool? IsExcelFormat { get; set; }

    public string ExcelFlux { get; set; }

    public string HeaderExcel { get; set; }

    public DateTime? ShippingAta { get; set; }

    public DateTime? ShippingAtd { get; set; }

    public double? ShippingOffshore { get; set; }

    public DateTime? DateReceptionPayment { get; set; }

    public string Ref2 { get; set; }

    public string WaitingValidationFrom { get; set; }

    public DateTime? ClientRequestTime { get; set; }

    public DateTime? SentToClientTime { get; set; }

    public int? Poid { get; set; }

    public double? RealAmount { get; set; }

    public bool? PrefundingRequired { get; set; }

    public double? PrefundingPercentage { get; set; }

    public string RelatedCountry { get; set; }

    public string VesselType { get; set; }

    public double? SummerDraft { get; set; }

    public DateTime? RequestDate { get; set; }

    public string ConcernedCountry { get; set; }

    public string PortAirportCode { get; set; }

    public string CifFobCurrency { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnAgence AgenceNavigation { get; set; }

[NotMapped]
    public virtual TnClient ClientCodeNavigation { get; set; }

[NotMapped]
    public virtual TnDevise DeviseNavigation { get; set; }

    public virtual ICollection<TnDevisCommentaire> TnDevisCommentaires { get; set; } = new List<TnDevisCommentaire>();

    public virtual ICollection<TnDevisDetail> TnDevisDetails { get; set; } = new List<TnDevisDetail>();

    public virtual ICollection<TnDevisDevise> TnDevisDevises { get; set; } = new List<TnDevisDevise>();

    public virtual ICollection<TnDevisPackaging> TnDevisPackagings { get; set; } = new List<TnDevisPackaging>();

    public virtual ICollection<TnTarifDegressif> TnTarifDegressifs { get; set; } = new List<TnTarifDegressif>();

[NotMapped]
    public virtual TnTypesVessel VesselTypeNavigation { get; set; }
}

