// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDetailsConnaissementsTemporarire
{
    public string CodeDetailConnaissement { get; set; }

    public string Connaissement { get; set; }

    public string Produit { get; set; }

    public string TypeColisage { get; set; }

    public string Contenant { get; set; }

    public string MarquesEtNumeros { get; set; }

    public string DescriptionMarchandises { get; set; }

    public string Qte { get; set; }

    public string UnitePoids { get; set; }

    public string PoidsNet { get; set; }

    public string PoidsNet2 { get; set; }

    public string PoidsNet3 { get; set; }

    public string PoidsBrut { get; set; }

    public string PoidsBrut2 { get; set; }

    public string PoidsBrut3 { get; set; }

    public string UniteVolume { get; set; }

    public string Volume { get; set; }

    public string QtesRestantes { get; set; }

    public bool? ArretDecompte { get; set; }

    public int? Session { get; set; }

    public DateTime? AddNewTime { get; set; }

    public DateTime? EditTime { get; set; }

    public string ManufacturingCountry { get; set; }

    public float? MarchandiseValeur { get; set; }

    public string MarchandiseDevise { get; set; }

    public string Htscode { get; set; }

    public string SousTypeColis { get; set; }

    public string Division { get; set; }

    public double? Amount { get; set; }

    public string AmountCurency { get; set; }

    public string Reference { get; set; }

    public string CountryCode { get; set; }

    public bool? SuccesResult { get; set; }

    public string Messages { get; set; }

    public Guid TenantId { get; set; }
}
