// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDetailsPieceTaxe
{
    public int Id { get; set; }

    public string CodeTaxe { get; set; }

    public int CodeDetailPiece { get; set; }

    public string NumPiece { get; set; }

    public DateTime AddNewTime { get; set; }

    public string CreatedBy { get; set; }

    public DateTime EditTime { get; set; }

    public string ModifiedBy { get; set; }

    public double? PourcentageTaxe { get; set; }

    public bool? CreatedFromGenericTaxesModel { get; set; }

    public int? CodeDetailPieceTaxe { get; set; }

    public double? ForcedValue { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnDetailsPiece CodeDetailPieceTaxeNavigation { get; set; }

[NotMapped]
    public virtual TnPiece TnPiece { get; set; }
}

