// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDelaisPayement
{
    public int CodeDelaiPayement { get; set; }

    public string LibelleDelaiPayement { get; set; }

    public int DelaiPayement { get; set; }

    public string UniteDelai { get; set; }

    public bool DelaiFm { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string LibelleFacture { get; set; }

    public string LibelleFacturePt { get; set; }

    public string LibelleFactureUs { get; set; }

    public string LibelleFactureEs { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnClient> TnClients { get; set; } = new List<TnClient>();

    public virtual ICollection<TnFournisseur> TnFournisseurs { get; set; } = new List<TnFournisseur>();
}