// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDivision
{
    public string CodeDivision { get; set; }

    public string LibelleDivision { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string ClientRef { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnDivisionsClient> TnDivisionsClients { get; set; } = new List<TnDivisionsClient>();

    public virtual ICollection<TnDossier> TnDossiers { get; set; } = new List<TnDossier>();

    public virtual ICollection<TnPersonne> TnPersonnes { get; set; } = new List<TnPersonne>();
}
