// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDossierCategory
{
    public string Code { get; set; }

    public string Libelle { get; set; }

    public string Description { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnDossierSubCategory> TnDossierSubCategories { get; set; } = new List<TnDossierSubCategory>();

    public virtual ICollection<TnDossierTypeSubCategory> TnDossierTypeSubCategories { get; set; } = new List<TnDossierTypeSubCategory>();
}
