// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDossierTypeSubCategory
{
    public string Code { get; set; }

    public string DossierCategory { get; set; }

    public string TypeDossier { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnDossierCategory DossierCategoryNavigation { get; set; }
}

