// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDossierMapping
{
    public int Id { get; set; }

    public string SourceFile { get; set; }

    public string DestinationFile { get; set; }

    public DateTime AddNewTime { get; set; }

    public Guid TenantId { get; set; }
}
