// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDossiersExtraComment
{
    public int Id { get; set; }

    public string Comment1 { get; set; }

    public string Comment2 { get; set; }

    public string NumDossier { get; set; }

    public DateTime? DateComment { get; set; }

    public Guid TenantId { get; set; }
}