// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDocumentsParam
{
    public int Id { get; set; }

    public string ParameterName { get; set; }

    public string CodeDocument { get; set; }

    public string ParamType { get; set; }

    public bool? IsNullable { get; set; }

    public bool? UserParam { get; set; }

    public string DefaultValue { get; set; }

    public string ParamRowSource { get; set; }

    public string ParamLabel { get; set; }

    public bool? IsIdentifier { get; set; }

    public string ListTextField { get; set; }

    public string ListValueField { get; set; }

    public int? OrderField { get; set; }

    public int? WidthField { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnDocument CodeDocumentNavigation { get; set; }
}