// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDossier
{
    public string NumDossier { get; set; }

    public string Agence { get; set; }

    public DateTime Periode { get; set; }

    public string TypeDossier { get; set; }

    public string Division { get; set; }

    public string Key { get; set; }

    public DateTime DateDossier { get; set; }

    public string DossierSiege { get; set; }

    public bool Entrepot { get; set; }

    public string GroupeEstimation { get; set; }

    public double MontantEstimation { get; set; }

    public double SoldeDossier { get; set; }

    public string AncienNumDossier { get; set; }

    public DateTime? DateControle { get; set; }

    public bool Locked { get; set; }

    public bool Facture { get; set; }

    public string FactureReference { get; set; }

    public string StatutDossier { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string LocalRefDossier { get; set; }

    public string ClientObservations { get; set; }

    public string DossierSubCategory { get; set; }

    public string DossierAgent { get; set; }

    public string RefAgent { get; set; }

    public double? MontantMarge { get; set; }

    public string DeviseMarge { get; set; }

    public double? MontantServices { get; set; }

    public string DeviseServices { get; set; }

    public double? MontantOutlays { get; set; }

    public string DeviseOutlays { get; set; }

    public bool? EstimationEditedManually { get; set; }

    public DateTime? EstimationEditTime { get; set; }

    public bool? Ffok { get; set; }

    public bool? UrgentInvoing { get; set; }

    public string InvoicingStatus { get; set; }

    public int? InvoicingStatusId { get; set; }

    public string ClosedBy { get; set; }

    public DateTime? CloseDate { get; set; }

    public int? SoffilePlan { get; set; }

    public string RelatedGroup { get; set; }

    public bool? Refreshed { get; set; }

    public string DuplicatedRefReason { get; set; }

    public string CodePlanOperation { get; set; }

    public DateTime? ArchivedDate { get; set; }

    public DateTime? ClosedDate { get; set; }

    public int? CounterValue { get; set; }

    public int? CounterYear { get; set; }

    public string CounterType { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnAgence AgenceNavigation { get; set; }

    public virtual TnDivision DivisionNavigation { get; set; }

    public virtual ICollection<DsDetailsService> DsDetailsServices { get; set; } = new List<DsDetailsService>();

    public virtual ICollection<FileTaskValue> FileTaskValues { get; set; } = new List<FileTaskValue>();

    public virtual ICollection<Pofile> Pofiles { get; set; } = new List<Pofile>();

    public virtual TnStatutsDossier StatutDossierNavigation { get; set; }

    public virtual ICollection<TnFileEstimationDetail> TnFileEstimationDetails { get; set; } = new List<TnFileEstimationDetail>();

    public virtual ICollection<TnPiecesVente> TnPiecesVentes { get; set; } = new List<TnPiecesVente>();

    public virtual ICollection<TnSousDossier> TnSousDossiers { get; set; } = new List<TnSousDossier>();
}