// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDocumentSpecialField
{
    public int Id { get; set; }

    public string DocumentCode { get; set; }

    public int SpecialParamId { get; set; }

    public string ParamName { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnDocument DocumentCodeNavigation { get; set; }

[NotMapped]
    public virtual TnSpecialReportField SpecialParam { get; set; }
}

