// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnDocument
{
    public string CodeDocument { get; set; }

    public string LibelleDocument { get; set; }

    public string TypeRequete { get; set; }

    public string NomDocument { get; set; }

    public int Copies { get; set; }

    public string GroupeDocument { get; set; }

    public string TypesDossiers { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string NomDocumentTis { get; set; }

    public string ReportDirectory { get; set; }

    public bool? IsMultiple { get; set; }

    public string DefaultExtension { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnCheckPrintingTemplate> TnCheckPrintingTemplates { get; set; } = new List<TnCheckPrintingTemplate>();

    public virtual ICollection<TnDocumentSpecialField> TnDocumentSpecialFields { get; set; } = new List<TnDocumentSpecialField>();

    public virtual ICollection<TnDocumentsParam> TnDocumentsParams { get; set; } = new List<TnDocumentsParam>();

    public virtual ICollection<TnOperationTypeDocument> TnOperationTypeDocuments { get; set; } = new List<TnOperationTypeDocument>();

[NotMapped]
    public virtual TnTypesRequete TypeRequeteNavigation { get; set; }
}

