// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnEscalesNavire
{
    public int CodeEscale { get; set; }

    public string SousDossier { get; set; }

    public string Agence { get; set; }

    public string Navire { get; set; }

    public string PortEscale { get; set; }

    public string NumVoyage { get; set; }

    public DateTime? DateArrivee { get; set; }

    public DateTime? DateDepart { get; set; }

    public string PortProvenanceImport { get; set; }

    public string PortDestinationExport { get; set; }

    public string NomCapitaine { get; set; }

    public int NombreEquipage { get; set; }

    public string MotifEscale { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string CaptainNationality { get; set; }

    public string VesselCallId { get; set; }

    public double? VesselDraftOnArrival { get; set; }

    public double? VesselDraftOnDepature { get; set; }

    public string FromHarborIso { get; set; }

    public string ToHarborIso { get; set; }

    public string PortCallIso { get; set; }

    public string CaptainNationalityIso { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnAgence AgenceNavigation { get; set; }

    public virtual TnPay CaptainNationalityNavigation { get; set; }

    public virtual TnNavire NavireNavigation { get; set; }

    public virtual TnLieux PortDestinationExportNavigation { get; set; }

    public virtual TnSitesLocaux PortEscaleNavigation { get; set; }

    public virtual TnLieux PortProvenanceImportNavigation { get; set; }

    public virtual ICollection<TnPassagersEscale> TnPassagersEscales { get; set; } = new List<TnPassagersEscale>();

    public virtual ICollection<TnSof> TnSofs { get; set; } = new List<TnSof>();

    public virtual TnSousDossier TnSousDossier { get; set; }
}