// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnEtapesPrecedente
{
    public int Id { get; set; }

    public int RefEtapePlan { get; set; }

    public int RefEtapePlanPrecedente { get; set; }

    public Guid TenantId { get; set; }
}