// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnEtapesOperation
{
    public string Agence { get; set; }

    public string Operation { get; set; }

    public string SousDossier { get; set; }

    public string EtapeOperation { get; set; }

    public DateTime DateOperationEtape { get; set; }

    public double Qte { get; set; }

    public string ReferenceEtape { get; set; }

    public DateTime? DateAchevement { get; set; }

    public bool PieceDifferee { get; set; }

    public string ObservationEtape { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public int CodeEtapeOperation { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnAgence AgenceNavigation { get; set; }

    public virtual TnSousDossier TnSousDossier { get; set; }
}