// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnEtapesPlansOperation
{
    public int RefEtapePlanOperation { get; set; }

    public string PlanOperation { get; set; }

    public string EtapeOperation { get; set; }

    public bool Couverture { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public bool? Obligatoire { get; set; }

    public int? LimiteAvertissement { get; set; }

    public int? OrdreEtape { get; set; }

    public bool? DateAchvementObligatoire { get; set; }

    public string ObligatoireSiRegime { get; set; }

    public Guid TenantId { get; set; }
}
