// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnFileTypeTabsVisibility
{
    public int Id { get; set; }

    public string FileType { get; set; }

    public int TabId { get; set; }

    public bool? OnCreate { get; set; }

    public bool? OnOpen { get; set; }

    public bool DefaultOnOpen { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnTabName Tab { get; set; }

    public virtual TnTypesDossier TnTypesDossier { get; set; }
}