// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnFileSummary
{
    public string NumDossier { get; set; }

    public string LastStepCode { get; set; }

    public DateTime? LastStepDate { get; set; }

    public string LastStepLabel { get; set; }

    public Guid TenantId { get; set; }
}