// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnFileEstimationDetail
{
    public int Id { get; set; }

    public string NumDossier { get; set; }

    public string Rubrique { get; set; }

    public string Libelle { get; set; }

    public string Observation { get; set; }

    public double MontantDevise { get; set; }

    public double MontantTotal { get; set; }

    public DateTime? ExpectedDate { get; set; }

    public DateTime? AddNewTime { get; set; }

    public DateTime? EditTime { get; set; }

    public int? StatusId { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string PaymentObservation { get; set; }

    public bool? AdvanceMode { get; set; }

    public int? Supplier { get; set; }

    public string VoucherNumber { get; set; }

    public int? Days { get; set; }

    public string DateType { get; set; }

    public string CostPlan { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnFournisseur SupplierNavigation { get; set; }

    public virtual TnDossier TnDossier { get; set; }

    public virtual TnPiece TnPiece { get; set; }
}