// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnFileTabsVisibility
{
    public int Id { get; set; }

    public string TypeDossier { get; set; }

    public bool Connaissement { get; set; }

    public bool Colisage { get; set; }

    public bool Regimes { get; set; }

    public bool Etapes { get; set; }

    public bool Operations { get; set; }

    public bool Requests { get; set; }

    public bool ColisageOnCreation { get; set; }

    public bool RegimeOnCreation { get; set; }

    public bool ComplementOnCreation { get; set; }

    public bool CleareanceOnCreation { get; set; }

    public bool Passengers { get; set; }

    public bool SofImport { get; set; }

    public bool SofExport { get; set; }

    public bool Flight { get; set; }

    public bool FlightPassengers { get; set; }

    public bool VesselsCalls { get; set; }

    public bool Services { get; set; }

    public bool Containers { get; set; }

    public bool BondedWarehouseIn { get; set; }

    public bool BondedWarehouseOut { get; set; }

    public Guid TenantId { get; set; }
}
