// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnFileTypeStep
{
    public int Id { get; set; }

    public string FileType { get; set; }

    public string StepCode { get; set; }

    public bool? Obligatoire { get; set; }

    public int? LimiteAvertissement { get; set; }

    public int? OrdreEtape { get; set; }

    public bool? DateAchvementObligatoire { get; set; }

    public string ObligatoireSiRegime { get; set; }

    public bool IsFileCover { get; set; }

    public Guid TenantId { get; set; }
}
