// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnFileGroupMapping
{
    public int Id { get; set; }

    public string GroupCode { get; set; }

    public string FileCode { get; set; }

    public string ItemType { get; set; }

    public Guid TenantId { get; set; }
}