// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnFournisseur
{
    public int CodeFournisseur { get; set; }

    public string NomFournisseur { get; set; }

    public string LangueFournisseur { get; set; }

    public string Agence { get; set; }

    public int? Country { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string CompteFournisseur { get; set; }

    public int? DelaiPayementFounisseur { get; set; }

    public string ConditionSpeciale { get; set; }

    public string DeviseFournisseur { get; set; }

    public string CodeTvaFournisseur { get; set; }

    public int? ModeReglementFournisseur { get; set; }

    public string CodeConvertionFournisseur { get; set; }

    public string Banque { get; set; }

    public string ObservationsFournisseur { get; set; }

    public string CodeFournisseurSiege { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public bool IsActif { get; set; }

    public string AlordreDe { get; set; }

    public string ChargeBearer { get; set; }

    public string DefaultTypePiece { get; set; }

    public bool? InvoiceForTheClient { get; set; }

    public string TaxTopology { get; set; }

    public bool? IsMainSupplier { get; set; }

    public string ValidationStatus { get; set; }

    public string LatestActionBy { get; set; }

    public string ValidationObservation { get; set; }

    public string ToReviseBy { get; set; }

    public DateTime? LatestValidationActionOn { get; set; }

    public int? WaitingValidationFromGroup { get; set; }

    public int? DefaultCostType { get; set; }

    public string City { get; set; }

    public string ZipCode { get; set; }

    public string Email { get; set; }

    public string DefaultCashType { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnAgence AgenceNavigation { get; set; }

    public virtual TnCodesConvertion CodeConvertionFournisseurNavigation { get; set; }

    public virtual TnCashType DefaultCashTypeNavigation { get; set; }

    public virtual TnCostType DefaultCostTypeNavigation { get; set; }

    public virtual TnDelaisPayement DelaiPayementFounisseurNavigation { get; set; }

    public virtual TnDevise DeviseFournisseurNavigation { get; set; }

    public virtual ICollection<Ecriture> Ecritures { get; set; } = new List<Ecriture>();

    public virtual ICollection<InvStockOperationHeader> InvStockOperationHeaders { get; set; } = new List<InvStockOperationHeader>();

    public virtual ICollection<TnFileEstimationDetail> TnFileEstimationDetails { get; set; } = new List<TnFileEstimationDetail>();

    public virtual ICollection<TnPiecesAchat> TnPiecesAchats { get; set; } = new List<TnPiecesAchat>();

    public virtual ICollection<TnRubriquesAchat> TnRubriquesAchats { get; set; } = new List<TnRubriquesAchat>();

    public virtual ICollection<TnVSupplierCost> TnVSupplierCosts { get; set; } = new List<TnVSupplierCost>();
}