// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnFormulesModule
{
    public int Id { get; set; }

    public string Module { get; set; }

    public string FormuleId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnFormule Formule { get; set; }

[NotMapped]
    public virtual TnModulesOperation ModuleNavigation { get; set; }
}

