// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnGenericTaxesHeader
{
    public int Id { get; set; }

    public string Label { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnGenericTaxesDetail> TnGenericTaxesDetails { get; set; } = new List<TnGenericTaxesDetail>();
}
