// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnGroupesCotation
{
    public string CodeGroupeCotation { get; set; }

    public string LibelleGroupeCotation { get; set; }

    public string LibelleGpfr { get; set; }

    public string LibelleGpus { get; set; }

    public int GroupeFacturation { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnSousGroupesCotation> TnSousGroupesCotations { get; set; } = new List<TnSousGroupesCotation>();

    public virtual ICollection<TnVoucherTypeRestriction> TnVoucherTypeRestrictions { get; set; } = new List<TnVoucherTypeRestriction>();
}