// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnGroupesEstimation
{
    public string CodeGroupeEstimation { get; set; }

    public string LibelleGroupeEstimation { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public bool? Editable { get; set; }

    public string Country { get; set; }

    public string Agency { get; set; }

    public string TypeGroup { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnClient> TnClients { get; set; } = new List<TnClient>();

    public virtual ICollection<TnEstimationsDossier> TnEstimationsDossiers { get; set; } = new List<TnEstimationsDossier>();
}
