// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnGroupEstimationDetail
{
    public int Id { get; set; }

    public string GroupEstimationCode { get; set; }

    public string CodeTypeDossier { get; set; }

    public double? MontantMarge { get; set; }

    public string DeviseMarge { get; set; }

    public double? MontantServices { get; set; }

    public string DeviseServices { get; set; }

    public double? MontantOutlays { get; set; }

    public string DeviseOutlays { get; set; }

    public DateTime? EditTime { get; set; }

    public string EditBy { get; set; }

    public DateTime? CreateTine { get; set; }

    public string CreateBy { get; set; }

    public Guid TenantId { get; set; }
}
