// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnHistoriqueExportation
{
    public int Id { get; set; }

    public DateTime? ExportTime { get; set; }

    public string UserName { get; set; }

    public string FileNom { get; set; }

    public string NumPiece { get; set; }

    public Guid TenantId { get; set; }
}
