// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnImportPieceMapping
{
    public int Id { get; set; }

    public string SourceNumber { get; set; }

    public string DestinationProvisalNumber { get; set; }

    public Guid TenantId { get; set; }
}