// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnInventaire
{
    public string CodeInventaire { get; set; }

    public DateTime DateInventaire { get; set; }

    public string ResponsableInventaire { get; set; }

    public string ObservationInventaire { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnDetailsInventaire> TnDetailsInventaires { get; set; } = new List<TnDetailsInventaire>();

    public virtual ICollection<TnDetailsStock> TnDetailsStocks { get; set; } = new List<TnDetailsStock>();
}