// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnLegalFournisseurRiskMatrix
{
    public int Id { get; set; }

    public string Fournisseur { get; set; }

    public int LegalMatrixId { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnLegalRiskMatrix LegalMatrix { get; set; }
}