// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnLegalEtape
{
    public int Id { get; set; }

    public string Libelle { get; set; }

    public int StatusId { get; set; }

    public int GroupId { get; set; }

    public string Observation { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int? PlanId { get; set; }

    public string LastEditedBy { get; set; }

    public DateTime LastEditTime { get; set; }

    public int EtapeResponsableId { get; set; }

    public double Poids { get; set; }

    public string LibelleRegroupement { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnLegalEtapeResponsable EtapeResponsable { get; set; }

    public virtual TnLegalGroupEtape Group { get; set; }

    public virtual TnLegalPlan Plan { get; set; }

    public virtual TnLegalEtapeStatus Status { get; set; }
}