// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnLegalRiskMatrix
{
    public int Id { get; set; }

    public string Libelle { get; set; }

    public DateTime? ValidFrom { get; set; }

    public DateTime? ValidUntil { get; set; }

    public DateTime CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public string LastEditedBy { get; set; }

    public DateTime LastEditTime { get; set; }

    public double? RiskScoreTotal { get; set; }

    public int? CategoryModel { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnLegalFournisseurRiskMatrix> TnLegalFournisseurRiskMatrices { get; set; } = new List<TnLegalFournisseurRiskMatrix>();

    public virtual ICollection<TnLegalRiskMatrixDetail> TnLegalRiskMatrixDetails { get; set; } = new List<TnLegalRiskMatrixDetail>();
}
