// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnLegalModelePlan
{
    public int Id { get; set; }

    public string Libelle { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnLegalModeleEtape> TnLegalModeleEtapes { get; set; } = new List<TnLegalModeleEtape>();

    public virtual ICollection<TnLegalPlan> TnLegalPlans { get; set; } = new List<TnLegalPlan>();
}