// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnLegalPlan
{
    public int Id { get; set; }

    public string Libelle { get; set; }

    public int ModelPlanId { get; set; }

    public DateTime CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public string LastEditedBy { get; set; }

    public DateTime LastEditDate { get; set; }

    public DateTime ValidFrom { get; set; }

    public DateTime? ValidUntil { get; set; }

    public bool IsActif { get; set; }

    public bool? IsRejected { get; set; }

    public bool? IsApproved { get; set; }

    public string Status { get; set; }

    public DateTime? LastApprovalDate { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnLegalModelePlan ModelPlan { get; set; }

    public virtual ICollection<TnLegalEtape> TnLegalEtapes { get; set; } = new List<TnLegalEtape>();

    public virtual ICollection<TnLegalFournisseurPlan> TnLegalFournisseurPlans { get; set; } = new List<TnLegalFournisseurPlan>();
}