// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnLegalRiskCategory
{
    public int Id { get; set; }

    public string Libelle { get; set; }

    public double Poids { get; set; }

    public int Ordre { get; set; }

    public double NullScore { get; set; }

    public double LowScore { get; set; }

    public double MediumScore { get; set; }

    public double HighScore { get; set; }

    public int? CategoryModel { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnLegalRiskMatrixDetail> TnLegalRiskMatrixDetails { get; set; } = new List<TnLegalRiskMatrixDetail>();
}