// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnLegalGroupEtape
{
    public int Id { get; set; }

    public string Libelle { get; set; }

    public int GroupOrder { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnLegalEtape> TnLegalEtapes { get; set; } = new List<TnLegalEtape>();

    public virtual ICollection<TnLegalModeleEtape> TnLegalModeleEtapes { get; set; } = new List<TnLegalModeleEtape>();
}
