// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnLieux
{
    public string CodeLieu { get; set; }

    public string CodeIata { get; set; }

    public string NomLieu { get; set; }

    public string Pays { get; set; }

    public bool? Aeroport { get; set; }

    public bool Port { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public int? CountryCode { get; set; }

    public Guid TenantId { get; set; }

    public virtual CountryCode CountryCodeNavigation { get; set; }

    public virtual TnPay PaysNavigation { get; set; }

    public virtual ICollection<TnConnaissement> TnConnaissementDestinationNavigations { get; set; } = new List<TnConnaissement>();

    public virtual ICollection<TnConnaissement> TnConnaissementProvenanceNavigations { get; set; } = new List<TnConnaissement>();

    public virtual ICollection<TnEscalesNavire> TnEscalesNavirePortDestinationExportNavigations { get; set; } = new List<TnEscalesNavire>();

    public virtual ICollection<TnEscalesNavire> TnEscalesNavirePortProvenanceImportNavigations { get; set; } = new List<TnEscalesNavire>();
}