// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnListesValeur
{
    public int RefListeValeur { get; set; }

    public string NomListe { get; set; }

    public int Valeur { get; set; }

    public string CodeListe { get; set; }

    public string LibelleListe { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }
}