// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnManifeste
{
    public string CodeManifeste { get; set; }

    public string SiteLocal { get; set; }

    public string MoyenTransport { get; set; }

    public string NumVoyage { get; set; }

    public string SensTrafic { get; set; }

    public DateTime? DatePrevisionnelle { get; set; }

    public DateTime? DateReelle { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public int? CompagnieAgent { get; set; }

    public Guid TenantId { get; set; }

    public virtual GcCompagnieAgent CompagnieAgentNavigation { get; set; }

    public virtual TnMoyensTransport MoyenTransportNavigation { get; set; }

    public virtual TnSitesLocaux SiteLocalNavigation { get; set; }

    public virtual ICollection<TnConnaissement> TnConnaissements { get; set; } = new List<TnConnaissement>();
}