// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnModesReglement
{
    public int CodeModeReglement { get; set; }

    public string LibelleModeReglement { get; set; }

    public string CategorieReglement { get; set; }

    public bool TresorerieDirecte { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnPiece> TnPieces { get; set; } = new List<TnPiece>();
}