// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnModelesCotation
{
    public string CodeModeleCotation { get; set; }

    public string NomModeleCotation { get; set; }

    public string NomCreateur { get; set; }

    public string Agence { get; set; }

    public string Activite { get; set; }

    public int? Client { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string TypeModele { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnAgence AgenceNavigation { get; set; }

    public virtual TnClient ClientNavigation { get; set; }

    public virtual TnActivite TnActivite { get; set; }
}