// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnMoyensTransport
{
    public string NomMoyenTransport { get; set; }

    public string ModeTransport { get; set; }

    public string MasqueConnaissement { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnManifeste> TnManifestes { get; set; } = new List<TnManifeste>();
}
