// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnNationalite
{
    public string CodeNationalite { get; set; }

    public string LibelleNationalite { get; set; }

    public bool Ambassade { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string CounrtyCodeIso { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnPersonne> TnPersonnes { get; set; } = new List<TnPersonne>();
}
