// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnOffresClient
{
    public string CodeOffreClient { get; set; }

    public int Client { get; set; }

    public string DeviseOffre { get; set; }

    public string Agence { get; set; }

    public DateTime DateOffre { get; set; }

    public string LibelleOffre { get; set; }

    public string ModuleOperation { get; set; }

    public double ForfaitOffre { get; set; }

    public string ResponsableOffre { get; set; }

    public DateTime? DateValidationOffre { get; set; }

    public DateTime DateExpirationOffre { get; set; }

    public string ParametresOffre { get; set; }

    public string ObservationsOffre { get; set; }

    public string StatutOffre { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnAgence AgenceNavigation { get; set; }

[NotMapped]
    public virtual TnClient ClientNavigation { get; set; }

[NotMapped]
    public virtual TnDevise DeviseOffreNavigation { get; set; }

    public virtual ICollection<TnDetailsOffresClient> TnDetailsOffresClients { get; set; } = new List<TnDetailsOffresClient>();
}

