// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnOperationSubTypesTypeDossier
{
    public int Id { get; set; }

    public int OperationSubTypesId { get; set; }

    public string CodeTypeDossier { get; set; }

    public Guid TenantId { get; set; }
}