// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnOperationTypeDocument
{
    public int Id { get; set; }

    public string DocumentId { get; set; }

    public int? OperationTypeId { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnDocument Document { get; set; }
}