// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnPassagersEscale
{
    public int RefPassager { get; set; }

    public int Escale { get; set; }

    public string Personne { get; set; }

    public bool Import { get; set; }

    public bool Export { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnEscalesNavire EscaleNavigation { get; set; }

[NotMapped]
    public virtual TnPersonne PersonneNavigation { get; set; }
}

