// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnParametresApp
{
    public string Parameter { get; set; }

    public int Type { get; set; }

    public string RowSource { get; set; }

    public string Value { get; set; }

    public bool Visible { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public int CountryId { get; set; }
}