// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnPaysNew
{
    public string CodePays { get; set; }

    public string NomPays { get; set; }

    public string A2 { get; set; }

    public Guid TenantId { get; set; }
}