// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnPassagersVol
{
    public int CodePassager { get; set; }

    public string Personne { get; set; }

    public string SousDossier { get; set; }

    public string Provenance { get; set; }

    public string Destination { get; set; }

    public string PointTransfert { get; set; }

    public string DocumentVol { get; set; }

    public string Observations { get; set; }

    public string Vol { get; set; }

    public string StatutPassager { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnDocumentsVol DocumentVolNavigation { get; set; }

[NotMapped]
    public virtual TnPersonne PersonneNavigation { get; set; }

[NotMapped]
    public virtual TnSousDossier TnSousDossier { get; set; }

[NotMapped]
    public virtual TnVol VolNavigation { get; set; }
}

