// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnPersonne
{
    public string CodePersonne { get; set; }

    public string NomsEtPrenoms { get; set; }

    public string NumPassport { get; set; }

    public string Nationalite { get; set; }

    public string Grade { get; set; }

    public DateTime? DateNaissance { get; set; }

    public DateTime? DateValiditePasseport { get; set; }

    public DateTime? DateValiditeVisa { get; set; }

    public int? Client { get; set; }

    public string Division { get; set; }

    public string Observations { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string NumSeamanBook { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string DeliveryPlace { get; set; }

    public string PlaceOfBirth { get; set; }

    public string Prenom { get; set; }

    public bool? Active { get; set; }

    public int? CountryCode { get; set; }

    public string AppRequest { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnClient ClientNavigation { get; set; }

[NotMapped]
    public virtual CountryCode CountryCodeNavigation { get; set; }

[NotMapped]
    public virtual TnDivision DivisionNavigation { get; set; }

[NotMapped]
    public virtual TnNationalite NationaliteNavigation { get; set; }

    public virtual ICollection<TnPassagersEscale> TnPassagersEscales { get; set; } = new List<TnPassagersEscale>();

    public virtual ICollection<TnPassagersVol> TnPassagersVols { get; set; } = new List<TnPassagersVol>();
}

