// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnPfdaPaymentsLink
{
    public int Id { get; set; }

    public string PaymentNumber { get; set; }

    public string TableCode { get; set; }

    public string TableType { get; set; }

    public DateTime? LinkedDate { get; set; }

    public string LinkedBy { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnPiece TnPiece { get; set; }
}