// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnPiecesVente
{
    public string NumPieceVente { get; set; }

    public int Client { get; set; }

    public string DossierReference { get; set; }

    public string DescriptionPiece { get; set; }

    public string CodeTva { get; set; }

    public string AdresseFacturation { get; set; }

    public string NumeroTransmission { get; set; }

    public DateTime? DateTransmission { get; set; }

    public string PiedPageFacture { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string NumeroTransmissionProvisoire { get; set; }

    public DateTime? DateTransmissionProvisoire { get; set; }

    public double? ValeurCif { get; set; }

    public double? ValeurFob { get; set; }

    public string DeviseValeur { get; set; }

    public int? SousDossierIndex { get; set; }

    public double? CommissionDebours { get; set; }

    public int? ClientPo { get; set; }

    public string BillingStreet { get; set; }

    public string BillingCity { get; set; }

    public string BillingZipCode { get; set; }

    public string BillingCountry { get; set; }

    public int? PaymentTermsId { get; set; }

    public bool SameAsBillingAddress { get; set; }

    public string DeliveryStreet { get; set; }

    public string DeliveryCity { get; set; }

    public string DeliveryZipCode { get; set; }

    public string DeliveryCountry { get; set; }

    public string ContactName { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnClient ClientNavigation { get; set; }

    public virtual TnDossier TnDossier { get; set; }

    public virtual TnPiece TnPiece { get; set; }
}