// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnPiecesStock
{
    public string NumPieceStock { get; set; }

    public string ProduitStock { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnProduitsStock ProduitStockNavigation { get; set; }

[NotMapped]
    public virtual TnPiece TnPiece { get; set; }
}

