// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnPieceClientDebitNote
{
    public int Id { get; set; }

    public string NumPieceClient { get; set; }

    public string NumDebitNote { get; set; }

    public double? Rate { get; set; }

    public double MontantDebitNote { get; set; }

    public Guid TenantId { get; set; }
}
