// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnPiecesAchat
{
    public string NumPieceAchat { get; set; }

    public int Fournisseur { get; set; }

    public string CodeTva { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string AdresseFournisseur { get; set; }

    public bool? VoucherForTheClient { get; set; }

    public string TaxTopology { get; set; }

    public bool? RemoveFromSaft { get; set; }

    public int? PaymentTermsId { get; set; }

    public Guid TenantId { get; set; }

    public string PoNumber { get; set; }

    public virtual TnFournisseur FournisseurNavigation { get; set; }

    public virtual TnPiecesAchat InverseTnPiecesAchatNavigation { get; set; }

    public virtual TnPiece TnPiece { get; set; }

    public virtual TnPiecesAchat TnPiecesAchatNavigation { get; set; }
}