// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnPlansOperation
{
    public string CodePlanOperation { get; set; }

    public string LibellePlanOperation { get; set; }

    public string Regroupement { get; set; }

    public string SerieOperation { get; set; }

    public string RowSource { get; set; }

    public bool ValidationImmediate { get; set; }

    public bool ValiditeRequise { get; set; }

    public string ModuleOperation { get; set; }

    public string SensTrafic { get; set; }

    public string ModeTransport { get; set; }

    public int Flag { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnCodesEtape> TnCodesEtapes { get; set; } = new List<TnCodesEtape>();

    public virtual ICollection<TnTypesDossier> TnTypesDossiers { get; set; } = new List<TnTypesDossier>();
}
