// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnPositionsTarifaire
{
    public string CodePosition { get; set; }

    public string DesignationPosition { get; set; }

    public string DesignationPosition2 { get; set; }

    public string SousChapitre { get; set; }

    public string GroupePosition { get; set; }

    public string TypeProduit { get; set; }

    public string DispositionsSpeciales { get; set; }

    public string TcaOuTva { get; set; }

    public string DroitAccise { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnSousChapitresTarif SousChapitreNavigation { get; set; }

    public virtual ICollection<TnDetailsPosition> TnDetailsPositions { get; set; } = new List<TnDetailsPosition>();

    public virtual TnTypesProduit TypeProduitNavigation { get; set; }
}