// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnProduitsColisage
{
    public string CodeProduitColisage { get; set; }

    public string NomProduit { get; set; }

    public string CategorieProduit { get; set; }

    public string DescriptionProduit { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnDetailsConnaissement> TnDetailsConnaissements { get; set; } = new List<TnDetailsConnaissement>();
}