// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnPricingValidityLog
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string UserFullName { get; set; }

    public string Status { get; set; }

    public DateTime DateLog { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnTarifsClient CodeNavigation { get; set; }
}

