// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnProjet
{
    public string CodeProjet { get; set; }

    public string AgenceCloture { get; set; }

    public string TitreProjet { get; set; }

    public int Client { get; set; }

    public string TypeProjet { get; set; }

    public string DescriptionProjet { get; set; }

    public string ResponsableProjet { get; set; }

    public string AgenceProjet { get; set; }

    public DateTime DateDebutProjet { get; set; }

    public DateTime? DateFinProjet { get; set; }

    public string Agences { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnAgence AgenceClotureNavigation { get; set; }

[NotMapped]
    public virtual TnAgence AgenceProjetNavigation { get; set; }

[NotMapped]
    public virtual TnClient ClientNavigation { get; set; }

    public virtual ICollection<TnActionsProjet> TnActionsProjets { get; set; } = new List<TnActionsProjet>();

[NotMapped]
    public virtual TnTypesProjet TypeProjetNavigation { get; set; }
}

