// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnRapportsProjet
{
    public string CodeRapportProjet { get; set; }

    public string Action { get; set; }

    public string AgenceRapport { get; set; }

    public DateTime DateRapport { get; set; }

    public string DescriptionRapport { get; set; }

    public string ResponsableRapport { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnActionsProjet ActionNavigation { get; set; }

    public virtual TnAgence AgenceRapportNavigation { get; set; }
}