// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnReference
{
    public int Key { get; set; }

    public string CategorieReference { get; set; }

    public string CodeReference { get; set; }

    public string LibelleReference { get; set; }

    public string Observations { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnCategoriesReference CategorieReferenceNavigation { get; set; }
}