// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnRegimesDocument
{
    public int Id { get; set; }

    public string RegimeCode { get; set; }

    public int DocumentCode { get; set; }

    public bool IsMandatory { get; set; }

    public Guid TenantId { get; set; }
}