// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnRubriquesAchatsPlansOp
{
    public int RefRubriqueAchat { get; set; }

    public string PlanOperation { get; set; }

    public string RubriqueAchat { get; set; }

    public string Condition { get; set; }

    public double TauxAchat { get; set; }

    public double MontantMinAchat { get; set; }

    public double MontantMaxAchat { get; set; }

    public bool TauxFixe { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string CodeEtape { get; set; }

    public int? Days { get; set; }

    public string DateType { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnRubriquesAchat RubriqueAchatNavigation { get; set; }
}

