// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnRubriquesCotation
{
    public string CodeRubriqueCotation { get; set; }

    public string LibelleRubriqueCotation { get; set; }

    public string LibelleFr { get; set; }

    public string LibelleUs { get; set; }

    public string SousGroupeCotation { get; set; }

    public string LibelleRegroupement { get; set; }

    public int OrdreRegroupement { get; set; }

    public string LibelleFacturation { get; set; }

    public string ModuleOperation { get; set; }

    public string Condition { get; set; }

    public string Devise { get; set; }

    public double Taux { get; set; }

    public string FormuleVente { get; set; }

    public string BaseDescription { get; set; }

    public double MontantMin { get; set; }

    public double MontantMax { get; set; }

    public bool TauxFixe { get; set; }

    public float CommissionDebours { get; set; }

    public string Remarque { get; set; }

    public string DocumentJustificatif { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string LibelleRubriqueCotationFr { get; set; }

    public string LibelleRegroupementFr { get; set; }

    public string LibelleFacturationFr { get; set; }

    public string LibelleRubriqueCotationEs { get; set; }

    public string LibelleRegroupementEs { get; set; }

    public string LibelleFacturationEs { get; set; }

    public string LibelleRubriqueCotationPt { get; set; }

    public string LibelleRegroupementPt { get; set; }

    public string LibelleFacturationPt { get; set; }

    public string ContenuFormule { get; set; }

    public string DescriptionFormule { get; set; }

    public bool? TaxExcluded { get; set; }

    public bool? IsPercentage { get; set; }

    public bool? DefaultSaleCategory { get; set; }

    public bool? DefaultPurchaseCategory { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnArticle> TnArticles { get; set; } = new List<TnArticle>();

    public virtual ICollection<TnDetailsOffresClient> TnDetailsOffresClients { get; set; } = new List<TnDetailsOffresClient>();

    public virtual ICollection<TnDetailsPiece> TnDetailsPieces { get; set; } = new List<TnDetailsPiece>();

    public virtual ICollection<TnDetailsTarifsClient> TnDetailsTarifsClients { get; set; } = new List<TnDetailsTarifsClient>();

    public virtual ICollection<TnDevisDetail> TnDevisDetails { get; set; } = new List<TnDevisDetail>();

    public virtual ICollection<TnRubriquesAchat> TnRubriquesAchats { get; set; } = new List<TnRubriquesAchat>();
}