// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnRubriquesAchat
{
    public string CodeRubriqueAchat { get; set; }

    public string LibelleRubriqueAchat { get; set; }

    public string RowSource { get; set; }

    public int? Article { get; set; }

    public string RubriqueVente { get; set; }

    public string DeviseAchat { get; set; }

    public double TauxAchat { get; set; }

    public string FormuleAchat { get; set; }

    public double MontantMinAchat { get; set; }

    public double MontantMaxAchat { get; set; }

    public bool TauxFixe { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public int? CostType { get; set; }

    public bool? AdvanceMode { get; set; }

    public int? Supplier { get; set; }

    public bool? IsActive { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnArticle ArticleNavigation { get; set; }

[NotMapped]
    public virtual TnDevise DeviseAchatNavigation { get; set; }

[NotMapped]
    public virtual TnFormule FormuleAchatNavigation { get; set; }

[NotMapped]
    public virtual TnRubriquesCotation RubriqueVenteNavigation { get; set; }

[NotMapped]
    public virtual TnFournisseur SupplierNavigation { get; set; }

    public virtual ICollection<TnRubriquesAchatsPlansOp> TnRubriquesAchatsPlansOps { get; set; } = new List<TnRubriquesAchatsPlansOp>();
}

