// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnRubriquesSof
{
    public int RefRubriqueSof { get; set; }

    public string LibelleSof { get; set; }

    public bool Import { get; set; }

    public bool Export { get; set; }

    public bool Previsionnel { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public bool? IsActive { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnSofRubricPlan> TnSofRubricPlans { get; set; } = new List<TnSofRubricPlan>();

    public virtual ICollection<TnSof> TnSofs { get; set; } = new List<TnSof>();
}