// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnRubriquesModelesCotation
{
    public int RefRubriqueModele { get; set; }

    public string ModeleCotation { get; set; }

    public string RubriqueCotation { get; set; }

    public string LibelleRubriqueCotation { get; set; }

    public string LibelleRegroupement { get; set; }

    public int OrdreRegroupement { get; set; }

    public string LibelleFacturation { get; set; }

    public string Condition { get; set; }

    public string Devise { get; set; }

    public double Taux { get; set; }

    public double MontantMin { get; set; }

    public double MontantMax { get; set; }

    public bool TauxFixe { get; set; }

    public string BaseDescription2 { get; set; }

    public float CommissionDebours { get; set; }

    public string Remarque { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string LibelleRubriqueCotationFr { get; set; }

    public string LibelleRegroupementFr { get; set; }

    public string LibelleFacturationFr { get; set; }

    public string LibelleRubriqueCotationEs { get; set; }

    public string LibelleRegroupementEs { get; set; }

    public string LibelleFacturationEs { get; set; }

    public string LibelleRubriqueCotationPt { get; set; }

    public string LibelleRegroupementPt { get; set; }

    public string LibelleFacturationPt { get; set; }

    public string ContenuFormule { get; set; }

    public string CodeFormule { get; set; }

    public string DescriptionFormule { get; set; }

    public bool? TaxExcluded { get; set; }

    public bool? IsPercentage { get; set; }

    public Guid TenantId { get; set; }
}