// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnShippingMvt
{
    public int Id { get; set; }

    public string SousDossier { get; set; }

    public string FromPlace { get; set; }

    public DateTime DepartureTimeFromPlace { get; set; }

    public string ToPlace { get; set; }

    public DateTime? ArrivalTimeToPlace { get; set; }

    public string Ref1 { get; set; }

    public string Ref2 { get; set; }

    public string UserName { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime EditDate { get; set; }

    public Guid TenantId { get; set; }
}
