// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnSof
{
    public int RefSof { get; set; }

    public int Escale { get; set; }

    public string SensTrafic { get; set; }

    public int RubriqueSof { get; set; }

    public int IndexSof { get; set; }

    public DateTime? DateEtHeure { get; set; }

    public string Observations { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string LibelleSof { get; set; }

    public bool? IsSpecial { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnEscalesNavire EscaleNavigation { get; set; }

[NotMapped]
    public virtual TnRubriquesSof RubriqueSofNavigation { get; set; }
}

