// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnSousDossiersRecap
{
    public string SousDossier { get; set; }

    public string RegimesDossier { get; set; }

    public string ComplementsDossier { get; set; }

    public string ColisageDossier { get; set; }

    public string ConnaissementsDossier { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnSousDossier TnSousDossier { get; set; }
}

