// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnSofRubricPlan
{
    public int Id { get; set; }

    public int SofrubricId { get; set; }

    public int SofplanId { get; set; }

    public int OrderLine { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnSofPlan Sofplan { get; set; }

    public virtual TnRubriquesSof Sofrubric { get; set; }
}