// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnSofPlan
{
    public int Id { get; set; }

    public string SofplanName { get; set; }

    public bool? IsForImport { get; set; }

    public bool? IsForExport { get; set; }

    public string Observation { get; set; }

    public DateTime AddNewTime { get; set; }

    public string CreatedBy { get; set; }

    public DateTime EditTime { get; set; }

    public string EditedBy { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnSofPlanFileType> TnSofPlanFileTypes { get; set; } = new List<TnSofPlanFileType>();

    public virtual ICollection<TnSofRubricPlan> TnSofRubricPlans { get; set; } = new List<TnSofRubricPlan>();
}