// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnSofPlanFileType
{
    public int Id { get; set; }

    public int SofplanId { get; set; }

    public string FileTypeId { get; set; }

    public bool? IsDefault { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnSofPlan Sofplan { get; set; }
}