// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnSousGroupesCotation
{
    public string CodeSousGroupeCotation { get; set; }

    public string LibelleSousGroupeCotation { get; set; }

    public string LibelleSgfr { get; set; }

    public string LibelleSgus { get; set; }

    public string GroupeCotation { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnGroupesCotation GroupeCotationNavigation { get; set; }
}