// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnSousTypesColisage
{
    public int Id { get; set; }

    public string LibelleSousTypeColis { get; set; }

    public string CodeSousTypeColis { get; set; }

    public string TypeId { get; set; }

    public bool? SuiviConteneur { get; set; }

    public bool? MarqueMantadory { get; set; }

    public string MarquePattern { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }
}