// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnSousDossier
{
    public string CodeSousDossier { get; set; }

    public string Dossier { get; set; }

    public int Index { get; set; }

    public int Client { get; set; }

    public string RefClient { get; set; }

    public string ClientPc { get; set; }

    public string OffreClient { get; set; }

    public string ObservationsDossier { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string ManufacturingCountry { get; set; }

    public string LastDestination { get; set; }

    public string ConsignePc { get; set; }

    public string FileLinkedWith { get; set; }

    public string FileLinckedWith { get; set; }

    public string RefConnaissement { get; set; }

    public string NominatedPartyId { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnClient ClientNavigation { get; set; }

    public virtual TnClientsPc ClientPcNavigation { get; set; }

    public virtual TnPay ManufacturingCountryNavigation { get; set; }

    public virtual ICollection<TnColisagesDossier> TnColisagesDossiers { get; set; } = new List<TnColisagesDossier>();

    public virtual ICollection<TnDetailsOperation> TnDetailsOperations { get; set; } = new List<TnDetailsOperation>();

    public virtual ICollection<TnDetailsPiece> TnDetailsPieces { get; set; } = new List<TnDetailsPiece>();

    public virtual TnDossier TnDossier { get; set; }

    public virtual ICollection<TnDossiersCommentaire> TnDossiersCommentaires { get; set; } = new List<TnDossiersCommentaire>();

    public virtual ICollection<TnDossiersComplement> TnDossiersComplements { get; set; } = new List<TnDossiersComplement>();

    public virtual ICollection<TnDossiersRegime> TnDossiersRegimes { get; set; } = new List<TnDossiersRegime>();

    public virtual ICollection<TnEscalesNavire> TnEscalesNavires { get; set; } = new List<TnEscalesNavire>();

    public virtual ICollection<TnEtapesOperation> TnEtapesOperations { get; set; } = new List<TnEtapesOperation>();

    public virtual ICollection<TnMobileDetailsOperation> TnMobileDetailsOperations { get; set; } = new List<TnMobileDetailsOperation>();

    public virtual ICollection<TnPassagersVol> TnPassagersVols { get; set; } = new List<TnPassagersVol>();

    public virtual ICollection<TnRequest> TnRequests { get; set; } = new List<TnRequest>();

    public virtual ICollection<TnSousDossiersRecap> TnSousDossiersRecaps { get; set; } = new List<TnSousDossiersRecap>();
}