// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnSplit
{
    public int SplitId { get; set; }

    public string NumPiece { get; set; }

    public string Division { get; set; }

    public int? SplitTypeId { get; set; }

    public double? Ratio { get; set; }

    public string UserName { get; set; }

    public Guid TenantId { get; set; }
}
