// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnStatutsDossier
{
    public string CodeStatutDossier { get; set; }

    public string LibelleStatutDossier { get; set; }

    public string DescriptionStatutDossier { get; set; }

    public int CodeValeur { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public virtual ICollection<TnDossier> TnDossiers { get; set; } = new List<TnDossier>();
}