// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnSuppliersSan
{
    public int Id { get; set; }

    public string EntityCode { get; set; }

    public DateTime Sandate { get; set; }

    public double San { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime EditTime { get; set; }

    public string EditedBy { get; set; }

    public bool Editable { get; set; }

    public Guid TenantId { get; set; }
}
