// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTarifDegressif
{
    public int IdTd { get; set; }

    public int? DetailDevisId { get; set; }

    public string CodeDevis { get; set; }

    public string Libelle { get; set; }

    public string Variable { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? EditNewTime { get; set; }

    public string CreatedBy { get; set; }

    public string EditedBy { get; set; }

    public int ModelId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnDevi CodeDevisNavigation { get; set; }

[NotMapped]
    public virtual TnDevisDetail DetailDevis { get; set; }
}

