// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTarifsDegressifsModel
{
    public int IdTdModel { get; set; }

    public string Libelle { get; set; }

    public string Variable { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? EditNewTime { get; set; }

    public string CreatedBy { get; set; }

    public string EditedBy { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnTarifsDegressifModelsDetail> TnTarifsDegressifModelsDetails { get; set; } = new List<TnTarifsDegressifModelsDetail>();
}