// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTaxeGroupe
{
    public int Id { get; set; }

    public int Tax { get; set; }

    public int Groupe { get; set; }

    public double Pourcentage { get; set; }

    public int Ordre { get; set; }

    public string Libelle { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnDetailGrouping GroupeNavigation { get; set; }

[NotMapped]
    public virtual TnListeTaxis TaxNavigation { get; set; }
}

