// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTarifsClient
{
    public string CodeTarifClient { get; set; }

    public int Client { get; set; }

    public string Agences { get; set; }

    public DateTime DateTarif { get; set; }

    public string LibelleTarif { get; set; }

    public string ModuleOperation { get; set; }

    public string ResponsableTarif { get; set; }

    public DateTime DateExpirationTarif { get; set; }

    public DateTime? DateValidationTarif { get; set; }

    public string ObservationsTarif { get; set; }

    public string StatutTarif { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public string RejectionReason { get; set; }

    public string RejectionDescription { get; set; }

    public DateTime? ValidatedOn { get; set; }

    public DateTime? ValidFrom { get; set; }

    public DateTime? ValidUntil { get; set; }

    public string ValidatedBy { get; set; }

    public DateTime? ApprovalDate { get; set; }

    public int RevIndex { get; set; }

    public string Substatus { get; set; }

    public DateTime? OfferValidity { get; set; }

    public bool IsFinalVersion { get; set; }

    public bool? OutlaysSp { get; set; }

    public bool? ServicesSp { get; set; }

    public bool? RemarksSp { get; set; }

    public bool? TaxesSp { get; set; }

    public bool? LumpsumSp { get; set; }

    public bool? AdvancesSp { get; set; }

    public bool IsModel { get; set; }

    public bool? TaxeExo { get; set; }

    public string Tender { get; set; }

    public double? CommissionDebours { get; set; }

    public DateTime? TransmissionDate { get; set; }

    public bool? ValidityDateForOperation { get; set; }

    public string LastEditedBy { get; set; }

    public DateTime? LastEditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnClient ClientNavigation { get; set; }

    public virtual ICollection<TnDetailsTarifsClient> TnDetailsTarifsClients { get; set; } = new List<TnDetailsTarifsClient>();

    public virtual ICollection<TnPricingValidityLog> TnPricingValidityLogs { get; set; } = new List<TnPricingValidityLog>();

    public virtual ICollection<TnTarifAgence> TnTarifAgences { get; set; } = new List<TnTarifAgence>();
}

