// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTarifAgence
{
    public int Id { get; set; }

    public string CodeTarif { get; set; }

    public string CodeAgence { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnTarifsClient CodeTarifNavigation { get; set; }
}

