// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTarifDegressifDetail
{
    public int IdTdDetail { get; set; }

    public int? TarifDegressifId { get; set; }

    public double? FromValue { get; set; }

    public double? ToValue { get; set; }

    public string Value { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? EditNewTime { get; set; }

    public string CreatedBy { get; set; }

    public string EditedBy { get; set; }

    public string SpecificValue { get; set; }

    public Guid TenantId { get; set; }
}
