// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTabName
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Label { get; set; }

    public bool? HasCreateStep { get; set; }

    public int? TabOrder { get; set; }

    public virtual ICollection<TnFileTypeTabsVisibility> TnFileTypeTabsVisibilities { get; set; } = new List<TnFileTypeTabsVisibility>();
}