// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTemp
{
    public string Value1 { get; set; }

    public string Value2 { get; set; }

    public string Value3 { get; set; }

    public Guid TenantId { get; set; }
}
