// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTosynchronize
{
    public int Id { get; set; }

    public string Piece { get; set; }

    public string SourceAgency { get; set; }

    public bool? Synchrnize { get; set; }

    public DateTime? AddNewTime { get; set; }

    public string CreatedBy { get; set; }

    public Guid TenantId { get; set; }
}
