// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTypesRequete
{
    public string CodeTypeRequete { get; set; }

    public string LibelleTypeRequete { get; set; }

    public string DescriptionRequete { get; set; }

    public string TexteSql { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnDocument> TnDocuments { get; set; } = new List<TnDocument>();
}