// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTypePieceTypeCash
{
    public int Id { get; set; }

    public string TypePiece { get; set; }

    public string TypeCash { get; set; }

    public bool IsDefaultForTypePiece { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnCashType TypeCashNavigation { get; set; }

    public virtual TnTypesPiece TypePieceNavigation { get; set; }
}