// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTypesCompte
{
    public string CodeTypeCompte { get; set; }

    public string LibelleTypeCompte { get; set; }

    public string CategorieCompte { get; set; }

    public string ParametreCompte { get; set; }

    public string GroupeCompte { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }
}