// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnTypesProduit
{
    public string CodeTypeProduit { get; set; }

    public string LibelleTypeProduit { get; set; }

    public string CategorieProduit { get; set; }

    public float TauxDroitDouane { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnPositionsTarifaire> TnPositionsTarifaires { get; set; } = new List<TnPositionsTarifaire>();
}
