// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnUnite
{
    public string CodeUnite { get; set; }

    public string LibelleUnite { get; set; }

    public string CategorieUnite { get; set; }

    public double ValeurUnite { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnCategoriesUnite CategorieUniteNavigation { get; set; }

    public virtual ICollection<TnDetailsInventaire> TnDetailsInventaires { get; set; } = new List<TnDetailsInventaire>();
}

