// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnUserAccountingYear
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public int AccountingYear { get; set; }

    public Guid TenantId { get; set; }
}
