// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnVehicle
{
    public int Id { get; set; }

    public string ConstructorVehicle { get; set; }

    public string Type { get; set; }

    public DateTime? DateOfCirculation { get; set; }

    public string Color { get; set; }

    public string NumberOfSeats { get; set; }

    public string PlateNumber { get; set; }

    public DateTime? LatestControlDate { get; set; }

    public DateTime? AddNewTime { get; set; }

    public DateTime? EditTime { get; set; }

    public string Model { get; set; }

    public int? KmInitial { get; set; }

    public int? KmActual { get; set; }

    public string Owner { get; set; }

    public string InsuranceCompany { get; set; }

    public string SubStatus { get; set; }

    public string PurchaseType { get; set; }

    public int? AdministrativePower { get; set; }

    public int? MaximumHppower { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public string PhotoUrl { get; set; }

    public int? PurchasePrice { get; set; }

    public string PurchaseCurrency { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? MonthlyAmount { get; set; }

    public int? VehicleTypeId { get; set; }

    public string AssignIn { get; set; }

    public decimal? AvgConsumption { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnVVehicleCostDetail> TnVVehicleCostDetails { get; set; } = new List<TnVVehicleCostDetail>();

    public virtual ICollection<VehicleEquipment> VehicleEquipments { get; set; } = new List<VehicleEquipment>();

    public virtual ICollection<VehicleLog> VehicleLogs { get; set; } = new List<VehicleLog>();
}