// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnVFuelTypeVehiculeType
{
    public int Id { get; set; }

    public int? TnVFuelTypeId { get; set; }

    public int? TnVVehiculeTypeId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnVFuelType TnVFuelType { get; set; }

[NotMapped]
    public virtual TnVVehiculeType TnVVehiculeType { get; set; }
}

