// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnVolsRecurrent
{
    public int Id { get; set; }

    public string TypeVoyage { get; set; }

    public string NomCompagnie { get; set; }

    public string NumVoyage { get; set; }

    public DateTime VolDate { get; set; }

    public string Sens { get; set; }

    public string Aeroport { get; set; }

    public Guid TenantId { get; set; }
}
