// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnVoucherTypeRestriction
{
    public int Id { get; set; }

    public string TypePiece { get; set; }

    public string GroupeRubriqueCotation { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual TnGroupesCotation GroupeRubriqueCotationNavigation { get; set; }

[NotMapped]
    public virtual TnTypesPiece TypePieceNavigation { get; set; }
}

