// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnVVehicleCost
{
    public int Id { get; set; }

    public string Label { get; set; }

    public bool? AskForKm { get; set; }

    public bool? AskForLitres { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnVSupplierCost> TnVSupplierCosts { get; set; } = new List<TnVSupplierCost>();

    public virtual ICollection<TnVVehicleCostDetail> TnVVehicleCostDetails { get; set; } = new List<TnVVehicleCostDetail>();
}