// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TnVVehicleCostDetail
{
    public int Id { get; set; }

    public string VoucherDetailsNumber { get; set; }

    public int? VehicleCostId { get; set; }

    public int? Km { get; set; }

    public int? Qty { get; set; }

    public string FullType { get; set; }

    public int? VehicleId { get; set; }

    public string Justification { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnVehicle Vehicle { get; set; }

    public virtual TnVVehicleCost VehicleCost { get; set; }
}