// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class Traduction
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Language { get; set; }

    public string Translation { get; set; }

    public string Fieldname { get; set; }

    public string Tablename { get; set; }

    public DateTime? Createdate { get; set; }

    public DateTime? Editdate { get; set; }
}