// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

/// <summary>
/// Traductions deduplicees : un source_label ne peut avoir qu&apos;une seule traduction par langue.
/// </summary>
public partial class TranslationDatum
{
    public int Id { get; set; }

    /// <summary>
    /// Valeur originale du champ (texte brut, pas le code PK de la ligne).
    /// </summary>
    public string SourceLabel { get; set; }

    /// <summary>
    /// Texte traduit. NULL = traduction non encore renseignee.
    /// </summary>
    public string TranslatedLabel { get; set; }

    /// <summary>
    /// Code langue normalise lowercase (fr, en, de, es, pt...).
    /// </summary>
    public string Language { get; set; }

    public DateTime? AddNewTime { get; set; }
}