// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

/// <summary>
/// Configuration des champs a traduire : une ligne par (table, champ).
/// </summary>
public partial class TranslationField
{
    public int Id { get; set; }

    /// <summary>
    /// Nom de la table contenant le champ (sans schema, schema est le schema tenant).
    /// </summary>
    public string TableName { get; set; }

    /// <summary>
    /// Nom de la colonne dont la valeur doit etre traduite.
    /// </summary>
    public string FieldName { get; set; }

    /// <summary>
    /// Optionnel : groupement fonctionnel (ex: &quot;articles&quot;, &quot;operations&quot;).
    /// </summary>
    public string Menu { get; set; }

    public DateTime? AddNewTime { get; set; }
}