// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TxDossier
{
    public string File { get; set; }

    public string Type { get; set; }

    public string Agency { get; set; }

    public DateTime Period { get; set; }

    public DateTime Date { get; set; }

    public string Customer { get; set; }

    public string Division { get; set; }

    public string CustomerRef { get; set; }

    public string CustomerPo { get; set; }

    public string CustomerOffer { get; set; }

    public string Hqfile { get; set; }

    public DateTime? ControlDate { get; set; }

    public string Regimes { get; set; }

    public string Complements { get; set; }

    public string Colisage { get; set; }

    public string Connaissements { get; set; }

    public string NomClient0 { get; set; }

    public string LibelleDivision0 { get; set; }

    public string Observations { get; set; }

    public string Status { get; set; }

    public bool Exported { get; set; }

    public bool Skip { get; set; }

    public bool Init { get; set; }

    public int Session { get; set; }

    public DateTime AddNewTime { get; set; }

    public DateTime EditTime { get; set; }

    public Guid TenantId { get; set; }
}