// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class TypePieceDossier
{
    public int Id { get; set; }

    public string CodeTypePiece { get; set; }

    public string CodeTypeDossier { get; set; }

    public string Type { get; set; }

    public DateTime AddNewTime { get; set; }

    public string CreatedBy { get; set; }

    public DateOnly EditTime { get; set; }

    public string ModifiedBy { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnTypesDossier TnTypesDossier { get; set; }
}