// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class UserFavourite
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int FavouriteId { get; set; }

    public int OrderBy { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual Erpfavourite Favourite { get; set; }

[NotMapped]
    public virtual User User { get; set; }
}

