// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class User
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public bool IsActive { get; set; }

    public DateTime? EditTime { get; set; }

    public byte[] SignatureDoc { get; set; }

    public double? SignatureTaille { get; set; }

    public string SignatureExtension { get; set; }

    public string Photo { get; set; }

    public string AttachedCountry { get; set; }

    public string AttachedAgency { get; set; }

    public int? JobDepartmentId { get; set; }

    public int? JobTitleId { get; set; }

    public bool? IsBlocked { get; set; }

    public bool? ReceiveNotifications { get; set; }

    public bool? IsAdmin { get; set; }

    public bool? ReadTerms { get; set; }

    public string FontSize { get; set; }

    public string Theme { get; set; }

    public string PreferredLanguage { get; set; }

    public string PreferredModule { get; set; }

    public string ParentsUserName { get; set; }

    public Guid? TenantId { get; set; }

    public bool? IsErpUser { get; set; }

    public virtual ICollection<ErpcustomUserFilterHeader> ErpcustomUserFilterHeaders { get; set; } = new List<ErpcustomUserFilterHeader>();

    public virtual ICollection<ErpuserGridFilter> ErpuserGridFilters { get; set; } = new List<ErpuserGridFilter>();

    public virtual ICollection<ErpuserModule> ErpuserModules { get; set; } = new List<ErpuserModule>();

    public virtual ICollection<GroupUser> GroupUsers { get; set; } = new List<GroupUser>();

    public virtual ICollection<UserClaim> UserClaims { get; set; } = new List<UserClaim>();

    public virtual ICollection<UserDocumentAction> UserDocumentActions { get; set; } = new List<UserDocumentAction>();

    public virtual ICollection<UserFavourite> UserFavourites { get; set; } = new List<UserFavourite>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}
