// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class VehicleOperationSubCategory
{
    public int Id { get; set; }

    public int? SubCategoryId { get; set; }

    public int? VehicleOperationId { get; set; }

    public Guid TenantId { get; set; }

    public virtual SubCategory SubCategory { get; set; }

    public virtual VehicleOperation VehicleOperation { get; set; }
}