// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class VehicleEquipment
{
    public int Id { get; set; }

    public int? VehicleId { get; set; }

    public DateTime? InstallationDate { get; set; }

    public DateTime? LastControlDate { get; set; }

    public string EquipmentName { get; set; }

    public string CreateBy { get; set; }

    public string EditedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? EditedOn { get; set; }

    public int? VehicleRebricEquipmentId { get; set; }

    public bool? FollowUpNeed { get; set; }

    public string Description { get; set; }

    public bool? Archive { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnVehicle Vehicle { get; set; }

    public virtual VehicleRebricEquipment VehicleRebricEquipment { get; set; }
}