// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class VehicleDashboarDatum
{
    public int Litre { get; set; }

    public int? Km { get; set; }

    public string Periode { get; set; }

    public double? FuelCost { get; set; }

    public double? ElectricRechargeCost { get; set; }

    public double? TotalFuelRechargeCost { get; set; }

    public double? MaintenanceCost { get; set; }

    public double? LicenceCost { get; set; }

    public double? RepairCost { get; set; }

    public double? TotalCosts { get; set; }

    public long? Index { get; set; }

    public int? DistanceParcourue { get; set; }

    public double? Consommation { get; set; }

    public Guid TenantId { get; set; }
}
