// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class VehiculeOperationRubric
{
    public int Id { get; set; }

    public string Label { get; set; }

    public bool? Recurrent { get; set; }

    public bool? AchiveAutomaticallyOldOperation { get; set; }

    public int? GroupId { get; set; }

    public int? DefaultValiditity { get; set; }

    public int? WarningDaysCount { get; set; }

    public bool? ByDays { get; set; }

    public bool? KmFollowApNeed { get; set; }

    public int? WarningKm { get; set; }

    public int? DefaultKmCount { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual Category Group { get; set; }

    public virtual ICollection<VehicleOperation> VehicleOperations { get; set; } = new List<VehicleOperation>();

    public virtual ICollection<VehicleRebricEquipment> VehicleRebricEquipments { get; set; } = new List<VehicleRebricEquipment>();
}

