// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class VehicleRebricEquipment
{
    public int Id { get; set; }

    public string Label { get; set; }

    public string Description { get; set; }

    public int? RubricId { get; set; }

    public Guid TenantId { get; set; }

    public virtual VehiculeOperationRubric Rubric { get; set; }

    public virtual ICollection<VehicleEquipment> VehicleEquipments { get; set; } = new List<VehicleEquipment>();
}