// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class VehicleFuelConsumationDetail
{
    public int Id { get; set; }

    public string Vehicle { get; set; }

    public double? _202404 { get; set; }

    public double? _202405 { get; set; }

    public double? _202406 { get; set; }

    public double? _202407 { get; set; }

    public Guid TenantId { get; set; }
}