// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class VehicleLog
{
    public int Id { get; set; }

    public string FromStatus { get; set; }

    public string ToStatus { get; set; }

    public DateTime? ChangeDate { get; set; }

    public string ChangeBy { get; set; }

    public int? VehicleId { get; set; }

    public int? UserId { get; set; }

    public string Instructions { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnVehicle Vehicle { get; set; }
}