// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class VehicleOperation
{
    public int Id { get; set; }

    public DateTime? ValidUntil { get; set; }

    public string Description { get; set; }

    public DateTime? OperationDate { get; set; }

    public int? GroupId { get; set; }

    public int? RubricId { get; set; }

    public int? VehicleId { get; set; }

    public bool? Archive { get; set; }

    public int? VehicleEquipmentId { get; set; }

    public int? KmInitial { get; set; }

    public int? NextOperationKm { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual Category Group { get; set; }

[NotMapped]
    public virtual VehiculeOperationRubric Rubric { get; set; }

    public virtual ICollection<VehicleOperationSubCategory> VehicleOperationSubCategories { get; set; } = new List<VehicleOperationSubCategory>();
}

