// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class VoucherReverseLog
{
    public int Id { get; set; }

    public string Original { get; set; }

    public string Extourne { get; set; }

    public DateTime AddNewTime { get; set; }

    public string EditBy { get; set; }

    public Guid TenantId { get; set; }

    public virtual TnPiece TnPiece { get; set; }
}