// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class VoucherCategory
{
    public int Id { get; set; }

    public string VoucherCategoryCode { get; set; }

    public string VoucherCategory1 { get; set; }

    public Guid TenantId { get; set; }
}