// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class VoucherStatusLog
{
    public int Id { get; set; }

    public string VoucherCode { get; set; }

    public string UserName { get; set; }

    public string OldStatus { get; set; }

    public string NewStatus { get; set; }

    public DateTime AddNewTime { get; set; }

    public Guid TenantId { get; set; }
}
