// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class VouchersToImport
{
    public int Id { get; set; }

    public string VoucherCode { get; set; }

    public string AgencyCode { get; set; }

    public string Client { get; set; }

    public double Amount { get; set; }

    public string Currency { get; set; }

    public string FileNumber { get; set; }

    public DateTime AddNewTime { get; set; }

    public string VoucherResponsible { get; set; }

    public Guid TenantId { get; set; }
}
