// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsCategoryFamily
{
    public int Id { get; set; }

    public string Label { get; set; }

    public string TitleQuery { get; set; }

    public string OpenUrl { get; set; }

    public string CreatorFieldName { get; set; }

    public string ManagerFieldName { get; set; }

    public string EdmInterfaceName { get; set; }

    public string LabelDashboard { get; set; }

    public string Icon { get; set; }

    public string WorkflowGroupType { get; set; }

    public bool HasMvtDateDefaultValue { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<DashboardOrderingField> DashboardOrderingFields { get; set; } = new List<DashboardOrderingField>();

    public virtual ICollection<DashboardStatus> DashboardStatuses { get; set; } = new List<DashboardStatus>();

    public virtual ICollection<WfsCategory> WfsCategories { get; set; } = new List<WfsCategory>();

    public virtual ICollection<WfsValidationWorkflow> WfsValidationWorkflows { get; set; } = new List<WfsValidationWorkflow>();
}
