// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsCategory
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Label { get; set; }

    public bool? IsActive { get; set; }

    public string EntityStatusFieldName { get; set; }

    public string EntityIdFieldName { get; set; }

    public string SousModule { get; set; }

    public string EntityName { get; set; }

    public bool? IsVisible { get; set; }

    public int? CategoryFamilyId { get; set; }

    public bool? IsAscending { get; set; }

    public string OrderBy { get; set; }

    public bool? CanSendEmail { get; set; }

    public string CreatorFieldsName { get; set; }

    public bool? HasMvtDate { get; set; }

    public string ManagerFieldName { get; set; }

    public Guid TenantId { get; set; }

    public virtual WfsCategoryFamily CategoryFamily { get; set; }

    public virtual ICollection<DashboardCategoryStatus> DashboardCategoryStatuses { get; set; } = new List<DashboardCategoryStatus>();

    public virtual ICollection<DashboardLabel> DashboardLabels { get; set; } = new List<DashboardLabel>();

    public virtual ICollection<WfsAgency> WfsAgencies { get; set; } = new List<WfsAgency>();

    public virtual ICollection<WfsEmailTemplate> WfsEmailTemplates { get; set; } = new List<WfsEmailTemplate>();

    public virtual ICollection<WfsGroupCategory> WfsGroupCategories { get; set; } = new List<WfsGroupCategory>();

    public virtual ICollection<WfsGroup> WfsGroups { get; set; } = new List<WfsGroup>();

    public virtual ICollection<WfsLinkFrom> WfsLinkFroms { get; set; } = new List<WfsLinkFrom>();

    public virtual ICollection<WfsPerson> WfsPeople { get; set; } = new List<WfsPerson>();

    public virtual ICollection<WfsStatus> WfsStatuses { get; set; } = new List<WfsStatus>();
}