// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsCondition
{
    public int Id { get; set; }

    public string Label { get; set; }

    public string ConditionRequest { get; set; }

    public string ExecutionRequest { get; set; }

    public string PostExecutionRequest { get; set; }

    public string Message { get; set; }

    public int? CategoryFamilyId { get; set; }

    public int? EmailTemplateId { get; set; }

    public bool? Creator { get; set; }

    public bool? Manager { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<WfsStatusLinkCondition> WfsStatusLinkConditions { get; set; } = new List<WfsStatusLinkCondition>();
}