// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsEmailTemplate
{
    public int Id { get; set; }

    public int EmailTemplateId { get; set; }

    public int WfscategoryId { get; set; }

    public string EmailTemplateTitle { get; set; }

    public Guid TenantId { get; set; }

    public virtual WfsCategory Wfscategory { get; set; }
}