// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsExtraReadRestriction
{
    public int Id { get; set; }

    public string Label { get; set; }

    public string FieldsName { get; set; }

    public int? WfsCategoryFamily { get; set; }

    public string Query { get; set; }

    public bool? VisibleOnQuery { get; set; }

    public bool? VisibleOnActions { get; set; }

    public bool? ShowRelativeRequests { get; set; }

    public bool? IsGroup { get; set; }

    public Guid TenantId { get; set; }
}
