// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsGroupJobTitle
{
    public int Id { get; set; }

    public string JobTtitleId { get; set; }

    public int? GroupId { get; set; }

    public Guid TenantId { get; set; }
}