// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsGroupStatus
{
    public int Id { get; set; }

    public int? StatusId { get; set; }

    public int? GroupId { get; set; }

    public Guid TenantId { get; set; }

    public virtual WfsGroup Group { get; set; }

    public virtual WfsStatus Status { get; set; }
}