// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsIcon
{
    public int Id { get; set; }

    public string Icon { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<WfsStatus> WfsStatuses { get; set; } = new List<WfsStatus>();
}