// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsJobTitle
{
    public int Id { get; set; }

    public int? JobTitleId { get; set; }

    public int? GroupStatusWorkflowId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual WfsGroup GroupStatusWorkflow { get; set; }
}

