// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsLinkFrom
{
    public int Id { get; set; }

    public string FormName { get; set; }

    public int? CategoryId { get; set; }

    public string EntityName { get; set; }

    public string EntityIdFieldName { get; set; }

    public string EntityFieldName { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual WfsCategory Category { get; set; }

    public virtual ICollection<WfsStatusLink> WfsStatusLinks { get; set; } = new List<WfsStatusLink>();
}

