// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsPerson
{
    public int Id { get; set; }

    public int PersonId { get; set; }

    public string UserName { get; set; }

    public int WfscategoryId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual Person Person { get; set; }

[NotMapped]
    public virtual WfsCategory Wfscategory { get; set; }
}

