// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsStatusLink
{
    public int Id { get; set; }

    public int? WorkflowStatusFrom { get; set; }

    public int? WorkflowStatusTo { get; set; }

    public int? FormId { get; set; }

    public string ExtraFieldQuery { get; set; }

    public int? ConditionId { get; set; }

    public int? EmailTemplateId { get; set; }

    public bool? Creator { get; set; }

    public string Name { get; set; }

    public bool? Manager { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<DestinatorsEmailTemplate> DestinatorsEmailTemplates { get; set; } = new List<DestinatorsEmailTemplate>();

[NotMapped]
    public virtual WfsLinkFrom Form { get; set; }

    public virtual ICollection<WfsStatusLinkCondition> WfsStatusLinkConditions { get; set; } = new List<WfsStatusLinkCondition>();
}

