// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsStatusLinkCondition
{
    public int Id { get; set; }

    public int? StatusLinkId { get; set; }

    public int? CondtionId { get; set; }

    public Guid TenantId { get; set; }

    public virtual WfsCondition Condtion { get; set; }

    public virtual WfsStatusLink StatusLink { get; set; }
}