// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsStatusPermission
{
    public int StatusId { get; set; }

    public int PermissionId { get; set; }

    public bool? Value { get; set; }

    public Guid TenantId { get; set; }
}