// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsStatus
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Label { get; set; }

    public string Description { get; set; }

    public bool? SystemStatus { get; set; }

    public bool? IsActive { get; set; }

    public int? CategoryWorkflowId { get; set; }

    public int? StatusOrder { get; set; }

    public string PositionNodeX { get; set; }

    public string PositionNodeY { get; set; }

    public int? IconId { get; set; }

    public bool? IsInitial { get; set; }

    public bool? IsShowInDashboard { get; set; }

    public bool? IsFinal { get; set; }

    public bool? IsBlocked { get; set; }

    public string Color { get; set; }

    public bool? IsCancelationStatus { get; set; }

    public Guid TenantId { get; set; }

    public virtual WfsCategory CategoryWorkflow { get; set; }

    public virtual ICollection<DashboardStatusStep> DashboardStatusSteps { get; set; } = new List<DashboardStatusStep>();

    public virtual WfsIcon Icon { get; set; }

    public virtual ICollection<WfsGroupStatus> WfsGroupStatuses { get; set; } = new List<WfsGroupStatus>();
}