// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsStatusExtraReadRestriction
{
    public int Id { get; set; }

    public int? StatusId { get; set; }

    public int? RestrictionId { get; set; }

    public Guid TenantId { get; set; }
}
