// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsValidationWorkFlowGroup
{
    public int Id { get; set; }

    public int? ValidationGroupId { get; set; }

    public int? WorkflowId { get; set; }

    public int? GroupOrder { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? CreateUserId { get; set; }

    public Guid TenantId { get; set; }

    public virtual WfsValidationGroup ValidationGroup { get; set; }

    public virtual WfsValidationWorkflow Workflow { get; set; }
}