// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsValidationGroupJobTitle
{
    public int Id { get; set; }

    public int? GroupId { get; set; }

    public int? TitleId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? CreateUserId { get; set; }

    public int? AgencyId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual WfsValidationGroup Group { get; set; }

[NotMapped]
    public virtual JobTitle Title { get; set; }
}

