// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WfsValidationGroup
{
    public int Id { get; set; }

    public string Label { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? CreateUserId { get; set; }

    public bool? Active { get; set; }

    public string Observation { get; set; }

    public bool? SendEmail { get; set; }

    public int? CategoryFamilyId { get; set; }

    public string GroupEmail { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<WfsValidationGroupJobTitle> WfsValidationGroupJobTitles { get; set; } = new List<WfsValidationGroupJobTitle>();

    public virtual ICollection<WfsValidationGroupMember> WfsValidationGroupMembers { get; set; } = new List<WfsValidationGroupMember>();

    public virtual ICollection<WfsValidationWorkFlowGroup> WfsValidationWorkFlowGroups { get; set; } = new List<WfsValidationWorkFlowGroup>();
}