// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WorkflowGroupParent
{
    public int Id { get; set; }

    public int WorkflowGroupId { get; set; }

    public int WorkflowGroupParentId { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual WorkflowGroup WorkflowGroup { get; set; }

[NotMapped]
    public virtual WorkflowGroup WorkflowGroupParentNavigation { get; set; }
}

