// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WorkflowNotification
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Icon { get; set; }

    public string Libelle { get; set; }

    public string Role { get; set; }

    public string Sp { get; set; }

    public string Type { get; set; }

    public string Url { get; set; }

    public string Site { get; set; }

    public bool Visible { get; set; }

    public Guid? RowGuid { get; set; }

    public string SpecificType { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<WorkflowGroupNotification> WorkflowGroupNotifications { get; set; } = new List<WorkflowGroupNotification>();
}