// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WorkingWeekPattern
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double TotalWorkingHoursPerWeek { get; set; }

    public int MaxTotalHoursPerDay { get; set; }

    public int BreakPerDayInMinute { get; set; }

    public int MinimumLunchTimePerDay { get; set; }

    public int MondayRate { get; set; }

    public int TuesdayRate { get; set; }

    public int WednesdayRate { get; set; }

    public int ThursdayRate { get; set; }

    public int FridayRate { get; set; }

    public int SaturdayRate { get; set; }

    public int SundayRate { get; set; }

    public int MorningBreak { get; set; }

    public int AfternoonBreak { get; set; }

    public Guid TenantId { get; set; }
}