// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WorkflowPaymentVoucher
{
    public int Id { get; set; }

    public string PaymentVoucherPrNumber { get; set; }

    public string InvoiceVoucherPrNumber { get; set; }

    public string WorkflowStatut { get; set; }

    public int? GroupFrom { get; set; }

    public DateTime? ReceivedOn { get; set; }

    public DateTime? TreatedOn { get; set; }

    public bool Visible { get; set; }

    public string Comments { get; set; }

    public string TreatedBy { get; set; }

    public string Action { get; set; }

    public bool? Bpp { get; set; }

    public bool InjectedToGed { get; set; }

    public string SenderBy { get; set; }

    public int? GroupTo { get; set; }

    public string Responsable { get; set; }

    public string CashReceiver { get; set; }

    public string SuccessResult { get; set; }

    public int? UserInWorkflowGroup { get; set; }

    public bool? ToPayLater { get; set; }

    public bool? Synchronized { get; set; }

    public Guid TenantId { get; set; }

    public virtual WorkflowGroup GroupFromNavigation { get; set; }

    public virtual WorkflowGroup GroupToNavigation { get; set; }
}