// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WorkflowGroup
{
    public int Id { get; set; }

    public string GroupName { get; set; }

    public bool IsFinance { get; set; }

    public double LimitAmountRef { get; set; }

    public bool? SendMail { get; set; }

    public bool? CanSendToFinance { get; set; }

    public string Type { get; set; }

    public bool? HasTablet { get; set; }

    public bool? IsActive { get; set; }

    public Guid? RowGuid { get; set; }

    public string MailTemplateId { get; set; }

    public Guid TenantId { get; set; }

    public virtual ICollection<TnBankTransfer> TnBankTransfers { get; set; } = new List<TnBankTransfer>();

    public virtual ICollection<WorkflowGroupNotification> WorkflowGroupNotifications { get; set; } = new List<WorkflowGroupNotification>();

    public virtual ICollection<WorkflowGroupParent> WorkflowGroupParentWorkflowGroupParentNavigations { get; set; } = new List<WorkflowGroupParent>();

    public virtual ICollection<WorkflowGroupParent> WorkflowGroupParentWorkflowGroups { get; set; } = new List<WorkflowGroupParent>();

    public virtual ICollection<WorkflowPaymentVoucher> WorkflowPaymentVoucherGroupFromNavigations { get; set; } = new List<WorkflowPaymentVoucher>();

    public virtual ICollection<WorkflowPaymentVoucher> WorkflowPaymentVoucherGroupToNavigations { get; set; } = new List<WorkflowPaymentVoucher>();

    public virtual ICollection<WorkflowUser> WorkflowUsers { get; set; } = new List<WorkflowUser>();

    public virtual ICollection<WorkflowVoucher> WorkflowVouchers { get; set; } = new List<WorkflowVoucher>();
}