// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WorkflowVoucher
{
    public int Id { get; set; }

    public string VoucherPrNumber { get; set; }

    public string WorkflowStatut { get; set; }

    public int WorkflowGroup { get; set; }

    public DateTime? ReceivedOn { get; set; }

    public DateTime? TreatedOn { get; set; }

    public bool Visible { get; set; }

    public string Comments { get; set; }

    public string Responsable { get; set; }

    public string Action { get; set; }

    public bool? Bpp { get; set; }

    public string Owner { get; set; }

    public bool? Synchronized { get; set; }

    public Guid TenantId { get; set; }

[NotMapped]
    public virtual WorkflowGroup WorkflowGroupNavigation { get; set; }
}

