// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WorkflowGroupNotification
{
    public int Id { get; set; }

    public int WorkflowGroupId { get; set; }

    public int WorkflowNotificationId { get; set; }

    public Guid TenantId { get; set; }

    public virtual WorkflowGroup WorkflowGroup { get; set; }

    public virtual WorkflowNotification WorkflowNotification { get; set; }
}