// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WorkflowUser
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public int WorkflowGroup { get; set; }

    public Guid TenantId { get; set; }

    public virtual WorkflowGroup WorkflowGroupNavigation { get; set; }
}