// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WorkflowLog
{
    public int Id { get; set; }

    public string EntityName { get; set; }

    public string EntityId { get; set; }

    public int WorkflowStatusId { get; set; }

    public DateTime OccuredAt { get; set; }

    public string CreatedBy { get; set; }

    public string Comments { get; set; }

    public DateTime? MovementDate { get; set; }

    public Guid TenantId { get; set; }
}