// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WsCallsLog
{
    public int Id { get; set; }

    public string Dossier { get; set; }

    public string MethodName { get; set; }

    public DateTime? CallDate { get; set; }

    public string Response { get; set; }

    public string Body { get; set; }

    public string Reference { get; set; }

    public string ErrorMessage { get; set; }

    public bool? Success { get; set; }

    public string SuccessMessage { get; set; }

    public string WarningMessage { get; set; }

    public bool? WarningRequired { get; set; }

    public Guid TenantId { get; set; }
}