// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WsConfigFileType
{
    public int ConfigId { get; set; }

    public string FileType { get; set; }

    public Guid TenantId { get; set; }
}
