// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace DMS.Entities.Models;

public partial class WsFileUpdate
{
    public int Id { get; set; }

    public string Dossier { get; set; }

    public DateTime? LastSreferenceUpdate { get; set; }

    public DateTime? LastMileStonesUpdate { get; set; }

    public DateTime? LastShipmentHeaderUpdate { get; set; }

    public DateTime? LastArrivedAtPort { get; set; }

    public DateTime? LastDepartedFromPort { get; set; }

    public DateTime? LastGreenLightUpdate { get; set; }

    public DateTime? CustomClearanceUnderwayUpdate { get; set; }

    public DateTime? CustomClearanceCompleteUpdate { get; set; }

    public DateTime? LastDeliveredToSiteUpdate { get; set; }

    public Guid TenantId { get; set; }
}
