// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.Entities.Models;

public partial class Currency
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Label { get; set; }

    public DateTime AddNewTime { get; set; }
}