// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Master.Entities.Models;

public partial class ERPMasterContext : DbContext
{
    public ERPMasterContext(DbContextOptions<ERPMasterContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuthLoginChallenge> AuthLoginChallenges { get; set; }

    public virtual DbSet<AuthRefreshTokens> AuthRefreshTokens { get; set; }

    public virtual DbSet<Currency> Currency { get; set; }

    public virtual DbSet<DbInstance> DbInstance { get; set; }

    public virtual DbSet<EfMigrationsHistory> EfMigrationsHistories { get; set; }

    public virtual DbSet<ErpCountries> ErpCountries { get; set; }

    public virtual DbSet<ErpTenants> ErpTenants { get; set; }

    public virtual DbSet<ErpUsers> ErpUsers { get; set; }

    public virtual DbSet<ErpUserTenants> ErpUserTenants { get; set; }

    public virtual DbSet<GedDirectory> GedDirectory { get; set; }

    public virtual DbSet<MasterAdminUsers> MasterAdminUsers { get; set; }

    public virtual DbSet<MasterErpDatabaseRef> MasterErpDatabaseRef { get; set; }

    public virtual DbSet<MasterErpGlobalConfigs> MasterErpGlobalConfigs { get; set; }

    public virtual DbSet<MasterErpIndustriesClient> MasterErpIndustriesClients { get; set; }

    public virtual DbSet<MasterErpIndustries> MasterErpIndustries { get; set; }

    public virtual DbSet<MasterErpMailTemplates> MasterErpMailTemplates { get; set; }

    public virtual DbSet<MasterErpModules> MasterErpModules { get; set; }

    public virtual DbSet<MasterErpModuleClient> MasterErpModuleClient { get; set; }

    public virtual DbSet<MasterErpUser> MasterErpUsers { get; set; }

    public virtual DbSet<RefIdMap> RefIdMaps { get; set; }

    public virtual DbSet<RefInitConfig> RefInitConfigs { get; set; }

    public virtual DbSet<RefInitConfigRaw> RefInitConfigRaws { get; set; }

    public virtual DbSet<RegisterAuthCodes> RegisterAuthCodes { get; set; }

    public virtual DbSet<RegisterCompletionToken> RegisterCompletionTokens { get; set; }

    public virtual DbSet<TenantAgencyProfile> TenantAgencyProfile { get; set; }

    public virtual DbSet<TenantInitJob> TenantInitJobs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("dms_5", "allocation_strategy", new[] { "FIFO", "BY_CURRENCY", "MANUAL" })
            .HasPostgresEnum("dms_5", "clearing_type", new[] { "CLIENT", "SUPPLIER" })
            .HasPostgresEnum("dms_5", "close_mode", new[] { "LEAVE_OPEN", "FORCE_CLOSE_WRITE_OFF" })
            .HasPostgresEnum("dms_5", "piece_type", new[] { "INVOICE", "CREDIT", "PAYMENT_IN", "PAYMENT_OUT" })
            .HasPostgresEnum("dms_5", "post_mode", new[] { "DRAFT", "POST_TO_GL" })
            .HasPostgresEnum("dms_5", "rate_policy", new[] { "ECB_SPOT", "BANK" })
            .HasPostgresEnum("dms_7", "allocation_strategy", new[] { "FIFO", "BY_CURRENCY", "MANUAL" })
            .HasPostgresEnum("dms_7", "clearing_type", new[] { "CLIENT", "SUPPLIER" })
            .HasPostgresEnum("dms_7", "close_mode", new[] { "LEAVE_OPEN", "FORCE_CLOSE_WRITE_OFF" })
            .HasPostgresEnum("dms_7", "piece_type", new[] { "INVOICE", "CREDIT", "PAYMENT_IN", "PAYMENT_OUT" })
            .HasPostgresEnum("dms_7", "post_mode", new[] { "DRAFT", "POST_TO_GL" })
            .HasPostgresEnum("dms_7", "rate_policy", new[] { "ECB_SPOT", "BANK" })
            .HasPostgresEnum("dms_new_ref", "allocation_strategy", new[] { "FIFO", "BY_CURRENCY", "MANUAL" })
            .HasPostgresEnum("dms_new_ref", "clearing_type", new[] { "CLIENT", "SUPPLIER" })
            .HasPostgresEnum("dms_new_ref", "close_mode", new[] { "LEAVE_OPEN", "FORCE_CLOSE_WRITE_OFF" })
            .HasPostgresEnum("dms_new_ref", "piece_type", new[] { "INVOICE", "CREDIT", "PAYMENT_IN", "PAYMENT_OUT" })
            .HasPostgresEnum("dms_new_ref", "post_mode", new[] { "DRAFT", "POST_TO_GL" })
            .HasPostgresEnum("dms_new_ref", "rate_policy", new[] { "ECB_SPOT", "BANK" })
            .HasPostgresEnum("dms_reference", "allocation_strategy", new[] { "FIFO", "BY_CURRENCY", "MANUAL" })
            .HasPostgresEnum("dms_reference", "clearing_type", new[] { "CLIENT", "SUPPLIER" })
            .HasPostgresEnum("dms_reference", "close_mode", new[] { "LEAVE_OPEN", "FORCE_CLOSE_WRITE_OFF" })
            .HasPostgresEnum("dms_reference", "piece_type", new[] { "INVOICE", "CREDIT", "PAYMENT_IN", "PAYMENT_OUT" })
            .HasPostgresEnum("dms_reference", "post_mode", new[] { "DRAFT", "POST_TO_GL" })
            .HasPostgresEnum("dms_reference", "rate_policy", new[] { "ECB_SPOT", "BANK" });

        modelBuilder.Entity<AuthLoginChallenge>(entity =>
        {
            entity.HasKey(e => e.ChallengeId).HasName("auth_login_challenges_pkey");

            entity.ToTable("auth_login_challenges", "erpmaster");

            entity.HasIndex(e => e.ExpiresAtUtc, "ix_auth_login_challenges_expires_at_utc");

            entity.HasIndex(e => e.UserId, "ix_auth_login_challenges_user_id");

            entity.Property(e => e.ChallengeId).HasColumnName("challenge_id");
            entity.Property(e => e.AttemptsRemaining)
                .HasDefaultValue(0)
                .HasColumnName("attempts_remaining");
            entity.Property(e => e.ChallengeType).HasColumnName("challenge_type");
            entity.Property(e => e.ConsumedAtUtc).HasColumnName("consumed_at_utc");
            entity.Property(e => e.CreatedAtUtc)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at_utc");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnName("email");
            entity.Property(e => e.ExpiresAtUtc).HasColumnName("expires_at_utc");
            entity.Property(e => e.IsConsumed)
                .HasDefaultValue(false)
                .HasColumnName("is_consumed");
            entity.Property(e => e.OtpCode).HasColumnName("otp_code");
            entity.Property(e => e.UserId).HasColumnName("user_id");
        });

        modelBuilder.Entity<AuthRefreshTokens>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("auth_refresh_tokens_pkey");

            entity.ToTable("auth_refresh_tokens", "erpmaster");

            entity.Property(e => e.UserId)
                .ValueGeneratedNever()
                .HasColumnName("user_id");
            entity.Property(e => e.ActiveRefreshTokenId)
                .IsRequired()
                .HasColumnName("active_refresh_token_id");
            entity.Property(e => e.ExpiresAtUtc).HasColumnName("expires_at_utc");
            entity.Property(e => e.IsCompromised)
                .HasDefaultValue(false)
                .HasColumnName("is_compromised");
            entity.Property(e => e.UpdatedAtUtc)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at_utc");

            entity.HasOne(d => d.User).WithOne(p => p.AuthRefreshTokens)
                .HasForeignKey<AuthRefreshTokens>(d => d.UserId)
                .HasConstraintName("fk_auth_refresh_tokens_user");
        });

        modelBuilder.Entity<Currency>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("currency_pkey");

            entity.ToTable("currency", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .HasColumnName("code");
            entity.Property(e => e.Label)
                .HasMaxLength(50)
                .HasColumnName("label");
        });

        modelBuilder.Entity<DbInstance>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("db_instance_pkey");

            entity.ToTable("db_instance", "erpmaster");

            entity.HasIndex(e => e.IsDefault, "ix_db_instance_is_default").HasFilter("(is_default = true)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.AdminPassword)
                .IsRequired()
                .HasColumnName("admin_password");
            entity.Property(e => e.AdminUser)
                .IsRequired()
                .HasColumnName("admin_user");
            entity.Property(e => e.DbName).HasColumnName("db_name");
            entity.Property(e => e.DbUser)
                .IsRequired()
                .HasColumnName("db_user");
            entity.Property(e => e.EdmTempDirectory).HasColumnName("edm_temp_directory");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.IsDefault)
                .HasDefaultValue(false)
                .HasColumnName("is_default");
            entity.Property(e => e.Password).HasColumnName("password");
            entity.Property(e => e.ReadOnlyPassword).HasColumnName("read_only_password");
            entity.Property(e => e.ReadOnlyUser).HasColumnName("read_only_user");
            entity.Property(e => e.ServerAddress)
                .IsRequired()
                .HasColumnName("server_address");
            entity.Property(e => e.ServerName).HasColumnName("server_name");
        });

        modelBuilder.Entity<EfMigrationsHistory>(entity =>
        {
            entity.HasKey(e => e.MigrationId).HasName("__ef_migrations_history_pkey");

            entity.ToTable("__ef_migrations_history", "erpmaster");

            entity.Property(e => e.MigrationId)
                .HasMaxLength(150)
                .HasColumnName("migration_id");
            entity.Property(e => e.ProductVersion)
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnName("product_version");
        });

        modelBuilder.Entity<ErpCountries>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("country_codes_pkey");

            entity.ToTable("erp_countries", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CountryCode)
                .HasMaxLength(3)
                .HasColumnName("country_code");
            entity.Property(e => e.CountryFlagUrl).HasColumnName("country_flag_url");
            entity.Property(e => e.CountryName)
                .HasMaxLength(200)
                .HasColumnName("country_name");
            entity.Property(e => e.DefaultCurrency)
                .HasMaxLength(10)
                .HasColumnName("default_currency");
            entity.Property(e => e.DefaultEquivalenceCurrency)
                .HasMaxLength(10)
                .HasColumnName("default_equivalence_currency");
            entity.Property(e => e.DefaultLanguage)
                .HasMaxLength(50)
                .HasColumnName("default_language");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(false)
                .HasColumnName("is_active");
            entity.Property(e => e.Nationality)
                .HasMaxLength(200)
                .HasColumnName("nationality");
        });

        modelBuilder.Entity<ErpTenants>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("erp_tenants_pkey");

            entity.ToTable("erp_tenants", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_DATE")
                .HasColumnName("add_new_time");
            entity.Property(e => e.DbInstanceId).HasColumnName("db_instance_id");
            entity.Property(e => e.EntityName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("entity_name");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");

            entity.HasOne(d => d.DbInstance).WithMany(p => p.ErpTenants)
                .HasForeignKey(d => d.DbInstanceId)
                .HasConstraintName("tenants_instance_fk");
        });

        modelBuilder.Entity<ErpUsers>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("erp_users_pkey");

            entity.ToTable("erp_users", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.AuthCode)
                .HasMaxLength(6)
                .HasColumnName("auth_code");
            entity.Property(e => e.AuthCodeAttempts).HasColumnName("auth_code_attempts");
            entity.Property(e => e.EditTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("edit_time");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnName("email");
            entity.Property(e => e.FailedLoginAttempts)
                .HasDefaultValue(0)
                .HasColumnName("failed_login_attempts");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasColumnName("first_name");
            entity.Property(e => e.HasM2f).HasColumnName("has_m2f");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.IsBlocked).HasColumnName("is_blocked");
            entity.Property(e => e.LastAttempts)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("last_attempts");
            entity.Property(e => e.LastCodeGeneratedTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("last_code_generated_time");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasColumnName("last_name");
            entity.Property(e => e.LastPasswordChangeDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("last_password_change_date");
            entity.Property(e => e.M2fExpireDateTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("m2f_expire_date_time");
            entity.Property(e => e.NumberOfAttemptsLogin).HasColumnName("number_of_attempts_login");
            entity.Property(e => e.NumberOfCodeGenerated).HasColumnName("number_of_code_generated");
            entity.Property(e => e.Password).HasColumnName("password");
            entity.Property(e => e.PasswordSalt)
                .IsRequired()
                .HasDefaultValueSql("''::text")
                .HasColumnName("password_salt");
            entity.Property(e => e.Photo).HasColumnName("photo");
            entity.Property(e => e.ResetPasswordIsNeeded)
                .HasDefaultValue(false)
                .HasColumnName("reset_password_is_needed");
            entity.Property(e => e.UserName).HasColumnName("user_name");
        });

        modelBuilder.Entity<ErpUserTenants>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.TenantId }).HasName("erp_user_tenants_pkey");

            entity.ToTable("erp_user_tenants", "erpmaster");

            entity.HasIndex(e => e.UserId, "ux_erp_user_tenants_default_per_user")
                .IsUnique()
                .HasFilter("(is_default = true)");

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_DATE")
                .HasColumnName("add_new_time");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.IsDefault)
                .HasDefaultValue(false)
                .HasColumnName("is_default");
            entity.Property(e => e.IsErpUser)
                .HasDefaultValue(true)
                .HasColumnName("is_erp_user");

            entity.HasOne(d => d.Tenant).WithMany(p => p.ErpUserTenants)
                .HasForeignKey(d => d.TenantId)
                .HasConstraintName("fk_erp_user_tenants_tenant");

            entity.HasOne(d => d.User).WithOne(p => p.ErpUserTenants)
                .HasForeignKey<ErpUserTenants>(d => d.UserId)
                .HasConstraintName("fk_erp_user_tenants_user");
        });

        modelBuilder.Entity<GedDirectory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("ged_directory_pkey");

            entity.ToTable("ged_directory", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.DirectoryName)
                .HasMaxLength(500)
                .HasColumnName("directory_name");
            entity.Property(e => e.Domaine)
                .HasMaxLength(500)
                .HasColumnName("domaine");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("password");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("user_name");
        });

        modelBuilder.Entity<MasterAdminUsers>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("master_admin_users_pkey");

            entity.ToTable("master_admin_users", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.AuthCode)
                .HasMaxLength(6)
                .HasColumnName("auth_code");
            entity.Property(e => e.AuthCodeAttempts).HasColumnName("auth_code_attempts");
            entity.Property(e => e.EditTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("edit_time");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnName("email");
            entity.Property(e => e.FailedLoginAttempts)
                .HasDefaultValue(0)
                .HasColumnName("failed_login_attempts");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasColumnName("first_name");
            entity.Property(e => e.HasM2f).HasColumnName("has_m2f");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.IsBlocked).HasColumnName("is_blocked");
            entity.Property(e => e.LastAttempts)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("last_attempts");
            entity.Property(e => e.LastCodeGeneratedTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("last_code_generated_time");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasColumnName("last_name");
            entity.Property(e => e.LastPasswordChangeDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("last_password_change_date");
            entity.Property(e => e.M2fExpireDateTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("m2f_expire_date_time");
            entity.Property(e => e.NumberOfAttemptsLogin).HasColumnName("number_of_attempts_login");
            entity.Property(e => e.NumberOfCodeGenerated).HasColumnName("number_of_code_generated");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasColumnName("password");
            entity.Property(e => e.PasswordSalt)
                .IsRequired()
                .HasDefaultValueSql("''::text")
                .HasColumnName("password_salt");
            entity.Property(e => e.Photo).HasColumnName("photo");
            entity.Property(e => e.ResetPasswordIsNeeded)
                .HasDefaultValue(false)
                .HasColumnName("reset_password_is_needed");
            entity.Property(e => e.UserName).HasColumnName("user_name");
        });

        modelBuilder.Entity<MasterErpDatabaseRef>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("master_erp_database_ref_pkey");

            entity.ToTable("master_erp_database_ref", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.Name)
                .HasMaxLength(500)
                .HasColumnName("name");
            entity.Property(e => e.SqlServerInstanceId).HasColumnName("sql_server_instance_id");
            entity.Property(e => e.UrlDestinationLdf).HasColumnName("url_destination_ldf");
            entity.Property(e => e.UrlDestinationMdf).HasColumnName("url_destination_mdf");
            entity.Property(e => e.UrlSourceLdf).HasColumnName("url_source_ldf");
            entity.Property(e => e.UrlSourceMdf).HasColumnName("url_source_mdf");

            entity.HasOne(d => d.SqlServerInstance).WithMany(p => p.MasterErpDatabaseRefs)
                .HasForeignKey(d => d.SqlServerInstanceId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("fk_master_erp_database_ref_db_instance");
        });

        modelBuilder.Entity<MasterErpGlobalConfigs>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("master_erp_global_configs_pkey");

            entity.ToTable("master_erp_global_configs", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccessTokenExpiration).HasColumnName("access_token_expiration");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.DmsPhysicalPath).HasColumnName("dms_physical_path");
            entity.Property(e => e.DmsVirtualDirectoryName).HasColumnName("dms_virtual_directory_name");
            entity.Property(e => e.EnvironmentName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("environment_name");
            entity.Property(e => e.FrontDirectoryPath)
                .HasMaxLength(500)
                .HasColumnName("front_directory_path");
            entity.Property(e => e.GlobalDfsMainUrl).HasColumnName("global_dfs_main_url");
            entity.Property(e => e.GlobalDfsPath).HasColumnName("global_dfs_path");
            entity.Property(e => e.GlobalDfsPort).HasColumnName("global_dfs_port");
            entity.Property(e => e.GlobalDfsUserAddress).HasColumnName("global_dfs_user_address");
            entity.Property(e => e.GlobalDfsUserDomainName).HasColumnName("global_dfs_user_domain_name");
            entity.Property(e => e.GlobalDfsUserGroupName).HasColumnName("global_dfs_user_group_name");
            entity.Property(e => e.GlobalDfsUserId)
                .HasMaxLength(500)
                .HasColumnName("global_dfs_user_id");
            entity.Property(e => e.GlobalDfsUserName)
                .HasMaxLength(500)
                .HasColumnName("global_dfs_user_name");
            entity.Property(e => e.GlobalDfsUserPassword)
                .HasMaxLength(500)
                .HasColumnName("global_dfs_user_password");
            entity.Property(e => e.GlobalDfsUserRole).HasColumnName("global_dfs_user_role");
            entity.Property(e => e.GlobalSmtpAccount)
                .HasMaxLength(500)
                .HasColumnName("global_smtp_account");
            entity.Property(e => e.GlobalSmtpPasswordHash)
                .HasMaxLength(500)
                .HasColumnName("global_smtp_password_hash");
            entity.Property(e => e.GlobalSmtpPort).HasColumnName("global_smtp_port");
            entity.Property(e => e.GlobalSmtpUser)
                .HasMaxLength(500)
                .HasColumnName("global_smtp_user");
            entity.Property(e => e.HasCaptcha)
                .HasDefaultValue(false)
                .HasColumnName("has_captcha");
            entity.Property(e => e.HasM2f).HasColumnName("has_m2f");
            entity.Property(e => e.HasResetPasswordEveryXDays).HasColumnName("has_reset_password_every_x_days");
            entity.Property(e => e.M2fActiveTime)
                .HasDefaultValue(10)
                .HasColumnName("m2f_active_time");
            entity.Property(e => e.M2fAlwaysAsk).HasColumnName("m2f_always_ask");
            entity.Property(e => e.M2fFrequencyXDays)
                .HasDefaultValue(7)
                .HasColumnName("m2f_frequency_x_days");
            entity.Property(e => e.M2fNumberOfTries)
                .HasDefaultValue(3)
                .HasColumnName("m2f_number_of_tries");
            entity.Property(e => e.M2fUserCanControl).HasColumnName("m2f_user_can_control");
            entity.Property(e => e.MinPasswordLength)
                .HasDefaultValue(8)
                .HasColumnName("min_password_length");
            entity.Property(e => e.NumberOfRegenerateCode).HasColumnName("number_of_regenerate_code");
            entity.Property(e => e.RequireDigits).HasColumnName("require_digits");
            entity.Property(e => e.RequireLowerCase).HasColumnName("require_lower_case");
            entity.Property(e => e.RequirePasswordComplexity).HasColumnName("require_password_complexity");
            entity.Property(e => e.RequireSpecialCharacters).HasColumnName("require_special_characters");
            entity.Property(e => e.RequireUpperCase).HasColumnName("require_upper_case");
            entity.Property(e => e.ResetPasswordEveryXDays).HasColumnName("reset_password_every_x_days");
            entity.Property(e => e.ShowCaptchaLoginAfterX).HasColumnName("show_captcha_login_after_x");
            entity.Property(e => e.TemporaryPhysicalPath)
                .HasMaxLength(500)
                .HasColumnName("temporary_physical_path");
            entity.Property(e => e.VirtualDirectoryName)
                .HasMaxLength(50)
                .HasColumnName("virtual_directory_name");
            entity.Property(e => e.ZipLibraryPath)
                .HasMaxLength(500)
                .HasColumnName("zip_library_path");
        });

        modelBuilder.Entity<MasterErpIndustriesClient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("master_erp_industries_client_pkey");

            entity.ToTable("master_erp_industries_client", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.IndustryCode)
                .IsRequired()
                .HasMaxLength(5)
                .HasColumnName("industry_code");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");

            entity.HasOne(d => d.Tenant).WithMany(p => p.MasterErpIndustriesClient)
                .HasForeignKey(d => d.TenantId)
                .HasConstraintName("fk_master_erp_industries_client_tenant");
        });

        modelBuilder.Entity<MasterErpIndustries>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("master_erp_industries_pkey");

            entity.ToTable("master_erp_industries", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.CodeIndustry)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("code_industry");
            entity.Property(e => e.DescriptionIndustry)
                .HasMaxLength(200)
                .HasColumnName("description_industry");
            entity.Property(e => e.EditTime)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("edit_time");
            entity.Property(e => e.LabelIndustry)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("label_industry");
            entity.Property(e => e.ProfilIndustry)
                .HasDefaultValue(0)
                .HasColumnName("profil_industry");
            entity.Property(e => e.Session).HasColumnName("session");
        });

        modelBuilder.Entity<MasterErpMailTemplates>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("master_erp_mail_templates_pkey");

            entity.ToTable("master_erp_mail_templates", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.Body)
                .IsRequired()
                .HasColumnName("body");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("code");
            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("label");
            entity.Property(e => e.MailFrom)
                .HasMaxLength(500)
                .HasColumnName("mail_from");
            entity.Property(e => e.Signature).HasColumnName("signature");
            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("subject");
            entity.Property(e => e.ToEmail).HasColumnName("to_email");
        });

        modelBuilder.Entity<MasterErpModules>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("master_erp_modules_pkey");

            entity.ToTable("master_erp_modules", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.DbPrefix)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("db_prefix");
            entity.Property(e => e.IconName)
                .HasMaxLength(50)
                .HasColumnName("icon_name");
            entity.Property(e => e.IconStyle)
                .HasMaxLength(50)
                .HasColumnName("icon_style");
            entity.Property(e => e.ModuleName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("module_name");
        });

        modelBuilder.Entity<MasterErpModuleClient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("master_erp_module_client_pkey");

            entity.ToTable("master_erp_module_client", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.MaxAgencies).HasColumnName("max_agencies");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");

            entity.HasOne(d => d.Module).WithMany(p => p.MasterErpModuleClient)
                .HasForeignKey(d => d.ModuleId)
                .HasConstraintName("fk_master_erp_module_client_module");

            entity.HasOne(d => d.Tenant).WithMany(p => p.MasterErpModuleClient)
                .HasForeignKey(d => d.TenantId)
                .HasConstraintName("fk_master_erp_module_client_tenant");
        });

        modelBuilder.Entity<MasterErpUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("master_erp_user_pkey");

            entity.ToTable("master_erp_user", "erpmaster");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddNewTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("add_new_time");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("email");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("first_name");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("last_name");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("user_name");
        });

        modelBuilder.Entity<RefIdMap>(entity =>
        {
            entity.HasKey(e => new { e.TenantGuid, e.TableName, e.SrcId }).HasName("ref_id_map_pkey");

            entity.ToTable("ref_id_map", "erpmaster");

            entity.Property(e => e.TenantGuid).HasColumnName("tenant_guid");
            entity.Property(e => e.TableName).HasColumnName("table_name");
            entity.Property(e => e.SrcId).HasColumnName("src_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.TgtId)
                .IsRequired()
                .HasColumnName("tgt_id");
        });

        modelBuilder.Entity<RefInitConfig>(entity =>
        {
            entity.HasKey(e => e.TableName).HasName("ref_init_config_pkey");

            entity.ToTable("ref_init_config", "erpmaster");

            entity.Property(e => e.TableName).HasColumnName("table_name");
            entity.Property(e => e.IsMapping)
                .HasDefaultValue(false)
                .HasColumnName("is_mapping");
            entity.Property(e => e.NeedDataInitialisation).HasColumnName("need_data_initialisation");
        });

        modelBuilder.Entity<RefInitConfigRaw>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("ref_init_config_raw", "erpmaster");

            entity.Property(e => e.Action).HasColumnName("action");
            entity.Property(e => e.Country).HasColumnName("country");
            entity.Property(e => e.Industry).HasColumnName("industry");
            entity.Property(e => e.Industryspecific).HasColumnName("industryspecific");
            entity.Property(e => e.Language).HasColumnName("language");
            entity.Property(e => e.NeedDataInitialisation).HasColumnName("need_data_initialisation");
            entity.Property(e => e.Order).HasColumnName("order");
            entity.Property(e => e.Request).HasColumnName("request");
            entity.Property(e => e.TableName).HasColumnName("table_name");
            entity.Property(e => e.TableSchema).HasColumnName("table_schema");
            entity.Property(e => e.UsedWithErpV3).HasColumnName("used_with_erp_v3");
        });

        modelBuilder.Entity<RegisterAuthCodes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("register_auth_codes_pkey");

            entity.ToTable("register_auth_codes", "erpmaster");

            entity.HasIndex(e => e.Email, "ix_register_auth_codes_email");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Attempts)
                .HasDefaultValue(0)
                .HasColumnName("attempts");
            entity.Property(e => e.CodeHash)
                .IsRequired()
                .HasColumnName("code_hash");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnName("email");
            entity.Property(e => e.ExpiresAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("expires_at");
            entity.Property(e => e.IsUsed)
                .HasDefaultValue(false)
                .HasColumnName("is_used");
            entity.Property(e => e.MaxAttempts)
                .HasDefaultValue(5)
                .HasColumnName("max_attempts");
            entity.Property(e => e.ResendCount)
                .HasDefaultValue(0)
                .HasColumnName("resend_count");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<RegisterCompletionToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("register_completion_tokens_pkey");

            entity.ToTable("register_completion_tokens", "erpmaster");

            entity.HasIndex(e => e.Email, "ix_register_completion_tokens_email");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.ConsumedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("consumed_at");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnName("email");
            entity.Property(e => e.ExpiresAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("expires_at");
        });

        modelBuilder.Entity<TenantAgencyProfile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("tenant_agency_profile_pkey");

            entity.ToTable("tenant_agency_profile", "erpmaster");

            entity.HasIndex(e => e.TenantId, "ux_tenant_agency_profile_tenant").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AgencyBuilding).HasColumnName("agency_building");
            entity.Property(e => e.AgencyCity).HasColumnName("agency_city");
            entity.Property(e => e.AgencyCode)
                .IsRequired()
                .HasColumnName("agency_code");
            entity.Property(e => e.AgencyCountry).HasColumnName("agency_country");
            entity.Property(e => e.AgencyEmail).HasColumnName("agency_email");
            entity.Property(e => e.AgencyName)
                .IsRequired()
                .HasColumnName("agency_name");
            entity.Property(e => e.AgencyPhoneNumber).HasColumnName("agency_phone_number");
            entity.Property(e => e.AgencyPostalCode).HasColumnName("agency_postal_code");
            entity.Property(e => e.AgencyPrintName).HasColumnName("agency_print_name");
            entity.Property(e => e.AgencyStreet).HasColumnName("agency_street");
            entity.Property(e => e.AgencyTaxId).HasColumnName("agency_tax_id");
            entity.Property(e => e.AgencyUserName).HasColumnName("agency_user_name");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CurrencyEq).HasColumnName("currency_eq");
            entity.Property(e => e.CurrencyRef).HasColumnName("currency_ref");
            entity.Property(e => e.IndustryCode).HasColumnName("industry_code");
            entity.Property(e => e.Other).HasColumnName("other");
            entity.Property(e => e.PreferredLanguage).HasColumnName("preferred_language");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Tenant).WithOne(p => p.TenantAgencyProfile)
                .HasForeignKey<TenantAgencyProfile>(d => d.TenantId)
                .HasConstraintName("fk_tenant_agency_profile_tenant");
        });

        modelBuilder.Entity<TenantInitJob>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("tenant_init_jobs_pkey");

            entity.ToTable("tenant_init_jobs", "erpmaster");

            entity.HasIndex(e => e.Status, "ix_tenant_init_jobs_status");

            entity.HasIndex(e => e.TenantId, "ix_tenant_init_jobs_tenant");

            entity.HasIndex(e => e.TenantId, "ux_tenant_init_jobs_active_tenant")
                .IsUnique()
                .HasFilter("(status = ANY (ARRAY['pending'::text, 'running'::text]))");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Attempts)
                .HasDefaultValue(0)
                .HasColumnName("attempts");
            entity.Property(e => e.CompletedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("completed_at");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.LastError).HasColumnName("last_error");
            entity.Property(e => e.MaxAttempts)
                .HasDefaultValue(3)
                .HasColumnName("max_attempts");
            entity.Property(e => e.Payload)
                .IsRequired()
                .HasColumnType("jsonb")
                .HasColumnName("payload");
            entity.Property(e => e.StartedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("started_at");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasDefaultValueSql("'pending'::text")
                .HasColumnName("status");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
        });
        modelBuilder.HasSequence("Ecriture_ID_seq", "dms_5");
        modelBuilder.HasSequence("Ecriture_ID_seq", "dms_7");
        modelBuilder.HasSequence("Ecriture_ID_seq", "dms_new_ref");
        modelBuilder.HasSequence("Ecriture_ID_seq", "dms_reference");
        modelBuilder.HasSequence("erp_countries_id_seq", "erpmaster");
        modelBuilder.HasSequence("erp_countries_id_seq", "erpmaster3");
        modelBuilder.HasSequence("ti_Relations_NÃ‚Â°_seq", "dms_5").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÃ‚Â°_seq", "dms_7").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÃ‚Â°_seq", "dms_new_ref").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÃ‚Â°_seq", "dms_reference").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÂ°_seq", "dms_5").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÂ°_seq", "dms_7").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÂ°_seq", "dms_reference").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÃƒâ€šÃ‚Â°_seq", "dms_new_ref").HasMax(2147483647L);
        modelBuilder.HasSequence("ti_Relations_NÃƒâ€šÃ‚Â°_seq", "dms_reference").HasMax(2147483647L);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

