// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.Entities.Models;

public partial class GedDirectory
{
    public int Id { get; set; }

    public string DirectoryName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Domaine { get; set; }

    public DateTime AddNewTime { get; set; }
}