// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Master.Entities.Models;

public partial class TenantAgencyProfile
{
    public int Id { get; set; }

    public int TenantId { get; set; }

    public string AgencyName { get; set; }

    public string AgencyCode { get; set; }

    public string AgencyCountry { get; set; }

    public string AgencyTaxId { get; set; }

    public string AgencyStreet { get; set; }

    public string AgencyBuilding { get; set; }

    public string AgencyPostalCode { get; set; }

    public string AgencyCity { get; set; }

    public string AgencyEmail { get; set; }

    public string AgencyPhoneNumber { get; set; }

    public string AgencyPrintName { get; set; }

    public string AgencyUserName { get; set; }

    public string CurrencyRef { get; set; }

    public string CurrencyEq { get; set; }

    public string Other { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string IndustryCode { get; set; }

    public string PreferredLanguage { get; set; }

    public virtual ErpTenants Tenant { get; set; }
}
